#!/bin/bash
# Copyright (c) 2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
SCRIPTS="$SCRIPTS/.."
. "$SCRIPTS/util.bash"

# Historique des versions gérées

logiciel=tar

version=0.3.1.0

version=0.4.0.1

[ "x$1" = x-v ] && version="$2" && shift && shift

ghcv="`ghc --version | sed -e 's/^.*version \([0-9.]*\).*$/\1/'`"
dest=$INSTALLS/ghc-$ghcv
archive=http://hackage.haskell.org/packages/archive/$logiciel/$version/$logiciel-$version.tar.gz

# Modifications

# Boulot

[ -d "$dest/lib/$logiciel-$version" ] && exit 0
[ -d "$dest/lib/ghc-$ghcv/$logiciel-$version" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
runghc Setup configure --prefix="$dest"

echo Compilation… >&2
runghc Setup build

echo Installation… >&2
sudo runghc Setup install
