#!/bin/bash
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

logiciel=7z

# Historique des versions gérées

version=4.57

version=4.65
modifs=dlopenPourTous

# Modifications

dlopenPourTous()
{
	filtrer CPP/Windows/DLL.cpp sed -e 's/_APPLE_CC_/_OH_NON_APPLE_CC_/'
	filtrer CPP/7zip/UI/Common/LoadCodecs.cpp sed -e 's/7z.dll/7z.so/g'
}

# Variables

dest="/usr/local/$logiciel-$version"
archive=http://heanet.dl.sourceforge.net/sourceforge/p7zip/p7zip_${version}_src_all.tar.bz2

[ -d "$dest" ] && exit 0

if [[ $version = r* ]] ; then
	obtenirEtAllerDansSvn -r ${version#r} $archive_svn
elif [[ $version = *-* ]] ; then
	obtenirEtAllerDansCvs -d $version $archive_cvs
else
	obtenirEtAllerDans "$archive"
fi

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
filtrer makefile sed -e '/^DEST_HOME=/c\
DEST_HOME='"$dest"'
'
filtrer makefile.machine sed -e '/^\(ALLFLAGS=.*\) -s /s//\1 /'

echo Compilation… >&2
make 7za 7z

echo Installation… >&2
sudo make install
sudo utiliser "$logiciel-$version"

rm -Rf /tmp/$$
