#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 4.57 || true
v 4.65 && modifs=dlopenPourTous || true
v 9.20.1 && modifs="dlopenPourTous sansLdl" || true
v 15.09 || true
v 15.14 && modifs="dlopenPourTous sansLdl clang" || true
v 16.02 || true

# Modifications

dlopenPourTous()
{
	filtrer CPP/Windows/DLL.cpp sed -e 's/_APPLE_CC_/_OH_NON_APPLE_CC_/'
	filtrer CPP/7zip/UI/Common/LoadCodecs.cpp sed -e 's/7z.dll/7z.so/g'
}

sansLdl()
{
	ldlOptionnel makefile.machine
}

clang()
{
	filtrer makefile.machine sed -e "s#g++#$CXX#g" -e "s#gcc#$CC#g"
	# clang est notablement plus strict sur le typage.
	filtrer CPP/Windows/ErrorMsg.cpp sed -e '/switch(errorCode/s/errorCode/(HRESULT)errorCode/'
}

# Variables

archive=http://heanet.dl.sourceforge.net/sourceforge/p7zip/p7zip_${version}_src_all.tar.bz2
archive=https://kent.dl.sourceforge.net/project/p7zip/p7zip/$version/p7zip_${version}_src_all.tar.bz2

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
for i in makefile makefile.common
do
	[ -e "$i" ] && filtrer "$i" sed -e '/^DEST_HOME=/c\
DEST_HOME='"$dest"'
' || true
done
filtrer makefile.machine sed -e '/^\(ALLFLAGS=.*\) -s /s//\1 /'

echo Compilation… >&2
make 7za 7z

echo Installation… >&2
sudo make install
sutiliser
