#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

prerequis="cntlm"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi [-u <compte>] [-s <suffixe démarreur>] [-p <port>] <fichier de conf cntlm>
TERMINE
	exit 1
}

analyserParametres()
{
	vars="config"
	config=
	suffixe=
	port=3128
	while [ $# -gt 0 ]
	do
		case "$1" in
			-s) suffixe="$2" ; shift ;;
			-p) port="$2" ; shift ;;
			-u) shift ; compte="$1" ;;
			*) apAffecter "$1" $vars ;;
		esac
		shift
	done
	
	if [ -z "$compte" ]
	then
		compte="`id -un`"
	fi
	
	[ ! -z "$config" ] || auSecours
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

eval "version=\"\$version_`echo "$logiciel" | cut -c 2-`\"" # On prend pour numéro de version installée celui de notre logiciel sous-jacent.

destiner

_patronTemp()
{
	case `uname` in
		FreeBSD) opts="-P \$pidfile" ; vars="$vars var/run" ;;
		*) opts= ;;
	esac
	case "$vars" in ?*)
		mkdir "$desttemp"
		serveur_patronVars "$desttemp" $vars
		optionsServeur="$optionsServeur -d0 $desttemp"
	esac
}

_pousserPatronTemp()
{
	local dest0="$1" dest="$2"
	
	# Copie.
	sudoku sh -c "mkdir -p \"$dest\" && ( cd \"$dest0\" && tar cf - . ) | ( cd \"$dest\" && tar xf - )"
	serveur_chownVars
}

if ! id "$compte" > /dev/null 2>&1
then

echo "Création de l'utilisateur…" >&2
creeCompte -s /bin/sh $compte

fi

echo "Auto-démarrage…" >&2
creerAmorceur()
{
	local desttemp="$TMP/$$/dest" vars opts optionsServeur
	
	_patronTemp "$desttemp"
	_pousserPatronTemp "$desttemp" "$dest"
	
	# Amorçage.
	
	serveur -u "$compte" $optionsServeur demon cntlm$suffixe "$destcntlm/bin/cntlm -c $config $opts"
}
creerAmorceur "$@"

sutiliser -
