#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=_cntlm

# Historique des versions gérées

prerequis="cntlm"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi [-u <compte>] [-s <suffixe démarreur>] [-p <port>] <fichier de conf cntlm>
TERMINE
	exit 1
}

analyserParametres()
{
	vars="config"
	config=
	suffixe=
	port=3128
	while [ $# -gt 0 ]
	do
		case "$1" in
			-s) suffixe="$2" ; shift ;;
			-p) port="$2" ; shift ;;
			-u) shift ; compte="$1" ;;
			*) apAffecter "$1" $vars ;;
		esac
		shift
	done
	
	if [ -z "$compte" ]
	then
		compte="`id -un`"
	fi
	
	[ ! -z "$config" ] || auSecours
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

eval "version=\"\$version_`echo "$logiciel" | cut -c 2-`\"" # On prend pour numéro de version installée celui de notre logiciel sous-jacent.
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

if ! id "$compte" > /dev/null 2>&1
then

echo "Création de l'utilisateur…" >&2
creeCompte -s /bin/sh $compte

fi

echo "Auto-démarrage…" >&2
case `uname` in
	FreeBSD) opts="-P \$pidfile" ;;
	*) opts= ;;
esac
serveur -u "$compte" demon cntlm$suffixe "$destcntlm/bin/cntlm -c $config $opts"

rm -Rf "$TMP/$$"
