#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=_exim

# Historique des versions gérées

prerequis="exim"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi (-d <domaine>)* <répertoire maildir>
TERMINE
	exit 1
}

analyserParametres()
{
	vars="mels"
	versionExim=
	domaines=
	compte=
	mels=
	paf=0
	pourriel=
	while [ $# -gt 0 ]
	do
		case "$1" in
			-u) shift ; compte="$1" ;;
			-d) shift ; domaines="$domaines $1" ;;
			*) apAffecter "$1" $vars ;;
		esac
		shift
	done

	if [ -z "$compte" ]
	then
		comptesEnvisages="exim mail mel"
		for compte in $comptesEnvisages personne
		do
			id "$compte" 2> /dev/null >&2 && break
		done
		if [ "$compte" = personne ]
		then
			echo "# Impossible de trouver un des comptes sous lequel tourner ($comptesEnvisages). Forcez un compte via l'option -u (il sera créé si nécessaire)." >&2
			exit 1
		fi
	fi
	
	[ -z "$versionExim" -a ! -z "$argVersion" ] && versionExim="$argVersion" || true
	[ -z "$versionExim" ] || prerequis="`echo " $prerequis " | sed -e "s# exim # exim $versionExim #g"`"
	
	# Si le traiteur de pourriel n'est pas mentionné, on branche rspam à partir de la 4.89, version à partir de laquelle je compile exim avec paf2 (qui repose sur la présence d'un analyseur de pourriel).
	if [ -z "$pourriel" ]
	then
		if pge "$versionExim" 4.89
		then
			pourriel=rspam+paf2
			paf= # paf2 n'a plus besoin des règles de paf (ce sont celles de rspam qui sont utilisées).
		fi
	fi
	
	[ ! -z "$mels" ] || auSecours
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

eval "version=\"\$version_`echo "$logiciel" | cut -c 2-`\"" # On prend pour numéro de version installée celui de notre logiciel sous-jacent.
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

if ! id "$compte" > /dev/null 2>&1
then

echo "Création de l'utilisateur…" >&2
creeCompte -s /bin/sh $compte # 4100

fi

if [ ! -d "$mels" ]
then

echo "Création de la base méls…" >&2

sudo mkdir -p "$mels"
sudo chown -R $compte: "$mels"
sudo chmod -R go-rwx "$mels"

fi

echo "Auto-démarrage…" >&2
case `uname` in
	Darwin)
		# Rien. On démarrera à la main.
		;;
	FreeBSD)
		serveur -d0 "$TMP/$$/dest" -d "$dest" -p "$destexim/var/spool/exim/exim-daemon.pid" LD_LIBRARY_PATH="$INSTALLS/lib" demon exim "$destexim/bin/exim -bd -q1m"
		if [ "$paf" = 1 ]
		then
		touch "$TMP/$$/dest/etc/exim.paf.regles"
			optionsPaf="--paf $dest/etc/exim.paf.regles"
		fi
		if [ ! -z "$pourriel" ]
		then
			optionsPaf="$optionsPaf --spam $pourriel"
		fi
		comptes="`dirname "$mels"`/comptes"
		"$SCRIPTS/eximConfig" $optionsPaf -u "$compte" `echo "$domaines" | sed -e 's/  *\([^ ]\)/ -d \1/g'` "$mels" "$comptes" > "$TMP/$$/exim.conf"
		sudo cp -R "$TMP/$$/dest" "$dest"
		sudo cp "$TMP/$$/exim.conf" "$destexim/etc/exim"
		sudo mkdir -p "$destexim/var/spool/exim/log"
		if [ "$paf" = 1 ]
		then
		sudo chown -R $compte: "$dest/etc/exim.paf.regles"
		fi
		sudo chown -R $compte: "$destexim/var/spool/exim"
		#[ -h /usr/sbin/sendmail -o ! -e /usr/sbin/sendmail ] && sudo rm -f /usr/sbin/sendmail && sudo ln -s "$destexim/bin/exim" /usr/sbin/sendmail
		# À FAIRE: permettre à sendmail sur tous les hôtes de passer par le même, ou passer par un ssmtp. Mais comment alors distinguer les méls de source locale?
		;;
esac

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
