#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=_mysql

# Historique des versions gérées

prerequis="mysql"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi <répertoire de la base>
TERMINE
	exit 1
}

analyserParametres()
{
	vars="bdd compte"
	while [ $# -gt 0 ]
	do
		case "$1" in
			*) apAffecter "$1" $vars ;;
		esac
		shift
	done

	if [ -z "$compte" ]
	then
		comptesEnvisages="mysql bdd db"
		for compte in $comptesEnvisages personne
		do
			id "$compte" 2> /dev/null >&2 && break
		done
		if [ "$compte" = personne ]
		then
			echo "# Impossible de trouver un des comptes sous lequel tourner ($comptesEnvisages). Forcez un compte en le précisant en second paramètre (il sera créé si nécessaire)." >&2
			exit 1
		fi
	fi
	
	[ ! -z "$bdd" ] || auSecours
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

eval "version=\"\$version_`echo "$logiciel" | cut -c 2-`\"" # On prend pour numéro de version installée celui de notre logiciel sous-jacent.
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

creerBase()
{
	sudo -u "$compte" mysql_install_db --datadir="$bdd"
	
	cat > "$bdd/my.cnf" <<TERMINE
# https://mariadb.com/blog/starting-mysql-low-memory-virtual-machines
# http://www.tocker.ca/2014/03/10/configuring-mysql-to-use-minimal-memory.html

[mysqld]
user = $compte
datadir = $bdd
pid-file = $bdd/my.pid
performance_schema = off # LE truc dont se passer sur petites machines en 5.6 (bouffe d'office 350 Mo de RAM).
innodb_buffer_pool_size = 8M
innodb_log_buffer_size = 1M
key_buffer_size = 10K

[server]
bind-address = 127.0.0.1
max_connections = 20
TERMINE
	chown "$compte:$compte" "$bdd/my.cnf"
}

creerAmorceur()
{
	case `uname` in
		Darwin)
			# Rien. On démarrera à la main.
			;;
		FreeBSD)
			cat > "$TMP/$$/init.mysql" <<TERMINE
#!/bin/sh
# PROVIDE: mysql
# REQUIRE: NETWORKING
. /etc/rc.subr
name=mysql
rcvar=\`set_rcvar\`
command=/usr/sbin/daemon
command_args="-u $compte $destmysql/bin/mysqld_safe --defaults-file=$bdd/my.cnf"
procname="*/mysqld"
pidfile=$bdd/my.pid
load_rc_config "\$name"
: \${mysql_enable="NO"}

run_rc_command "\$1"

if false ; then
case "\$1"
in	  
	*start)
		if ! checkyesno mysql_enable
		then
			echo -n "Cannot '${rc_arg}' $name. Set ${rcvar} to "
			echo -n "YES in /etc/rc.conf or use 'one${rc_arg}' "
			echo "instead of '${rc_arg}'."
			exit 1
		fi
		vraiecommande="\$1"
		[ \$vraiecommande = quietstart ] && vraiecommande=start || true
		checkyesno \${rcvar} && \$command "\$vraiecommande" \$command_args
		;;
	*)
		\$command "\$@" \$command_args
		;;
esac
fi
TERMINE
			sudo mkdir -p "$dest/etc/rc.d"
			sudo cp "$TMP/$$/init.mysql" "$dest/etc/rc.d/mysql"
			sudo chmod u+x "$dest/etc/rc.d/mysql"
			;;
	esac
}

if [ ! -d "$bdd" ]
then

echo "Création de la base…" >&2
creerBase

fi

echo "Auto-démarrage…" >&2
creerAmorceur

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
