#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=_nginx

# Historique des versions gérées

prerequis="nginx"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi [-u <compte>]
TERMINE
	exit 1
}

analyserParametres()
{
	vars=""
	compte=
	while [ $# -gt 0 ] ; do
		case "$1" in
			-u) shift ; compte="$1" ;;
			*)
				[ -z "$vars" ] && auSecours
				for i in $vars ; do
					export $i="$1"
					break
				done
				vars="`echo "$vars" | sed -e 's/[^ ]* //'`"
				;;
		esac
		shift
	done

	if [ -z "$compte" ] ; then
		comptesEnvisages="nginx web `id -un`"
		for compte in $comptesEnvisages personne ; do
			id "$compte" 2> /dev/null >&2 && break
		done
		if [ "$compte" = personne ] ; then
			echo "# Impossible de trouver un des comptes sous lequel tourner ($comptesEnvisages). Forcez un compte via -u <compte> (il sera créé si nécessaire)." >&2
			exit 1
		fi
	fi
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

version="`echo " $PREINCLUS" | sed -e 's/ *[^ ]*://g' -e 's/ //g'`"
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

if ! id "$compte" > /dev/null 2>&1 ; then
	echo "Création de l'utilisateur…" >&2
	creeCompte -s /bin/sh $compte
fi

echo "Auto-démarrage…" >&2
serveur -u "$compte" demon nginx -pre "extra_commands=\"reload\" ; umask 007" "$destnginx/sbin/nginx"

rm -Rf "$TMP/$$"
