#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=_phpfpm

# Historique des versions gérées

prerequis="php"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi [-s <suffixe démarreur>] [-p <port>] [<sélecteur de version>]
TERMINE
	exit 1
}

analyserParametres()
{
	vars="limitation"
	port=9000
	suffixe=
	while [ $# -gt 0 ]
	do
		case "$1" in
			-s) suffixe="$2" ; shift ;;
			-p) port="$2" ; shift ;;
			*)
				[ -z "$vars" ] && auSecours
				for i in $vars
				do
					eval $i="\"$1\""
					break
				done
				vars="`echo "$vars" | sed -e 's/[^ ]* //'`"
				;;
		esac
		shift
	done
	[ -z "$limitation" ] || prerequis="php $limitation"

	if [ -z "$compte" ]
	then
		comptesEnvisages="web www daemon"
		for compte in $comptesEnvisages personne
		do
			id "$compte" 2> /dev/null >&2 && break
		done
		if [ "$compte" = personne ]
		then
			echo "# Impossible de trouver un des comptes sous lequel tourner ($comptesEnvisages). Forcez un compte en le précisant en second paramètre (il sera créé si nécessaire)." >&2
			exit 1
		fi
	fi
}

filtrerConfs()
{
	for i in "$@"
	do
		filtrer "$i" sed -e "/^user *=/s#=.*#=$compte#" -e "/^listen *=/s#=.*#=127.0.0.1:$port#" -e "s#$destphp/etc/php-fpm.d#$dest/etc/php-fpm.d#g"
	done
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

version="`echo " $PREINCLUS" | sed -e 's/ *[^ ]*://g' -e 's/ //g'`"
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

echo "Auto-démarrage…" >&2
case `uname` in
	FreeBSD)
		conf="$dest/etc/php-fpm$suffixe.conf"
		
		mkdir "$TMP/$$/conf"
		cp "$destphp/etc/php-fpm.conf" "$TMP/$$/conf/php-fpm$suffixe.conf"
		[ ! -d "$destphp/etc/php-fpm.d" ] || cp -R "$destphp/etc/php-fpm.d" "$TMP/$$/conf/php-fpm$suffixe.d"
		filtrerConfs `find "$TMP/$$/conf" -type f`
		sudo mkdir -p "$dest/etc/"
		sudo cp -R "$TMP/$$/conf/"* "$dest/etc/"
		
		sudo mkdir -p "$dest/etc/rc.d"
		sed < "$destphp/etc/init.d.php-fpm" > "$TMP/$$/amorce" \
			-e "/^php_fpm_CONF *=/s#=.*#=$conf#"
		chmod a+x "$TMP/$$/amorce"
		sudo cp "$TMP/$$/amorce" "$dest/etc/rc.d/php-fpm$suffixe"
		;;
esac

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
