#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; [ -x "$SCRIPTS" -o ! -x "$0" ] || SCRIPTS="$0" ; case "`basename "$SCRIPTS"`" in *.*) true ;; *sh) SCRIPTS="$1" ;; esac ; case "$SCRIPTS" in /*) ;; *) SCRIPTS="`pwd`/$SCRIPTS" ;; esac ; delie() { while [ -h "$SCRIPTS" ] ; do SCRIPTS2="`readlink "$SCRIPTS"`" ; case "$SCRIPTS2" in /*) SCRIPTS="$SCRIPTS2" ;; *) SCRIPTS="`dirname "$SCRIPTS"`/$SCRIPTS2" ;; esac ; done ; } ; delie ; SCRIPTS="`dirname "$SCRIPTS"`" ; delie
. "$SCRIPTS/util.sh"

logiciel=_redis

# Historique des versions gérées

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi [-g] [-u <compte>]
  -g
    Générique. On ne se lie pas spécifiquement à la dernière version compilée du
    logiciel, mais on prendra celui trouvé à l'emplacement générique au moment
    du lancement:
      $INSTALLS
    Cela permettra (si le logiciel est compilé via les Petits Installeurs de
    Guillaume) de basculer vers une nouvelle version simplement en stoppant puis
    redémarrant le service.
TERMINE
	exit 1
}

analyserParametres()
{
	vars=""
	suffixe=
	generique=non
	while [ $# -gt 0 ]
	do
		case "$1" in
			-s) shift ; suffixe="$1" ;;
			-u) shift ; compte="$1" ;;
			-g) generique=oui ;;
			*) apAffecter "$1" $vars ;;
		esac
		shift
	done

	if [ -z "$compte" ]
	then
		comptesEnvisages="`id -u -n`"
		for compte in $comptesEnvisages personne
		do
			id "$compte" 2> /dev/null >&2 && break
		done
		if [ "$compte" = personne ]
		then
			echo "# Impossible de trouver un des comptes sous lequel tourner ($comptesEnvisages). Forcez un compte via l'option -u <compte> (il sera créé si nécessaire)." >&2
			exit 1
		fi
	fi
}

analyserParametres "$@"

prerequis="redis $argVersion"

prerequis

# Modifications

# Variables

eval "version=\"\$version_`echo "$logiciel" | cut -c 2-`\"" # On prend pour numéro de version installée celui de notre logiciel sous-jacent.
if [ $generique = oui ]
then
	install_dest="$INSTALLS/$logiciel$argOptions"
	destserviceredis="$INSTALLS"
else
	destserviceredis="$destredis"
fi
destiner

if ! id "$compte" > /dev/null 2>&1
then
	echo "Création de l'utilisateur…" >&2
	creeCompte $compte
fi

echo "Auto-démarrage…" >&2
# Constitution de l'arbo.
dest0="$TMP/$$/dest"
rm -Rf "$dest0"
mkdir -p "$dest0/etc" "$dest0/var/log" "$dest0/var/db"
cp "$destredis/etc/redis.default.conf" "$dest0/etc/redis$suffixe.conf"
cp "$destredis/etc/redis-sentinel.default.conf" "$dest0/etc/redis$suffixe-sentinel.conf"
changerconf "$dest0/etc/redis$suffixe.conf" -d ' ' maxclients=128 logfile="$dest/var/log/redis$suffixe.log" dbfilename="redis$suffixe.rdb" dir="$dest/var/db"
# Copie à l'emplacement définitif.
sinstaller -u $compte "$dest0" "$dest"
# Démarreurs!
serveur -u "$compte" simple "redis$suffixe" "$destserviceredis/bin/redis-server $dest/etc/redis$suffixe.conf"
serveur -u "$compte" -r redis$suffixe.sentinel simple "redis$suffixe-sentinel" "$destserviceredis/bin/redis-sentinel $dest/etc/redis$suffixe-sentinel.conf"

sutiliser
rm -Rf "$TMP/$$"
