#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

prerequis="rspamd"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi [<version rspamd>]
TERMINE
	exit 1
}

analyserParametres()
{
	vars="bdd"
	versionRspamd=
	compte=
	while [ $# -gt 0 ]
	do
		case "$1" in
			-u) shift ; compte="$1" ;;
			*) apAffecter "$1" $vars ;;
		esac
		shift
	done

	if [ -z "$compte" ]
	then
		comptesEnvisages="exim mail mel"
		for compte in $comptesEnvisages personne
		do
			id "$compte" 2> /dev/null >&2 && break
		done
		if [ "$compte" = personne ]
		then
			echo "# Impossible de trouver un des comptes sous lequel tourner ($comptesEnvisages). Forcez un compte via l'option -u (il sera créé si nécessaire)." >&2
			exit 1
		fi
	fi
	
	if [ -z "bdd" ]
	then
		bdd="$dest/var/db/rspamd"
	fi
	
	[ -z "$versionRspamd" -a ! -z "$argVersion" ] && versionRspamd="$argVersion" || true
	[ -z "$versionRspamd" ] || prerequis="`echo " $prerequis " | sed -e "s# rspamd # rspamd $versionRspamd #g"`"
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

eval "version=\"\$version_`echo "$logiciel" | cut -c 2-`\"" # On prend pour numéro de version installée celui de notre logiciel sous-jacent.
destiner

if ! id "$compte" > /dev/null 2>&1
then

echo "Création de l'utilisateur…" >&2
creeCompte -s /bin/sh $compte # 4100

fi

echo "Auto-démarrage…" >&2
t="$TMP/$$/dest"
mkdir -p "$t/etc" "$t/var/run" "$t/var/log"
if [ ! -d "$dest/etc/rspamd.0" ]
then
	cp -R "$destrspamd/etc/rspamd" "$t/etc/rspamd.0"
	mkdir -p "$t/etc/rspamd.0/local.d"
	echo "secure_ip = \"`localhost`\";" > "$t/etc/rspamd.0/local.d/worker-controller.inc"
fi
# Il faut lui préciser un SSL_CERT_FILE pour qu'il puisse télécharger ses listes régulièrement sur https://rspamd.com/.
serveur -d0 "$t" -d "$dest" -p "$dest/var/run/rspamd.pid" -u "$compte" demon rspamd \
	LD_LIBRARY_PATH="$INSTALLS/lib" \
	SSL_CERT_FILE="$INSTALLS/share/curl-ca-bundle.crt" \
	"$destrspamd/bin/rspamd LOGDIR=$dest/var/log CONFDIR=$dest/etc/rspamd.0 LOCAL_CONFDIR=$dest/etc/rspamd.0 DBDIR=$bdd -c $dest/etc/rspamd.0/rspamd.conf -u $compte -p $dest/var/run/rspamd.pid"
sudoku sh -c \
"
	mkdir -p \"$dest\"
	cp -R \"$t/.\" \"$dest/.\"
	mkdir -p \"$bdd\"
	chown -R $compte: \"$dest/var/run\" \"$dest/var/log\" \"$bdd\"
"

sutiliser -
