#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=_svn

# Historique des versions gérées

prerequis="subversion"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi [-u <compte>] [-s <suffixe démarreur>] [-p <port>] <silo> <options svnserve>...
TERMINE
	exit 1
}

analyserParametres()
{
	vars="silo reste"
	suffixe=
	port=3690
	reste=
	while [ $# -gt 0 ]
	do
		case "$1" in
			-s) suffixe="$2" ; shift ;;
			-p) port="$2" ; shift ;;
			-u) shift ; compte="$1" ;;
			*)
				if [ "x$vars" = xreste ]
				then
					reste="$reste $1"
				else
					apAffecter "$1" $vars
				fi
				;;
		esac
		shift
	done

	if [ -z "$compte" ]
	then
		compte="`id -un`"
	fi
	
	[ ! -z "$silo" ] || auSecours
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

eval "version=\"\$version_`echo "$logiciel" | cut -c 2-`\"" # On prend pour numéro de version installée celui de notre logiciel sous-jacent.
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

if ! id "$compte" > /dev/null 2>&1
then

echo "Création de l'utilisateur…" >&2
creeCompte -s /bin/sh $compte # 4100

fi

if [ ! -d "$silo" ]
then

echo "Création du silo…" >&2

sudo -u "$compte" svnadmin init "$silo"

fi

echo "Auto-démarrage…" >&2
sudo serveur demon -u "$compte" svn$suffixe "$destsubversion/bin/svnserve -M 512 -c 0 -r $silo -d -T $reste"

rm -Rf "$TMP/$$"
