#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=_syncthingdisco

# Historique des versions gérées

prerequis="syncthing"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi [-u <utilisateur>] [-http]
TERMINE
	exit 1
}

analyserParametres()
{
	vars="rien"
	compte=
	https=oui
	while [ $# -gt 0 ]
	do
		case "$1" in
			-u) shift ; compte="$1" ;;
			-http|--http) https=non ;;
			*)
				[ -z "$vars" ] && auSecours
				for i in $vars
				do
					eval $i="$1"
					break
				done
				vars="`echo "$vars" | sed -e 's/[^ ]* //'`"
				;;
		esac
		shift
	done

	if [ -z "$compte" ]
	then
		comptesEnvisages="nuage cloud `id -u -n`"
		for compte in $comptesEnvisages personne
		do
			id "$compte" 2> /dev/null >&2 && break
		done
		if [ "$compte" = personne ]
		then
			echo "# Impossible de trouver un des comptes sous lequel tourner ($comptesEnvisages). Forcez un compte via l'option -u (il sera créé si nécessaire)." >&2
			exit 1
		fi
	fi
	
	[ ! -z "$compte" ] || auSecours
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

version="`echo " $PREINCLUS" | sed -e 's/ *[^ ]*://g' -e 's/ //g'`"
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

creerAmorceur()
{
	if [ $https = oui ]
	then
		args="-cert $dest/$dcert/cert.pem -key $dest/$dcert/key.pem"
	else
		args="-http"
	fi
	case `uname` in
		Darwin)
			# Rien. On démarrera à la main.
			;;
		FreeBSD)
			dcert=var/cert/stdiscosrv
			mkdir -p "$TMP/$$/init/etc/rc.d" "$TMP/$$/init/var/run"
			[ $https = non ] || mkdir -p "$TMP/$$/init/$dcert"
			cat > "$TMP/$$/init/etc/rc.d/syncthingdisco" <<TERMINE
#!/bin/sh
# PROVIDE: syncthingdisco
# REQUIRE: NETWORKING
. /etc/rc.subr
name=syncthingdisco
rcvar=\`set_rcvar\`
pidfile=$dest/var/run/syncthingdisco.pid
command=/usr/sbin/daemon
# Bizarre, la doc de daemon dit qu'il faut utiliser -P pour tuer le démon plutôt que le fils (sinon le démon redémarre le fils), mais en pratique ce faisant le stop ne trouve pas le pid. Et comme apparemment le démon ne relance pas le fils, partons sur du -p.
command_args="-u $compte -p \$pidfile $destsyncthing/bin/stdiscosrv $args"
procname="*/stdiscosrv"
load_rc_config "\$name"
: \${syncthingdisco_enable="NO"}

run_rc_command "\$1"

if false ; then
case "\$1"
in	  
	*start)
		if ! checkyesno syncthingdisco_enable
		then
			echo -n "Cannot '${rc_arg}' $name. Set ${rcvar} to "
			echo -n "YES in /etc/rc.conf or use 'one${rc_arg}' "
			echo "instead of '${rc_arg}'."
			exit 1
		fi
		vraiecommande="\$1"
		[ \$vraiecommande = quietstart ] && vraiecommande=start || true
		checkyesno \${rcvar} && \$command "\$vraiecommande" \$command_args
		;;
	*)
		\$command "\$@" \$command_args
		;;
esac
fi
TERMINE
			chmod a+x "$TMP/$$/init/etc/rc.d/syncthingdisco"
			sudo cp -R "$TMP/$$/init/." "$dest"
			destcert="$dest/$dcert"
			[ $https = oui ] || destcert=
			sudo chown "$compte:" "$dest/var/run" $destdcert
			;;
	esac
}

echo "Auto-démarrage…" >&2
creerAmorceur

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
