#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=_tinyproxy

# Historique des versions gérées

prerequis="tinyproxy"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi [-u <utilisateur>] -p <port> <règle>*
  -u <utilisateur>
    Compte sous lequel tourner.
  -p <port>
    Numéro de port d'écoute.
  <règle>
    Si -, l'entrée standard est récupérée.
    Les règles sont celles de tinyproxy: upstream, no upstream, Allow, Filter,
	etc.
    Attention, les chaînes de caractères doivent être entourées de guillemets.
TERMINE
	exit 1
}

analyserParametres()
{
	vars="rien"
	compte=
	port=
	> $TMP/$$/regles
	while [ $# -gt 0 ]
	do
		case "$1" in
			-u) shift ; compte="$1" ;;
			-p) shift ; port="$1" ;;
			-) cat >> $TMP/$$/regles ;;
			*)
				if [ "$vars" = rien ]
				then
					echo "$1" >> $TMP/$$/regles
					shift
					continue
				fi
				[ -z "$vars" ] && auSecours
				for i in $vars
				do
					eval $i="$1"
					break
				done
				vars="`echo "$vars" | sed -e 's/[^ ]* //'`"
				;;
		esac
		shift
	done

	if [ -z "$compte" ]
	then
		comptesEnvisages="web www daemon `id -u -n`"
		for compte in $comptesEnvisages personne
		do
			id "$compte" 2> /dev/null >&2 && break
		done
		if [ "$compte" = personne ]
		then
			echo "# Impossible de trouver un des comptes sous lequel tourner ($comptesEnvisages). Forcez un compte via l'option -u (il sera créé si nécessaire)." >&2
			exit 1
		fi
	fi
	
	[ ! -z "$compte" ] || auSecours
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

version="`echo " $PREINCLUS" | sed -e 's/ *[^ ]*://g' -e 's/ //g'`"
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

creerAmorceur()
{
	case `uname` in
		Darwin)
			# Rien. On démarrera à la main.
			;;
		FreeBSD)
			mkdir -p "$TMP/$$/init/etc/rc.d" "$TMP/$$/init/var/run" "$TMP/$$/init/var/log"
			fpid="var/run/tinyproxy.pid"
			ftrace="var/log/tinyproxy.log"
			fconfig="etc/tproxy.conf"
			groupe="`id -g -n "$compte"`"
			
			serveur -d0 "$TMP/$$/init" -d "$dest" -p "$dest/$fpid" demon tinyproxy "$desttinyproxy/sbin/tinyproxy -c $dest/$fconfig"
			cat > "$TMP/$$/init/$fconfig" <<TERMINE
User $compte
Group $groupe
PidFile "$dest/$fpid"
LogFile "$dest/$ftrace"
TERMINE
			# On ajoute aussi les valeurs par défaut de tous les paramètres qui n'auront pas été définis par l'appelant.
			cat $TMP/$$/regles >> "$TMP/$$/init/$fconfig"
			(
				cat <<TERMINE
Port $port
StartServers 3
MinSpareServers 3
MaxSpareServers 3
MaxClients 100
TERMINE
			) | while read param contenu
			do
				grep -q "^$param[ 	]" < "$TMP/$$/init/$fconfig" || echo "$param $contenu"
			done >> "$TMP/$$/init/$fconfig"
			
			sudo cp -R "$TMP/$$/init/." "$dest"
			sudo chown "$compte:" "$dest/var/run" "$dest/var/log"
			;;
	esac
}

echo "Auto-démarrage…" >&2
creerAmorceur

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
