#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

prerequis="tinyproxy"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi [-u <utilisateur>] -p <port> [-r <remplace>] <règle>*
  -u <utilisateur>
    Compte sous lequel tourner.
  -p <port>
    Numéro de port d'écoute.
  -r <remplace>
    Remplace un autre serveur (en plus de lui-même s'il se trouve)
  <règle>
    Si -, l'entrée standard est récupérée.
    Les règles sont celles de tinyproxy: upstream, no upstream, Allow, Filter,
	etc.
    Attention, les chaînes de caractères doivent être entourées de guillemets.
TERMINE
	exit 1
}

analyserParametres()
{
	vars="rien"
	compte=
	port=
	seulement=
	optionsServeur=
	> $TMP/$$/regles
	while [ $# -gt 0 ]
	do
		case "$1" in
			--seulement) shift ; seulement="$1" ;;
			-u) shift ; compte="$1" ;;
			-p) shift ; port="$1" ;;
			-r) optionsServeur="$optionsServeur $1 $2" ; shift ;;
			-) cat >> $TMP/$$/regles ;;
			*)
				if [ "$vars" = rien ]
				then
					echo "$1" >> $TMP/$$/regles
				else
					 apAffecter "$1" $vars
				fi
				;;
		esac
		shift
	done

	if [ -z "$compte" ]
	then
		comptesEnvisages="web www daemon `id -u -n`"
		for compte in $comptesEnvisages personne
		do
			id "$compte" 2> /dev/null >&2 && break
		done
		if [ "$compte" = personne ]
		then
			echo "# Impossible de trouver un des comptes sous lequel tourner ($comptesEnvisages). Forcez un compte via l'option -u (il sera créé si nécessaire)." >&2
			exit 1
		fi
	fi
	
	[ ! -z "$compte" ] || auSecours
	
	[ -n "$port" ] || auSecours
	
	remplacerPrerequis "tinyproxy $argVersion"
}

analyserParametres "$@"

prerequis

# Modifications

# Variables

eval "version=\"\$version_`echo "$logiciel" | cut -c 2-`\"" # On prend pour numéro de version installée celui de notre logiciel sous-jacent.

destiner

creerAmorceur()
{
	local desttemp="$TMP/$$/init"
	
			mkdir -p "$TMP/$$/init/etc/rc.d" "$TMP/$$/init/var/run" "$TMP/$$/init/var/log"
			fpid="var/run/tinyproxy.pid"
			ftrace="var/log/tinyproxy.log"
			fconfig="etc/tproxy.conf"
			foui="etc/tproxy.oui"
			groupe="`id -g -n "$compte"`"
			
			cat > "$TMP/$$/init/$fconfig" <<TERMINE
User $compte
Group $groupe
PidFile "$dest/$fpid"
LogFile "$dest/$ftrace"
TERMINE
			# On ajoute aussi les valeurs par défaut de tous les paramètres qui n'auront pas été définis par l'appelant.
			cat $TMP/$$/regles >> "$TMP/$$/init/$fconfig"
			(
				if [ ! -z "$seulement" ]
				then
					echo "FilterDefaultDeny Yes"
					echo "Filter \"$dest/foui\""
					echo "$seulement" > "$TMP/$$/init/$foui"
				fi
				cat <<TERMINE
Port $port
StartServers 3
MinSpareServers 3
MaxSpareServers 3
MaxClients 100
TERMINE
			) | while read param contenu
			do
				grep -q "^$param[ 	]" < "$TMP/$$/init/$fconfig" || echo "$param $contenu"
			done >> "$TMP/$$/init/$fconfig"
			
	serveur_patronVars "$desttemp" var/run var/log
	mv "$desttemp/$fconfig" "$desttemp/$fconfig$PERSO_ORIGINAL"
	iperso "$desttemp"
	
			sudo cp -R "$TMP/$$/init/." "$dest"
	serveur_chownVars
	
	local bin=bin
	pge $version 1.10 || bin=sbin
	serveur -p "$dest/$fpid" $optionsServeur demon tinyproxy "$desttinyproxy/$bin/tinyproxy -c $dest/$fconfig"
}

echo "Auto-démarrage…" >&2
creerAmorceur

sutiliser -
