#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

[ "x$1" = x-d ] && shift && dest="$1" && shift

[ -z "$dest" ] && echo "Merci de préciser la destination via -d <destination>" >&2 && exit 1

v 2.0.0 && modifs="vueSemaine" || true
v 2.6.0 || true

archive="http://github.com/adobo/agendav/tarball/$version" # Ne contient pas les .css agglomérés.
archive="https://github.com/agendav/agendav/releases/download/$version/agendav-$version.tar.gz"

echo "$dest" | grep -q '^/' || dest="`pwd`/$dest"
[ -d "$dest" ] && echo "# Le dossier $dest existe déjà. Merci de le déplacer pour procéder à une installation propre." >&2 && exit 1

obtenirEtAllerDansVersion agendav-$version.tar.gz

mkdir -p "$dest"

local=http://sync.gclo.fr/cal.php/calendars # Avec un 127.0.0.1 sync.gclo.fr dans /etc/hosts
public=http://sync.gclo.fr/cal.php/calendars

mkdir -p "web/var"
touch "web/var/agendav.sqlite"
# À FAIRE: chown / chmod.
cat > web/config/settings.php <<TERMINE
<?php

\$app['site.title'] = 'Agenda de famille';
\$app['caldav.baseurl'] = '$local/';
\$app['caldav.authmethod'] = 'digest';
\$app['defaults.date_format'] = 'dmy';
\$app['defaults.weekstart'] = 1;
\$app['defaults.timezone'] = 'Europe/Paris';
\$app['defaults.language'] = 'fr_FR';
\$app['db.options'] =
[
	'driver' => 'pdo_sqlite',
	'path' => '$dest/web/var/agendav.sqlite',
];

?>
TERMINE

vueSemaine()
{
	# https://github.com/mtudury/agendav/pull/1
	filtrer web/src/DateHelper.php sed -e 's/THis/TH:i:s/g' -e '/T000000/{s//T00:00:00/;s/^/if(strlen($input) == 10) /'
}

set -x
chmod a+x agendavcli
filtrer agendavcli sed -e 's#/usr/bin/php#/usr/bin/env php#'
for modif in true $modifs ; do $modif ; done

tar cf - . | ( cd "$dest" && tar xf - )

cd "$dest"
( cd web && SSL_CERT_FILE=/usr/local/share/curl-ca-bundle.crt composer update )
echo y | ./agendavcli migrations:migrate

echo "# Pensez à configurer le serveur web pour qu'il pointe sur $dest/web/public" >&2
