#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

rempl=non
test=non
[ "x$1" = x-r ] && rempl=oui && shift
[ "x$1" = x-t ] && test=oui && rempl=oui && shift

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

logiciel=apache

# Historique des versions gérées

v 2.0.54 #&& modifs=confDeveloppement
v 2.1.7-beta && prerequis="apr-util >= 1.2.1" || true # Qui sait utiliser APR 1.2.1, qui n'a pas http://issues.apache.org/bugzilla/show_bug.cgi?id=34332
v 2.1.9-beta # Il faut suivre, car les beta disparaissent des serveurs au fur et à mesure.
v 2.2.3
v 2.2.8
v 2.2.11 && modifs="proxy"
v 2.2.15
v 2.2.21
v 2.2.23 && prerequis="apr-util >= 1.5" || true
v 2.4.10 && modifs="proxy dAbordInclusionsLocales modules24" || true

prerequis

# Modifs

confDeveloppement()
{
	find . -name configure | while read fichier
	do
		filtrer "$fichier" sed -e 's/ *-O2 */ /'
	done
	OPTIONS_CONF="$OPTIONS_CONF --enable-maintainer-mode"
}

proxy()
{
	OPTIONS_CONF="$OPTIONS_CONF --enable-proxy --enable-proxy-http"
}

modules24()
{
	# La 2.4 est vachement plus modulaire, et demande d'activer explicitement certains modules autrefois standard.
	OPTIONS_CONF="$OPTIONS_CONF --enable-headers --enable-rewrite"
}

dAbordInclusionsLocales()
{
	# Par défaut, en 2.4.10 en tout cas, la compil se fait en $CFLAGS $ALL_INCLUDES, ce dernier comprenant les includes "locaux" au répertoire de compil. Du coup, si dans CFLAGS on a /usr/local/include dans lequel on a un autre Apache, ce dernier verra ses .h utilisé au lieu de ceux de l'Apache en train de compiler.
	for i in ./build/rules.mk.in ./server/Makefile.in
	do
		filtrer "$i" sed -e 's#$(ALL_CPPFLAGS) $(ALL_INCLUDES)#$(ALL_INCLUDES) $(ALL_CPPFLAGS)#g' -e 's#\($(MOD_INCLUDES)\) \(.*$(EXTRA_INCLUDES)\)#\2 \1#g' # On fait passer ALL_CPPFLAGS (notre /usr/local) derrière ALL_INCLUDES (dans lequel il concatène les chemins de tous les modules compilés en ce moment); et on vire MOD_INCLUDES, qui vaut le --prefix, qui servira sans doute pour les modules qui seront compilés après coup, sauf que pour le moment on ne veut pas qu'il aille soit placé devant.
	done
	# De plus certaines de nos variables globales sont redondantes (reprennent le contenu de CPPFLAGS).
	CFLAGS=
	CXXFLAGS=
	export CFLAGS CXXFLAGS
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive=http://apache.crihan.fr/dist/httpd/httpd-$version.tar.bz2

[ -d "$dest" -a $rempl = non ] && exit 0

obtenirEtAllerDans "$archive"

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --enable-layout=Apache --prefix="$dest" $OPTIONS_CONF --enable-ssl --enable-rewrite --enable-so --enable-http --enable-dav --enable-auth-digest

echo Compilation… >&2
make

echo Installation… >&2
[ ! -d "$dest" ] || ( [ ! -d "$dest.remplace" ] && sudo mv "$dest" "$dest.remplace" || true )
sudo make install
if [ $test = oui ]
then
	[ -d "$dest.nouveau" ] || ( sudo mv "$dest" "$dest.nouveau" && sudo mv "$dest.remplace" "$dest" )
else
sutiliser "$logiciel-$version"
fi

rm -Rf $TMP/$$

echo "# Pensez à modifier le MIME des .js en text/javascript, sans quoi Drosera refuse de les déboguer." >&2
echo "# User et Group seraient aussi à modifier." >&2
