#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

rempl=non
test=non
[ "x$1" = x-r ] && rempl=oui && shift
[ "x$1" = x-t ] && test=oui && rempl=oui && shift

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

logiciel=apache

# Historique des versions gérées

version=2.0.54
#modifs=confDeveloppement

version=2.1.7-beta # Qui sait utiliser APR 1.2.1, qui n'a pas http://issues.apache.org/bugzilla/show_bug.cgi?id=34332
modifs=aprUtil

version=2.1.9-beta # Il faut suivre, car les beta disparaissent des serveurs au fur et à mesure.

version=2.2.3

version=2.2.8

version=2.2.11
modifs="aprUtil proxy"

version=2.2.15
modifs="aprUtil proxy"

version=2.2.16

# Modifs

confDeveloppement()
{
	find . -name configure | while read fichier
	do
		filtrer "$fichier" sed -e 's/ *-O2 */ /'
	done
	OPTIONS_CONF="$OPTIONS_CONF --enable-maintainer-mode"
}

aprUtil()
{
	inclure apr-util
}

proxy()
{
	OPTIONS_CONF="$OPTIONS_CONF --enable-proxy --enable-proxy-http"
}

# Variables

dest="/usr/local/$logiciel-$version"
archive=http://apache.crihan.fr/dist/httpd/httpd-$version.tar.bz2

[ -d "$dest" -a $rempl = non ] && exit 0

obtenirEtAllerDans "$archive"

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --enable-layout=Apache --prefix="$dest" $OPTIONS_CONF --enable-ssl --enable-rewrite --enable-so --enable-http --enable-dav --enable-auth-digest

echo Compilation… >&2
make

echo Installation… >&2
[ ! -d "$dest" ] || ( [ ! -d "$dest.remplace" ] && sudo mv "$dest" "$dest.remplace" || true )
sudo make install
if [ $test = oui ]
then
	[ -d "$dest.nouveau" ] || ( sudo mv "$dest" "$dest.nouveau" && sudo mv "$dest.remplace" "$dest" )
else
sutiliser "$logiciel-$version"
fi

rm -Rf /tmp/$$

echo "# Pensez à modifier le MIME des .js en text/javascript, sans quoi Drosera refuse de les déboguer." >&2
echo "# User et Group seraient aussi à modifier." >&2
