#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

analyserParametresPour --pour php "$@"

case `php-config --version | cut -d . -f 1-2` in
	[1-9][0-9].*) argVersion="$argVersion >= 5" ;;
	[45]*) argVersion="$argVersion < 4" ;;
esac

logiciel=apc

v 3.1.9 && modifs="lock" && prerequis="$prerequis autoconf" || true
v 3.1.13 && modifs= || true
v 3.1.13 && modifs= || true
#v 3.1.14 && modifs= || true # Retirée de la "vente" par Rasmus, pour une question de fuite mémoire.
v 5.1.12 || true

archive="http://pecl.php.net/get/APC-$version.tgz"
pge 4 $version || archive="https://pecl.php.net/get/apcu-$version.tgz"

lock()
{
	# https://bugs.php.net/bug.php?id=59750
	# http://news.php.net/php.pecl.cvs/15669
	filtrer apc_lock.h sed -e '/define apc_lck_rdunlock/s/&//'
}

destiner ":$destphp"

prerequis

obtenirEtAllerDansVersion

cd `find . -name APC\*-$version -o -name apc\*-$version`

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
phpize
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
apcso="`cd modules && find . -name \*apc\*.so\* | tail -1`" # Entre les apc.so et les libapc.so.0.0, youpi.
apcso="`basename "$apcso"`"
ini="`php -i | sed -e '/^Loaded Configura/!d' -e 's/.* => //'`"
sufiltrer "$ini" sed -e '${
a\
extension = '"$apcso"'
a\
apc.enabled = 1
}' -e '/extension = .*apc.*\.so/d' -e '/apc.enabled/d'

sutiliser -

rm -Rf "$TMP/$$"
