#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"
. "$SCRIPTS/util.php.sh"

analyserParametresPour --pour php "$@"

v_zoc=
case `php-config --version | cut -d . -f 1-2` in
	[1-9][0-9].*) argVersion="$argVersion >= 5" ;;
	5.[56]) argVersion="$argVersion >= 4 < 5" ;;
	5.4) argVersion="$argVersion >= 4 < 5" ; v_zoc=7.0.5 ;; # APC avec la 5.4 pose pas mal de prob; on bascule vers APCu + Zend OpCache (premières versions, alors non intégrées au cœur de PHP).
	[45]*) argVersion="$argVersion < 4" ;;
esac

v 3.1.9 && modifs="lock" && prerequis="$prerequis autoconf" || true
v 3.1.13 && modifs= || true
v 3.1.13 && modifs= || true
#v 3.1.14 && modifs= || true # Retirée de la "vente" par Rasmus, pour une question de fuite mémoire.
v 4.0.11 || true
v 5.1.12 || true
v 5.1.14 || true
v 5.1.17 || true

archive="http://pecl.php.net/get/APC-$version.tgz"
pge 4 $version || archive="https://pecl.php.net/get/apcu-$version.tgz"
# Subtile modification si nous sommes appelés pour la sous-partie Zend OpCache.
case "$GUILI_MOIRE:" in *:zoc:*)
	archive="https://pecl.php.net/get/zendopcache-$v_zoc.tgz"
	modifs="$modifs_zoc"
;; esac

lock()
{
	# https://bugs.php.net/bug.php?id=59750
	# http://news.php.net/php.pecl.cvs/15669
	filtrer apc_lock.h sed -e '/define apc_lck_rdunlock/s/&//'
}

destiner ":$destphp"

prerequis

obtenirEtAllerDansVersion

cd `find . -maxdepth 1 -name APC\*-$version -o -name apc\*-$version -o -name zendopcache-$v_zoc`

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
phpize
./configure --prefix="$dest"

echo Compilation… >&2
make
[ -z "$v_zoc" ] || moire -i zoc "$@"

echo Installation… >&2
sudo make install

case "$GUILI_MOIRE:" in
	:) php_iext apc apc.enabled ;;
	*:zoc:*) php_iext -z opcache opcache.enable ;;
esac

sutiliser -
