#!/bin/bash
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

if [ "$SCRIPTS" = "" ] ; then SCRIPTS=`command -v "$0"` ; SCRIPTS=`dirname "$SCRIPTS"` ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS" ; fi
. "$SCRIPTS/util.sh"

logiciel=bash-completion
version=20041017
dest=/usr/local/$logiciel-$version

[ -d "$dest" ] && exit 0

cd /tmp
echo Obtention et décompression… >&2
tar xzf `obtenir "http://www.caliban.org/files/bash/$logiciel-$version.tar.gz"`

cd /tmp/bash_completion

echo Configuration… >&2
filtrer bash_completion sed -e 's=/etc/bash_completion=/usr/local/etc/bash_completion=g'

echo Installation… >&2
sudo sh -c "mkdir -p $dest/etc && ln -s /usr/local/etc/bash_completion.d $dest/etc/ && cp /tmp/bash_completion/bash_completion $dest/etc/"

sudo mkdir /usr/local/etc/bash_completion.d
sutiliser $logiciel-$version
