#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

case `uname` in
	Darwin) exit 0 ;; # Sous Mac OS X, le strip de binutils explose tous les exécutables. Sans doute n'est-il adapté qu'à l'ELF.
esac

# Historique des versions gérées

# Une GNUmakerie avec un $(SED) -e s/NN/32/g < $< > $@ qui laisse apparemment bsdmake sans voix ($< rendu comme vide).
prerequis="make \\"
v 2.24 && modifs="sbrk" || true
v 2.27 || true
v 2.28.1 || true
v 2.30 || true
v 2.31.1 && modifs="$modifs max0" || true
v 2.34 && modifs="$modifs sansdoc" || true
v 2.36.1 && modifs="$modifs iostr" || true # max0 encore utile?
v 2.37 && retirerModif max0 || true
v 2.41 && retirerModif sansdoc || true

prerequis

# Modifications

iostr()
{
	# http://patches-tcwg.linaro.org/patch/45493/
	for f in binutils/objcopy.c
	do
		filtrer "$f" sed -e 's#[a-z]*->iostream#(FILE *)&#g'
	done
}

sansdoc()
{
	# Il nous réclame makeinfo et on n'a pas que ça à faire.
	#filtrer binutils/doc/Makefile.in sed -e '/^info:/s/ info-am//'
	filtrer binutils/doc/Makefile.in sed -e '/^INFO_DEPS *=/s/ binutils.info//'
}

max0()
{
	# https://bugzilla.redhat.com/show_bug.cgi?id=1599521
	# https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237068
	# Rencontrée par exemple en compilant hummus sur une FreeBSD 11.2: la libaesgm générée donne lieu à un "libaesgm.so: _end: invalid version 21 (max 0)".
	# À voir aussi https://sourceware.org/git/?p=binutils-gdb.git;a=patch;h=7a815dd566f3dd32435ac73aa0a0cc948d525e06 pour comment détecter les biblios qui ont été générées par ce ld pourri.
	
	patch -p1 < "`obtenir https://src.fedoraproject.org/rpms/binutils/raw/57a0cd302817a0fff7d529dc8aa7282eef480fad/f/binutils-do-not-provide-shared-section-symbols.patch`"
}

sbrk()
{
	# https://sourceware.org/bugzilla/show_bug.cgi?id=16644
	case `uname` in
		Darwin) OPTIONS_CONF="$OPTIONS_CONF --disable-werror" ;;
	esac
}

# Variables

archive="http://ftp.gnu.org/gnu/binutils/binutils-$version.tar.bz2"

destiner

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
