#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 1.0.6 && modifs="fpic meilleurCompilo dyna" || true
v 1.0.7 || true
v 1.0.8 || true

dyna()
{
	filtrer Makefile awk '
/^all: /{ print $0" libbz2.so"; next; }
/^libbz2\.a:/{ print "libbz2.so: $(OBJS)"; print "\t$(CC) -shared -fPIC -o $@ $(OBJS)" ; print ""; }
{ print; }
/^install:/{ install = 1; }
install&&/^$/{ install = 0; }
install&&/libbz2\.a/{ gsub(/libbz2\.a/, "libbz2.so"); print; }
'
}

archive="https://netix.dl.sourceforge.net/project/bzip2/bzip2-$version.tar.gz"
archive="https://sourceware.org/pub/bzip2/bzip2-$version.tar.gz"

destiner

prerequis

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif "$@" ; done

echo Configuration… >&2
filtrer Makefile sed \
	-e "s#^PREFIX=.*#PREFIX=$dest#" \
	-e "s#^CFLAGS=#CFLAGS=$CFLAGS #" \
	-e "s#^CC=.*#CC=$CC#" \

echo Compilation… >&2
make
for modif in true $modifspostcompil ; do $modif "$@" ; done

echo Installation… >&2
sudo make install

sutiliser
