#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=cabal

# Historique des versions gérées

v 1.22.3.0 && modifs="detectionALaConDeLd" || true
v 1.22.5.0 || true
v 1.22.8.0 || true
v 1.24.0.0 || true

prerequis

# Modifications

detectionALaConDeLd()
{
	# Cet abruti, pour détecter si le lieur est collect2 ou ld, essaie de le faire tourner en mode verbeux, puis traite la sortie en supprimant "tout ce qu'il y a après le nom du programme" (idée: transformer un /usr/bin/ld --machin --truc en /usr/bin/ld). Sauf que notre ld sous FreeBSD sort un /usr/bin/ld --machin -L/libexec/ld-elf.so", ce qui lui fait détecter un exécutable au doux nom de '/usr/bin/ld --machin -L/libexec/ld'.
	filtrer bootstrap.sh sed -e '/sed.*link/s#link\\)#link\\)[\\" ]#'

}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="https://www.haskell.org/cabal/release/cabal-install-$version/cabal-install-$version.tar.gz"

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./bootstrap.sh --no-doc
exit 0

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
