#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; }
calcScripts() { absolutiseScripts "`command -v "$1"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`" ; }
calcScripts "$0"
. "$SCRIPTS/util.sh"

logiciel=carddavmate

v 0.11.1 && modifs="config adaptations" || true
v 0.12.0 && modifs="config adaptations0012" || true
v 0.13.1 && modifs="config adaptations0013" || true

archive=http://www.inf-it.com/CardDavMATE_$version.zip

config()
{
	filtrer config.js jspropre -l
	filtrer config.js sed -E \
		-e "s/'us'/'fr'/g" \
		-e 's/en_US/fr_FR/g' \
		-e '/^var globalCollectionSort=/i\
var globalCollectionSort=["first","last"];
' \
		-e '/^var globalCollectionSort=/,/^\]/d' \
		-e '/^var globalCollectionDisplay=/i\
var globalCollectionDisplay=["first"," last"];
' \
		-e '/^var globalCollectionDisplay=/,/^\]/d' \
		-e '/^var globalContactStoreFN=/i\
var globalContactStoreFN=["prefix"," first"," last"];
' \
		-e '/^var globalContactStoreFN=/,/^\]/d' \
		-e '/^var globalCollectionDisplayOrg=/c\
var globalCollectionDisplayOrg=false;
' \
		-e 's#^[/]*var globalUseJqueryAuth.*#var globalUseJqueryAuth=true;#' \
		-e '/^var globalNetworkCheckSettings=/,/^}/{
/^{/a\
	href: "http://gclo.fr/sync/card.php/addressbooks/",
/^{/a\
	crossDomain: true,
/^{/a\
	ignoreAlarms: false,
/^{/a\
	backgroundCalendars: [],
/^[ 	](href|crossDomain|ignoreAlarms|backgroundCalendars):/d
}'
	local colonnes="
[
	{ label: '{Name}', value: ['{FirstName}', ' {LastName}'] },
	{ label: '{Email}', value: ['{Email[:0]}'] },
	{ label: '{Phone} 1', value: ['{Phone[:0]}'] },
	{ label: '{NoteText}', value: ['{NoteText}'] }
];
"
	local zz3="`echo | tr '\012' '\003'`"
	colonnes="`echo "$colonnes" | tr '\012' '\003' | sed -e "s#$zz3#\\\\\\n#g"`"
	filtrer config.js awk "
BEGIN{
	globalCollectionDisplay=0;
}
!globalCollectionDisplay&&/var globalCollectionDisplay/{
	globalCollectionDisplay = 1;
	print \"var globalCollectionDisplay=\";
	print \"$colonnes\";
}
{print}
"
}

adaptations()
{
	for i in carddavmate-0.11.1.maidenname.patch carddavmate-0.11.1.presentation.patch carddavmate-0.11.1.rechargementintempestif.patch
	do
		patch -p0 < "$SCRIPTS/$i"
	done
}

adaptations0012()
{
	for i in carddavmate-0.12.0.maidenname.patch carddavmate-0.12.0.presentation.patch
	do
		patch -p0 < "$SCRIPTS/$i"
	done
}

adaptations0013()
{
	for i in carddavmate-0.13.1.maidenname.patch carddavmate-0.12.0.presentation.patch
	do
		patch -p0 < "$SCRIPTS/$i"
	done
}

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi <répertoire destination>
TERMINE
	exit 1
}

analyserParametres()
{
	vars="dest"
	while [ $# -gt 0 ]
	do
		case "$1" in
			*)
				[ -z "$vars" ] && auSecours
				for i in $vars
				do
					eval $i="$1"
					break
				done
				vars="`echo "$vars" | sed -e 's/[^ ]* //'`"
				;;
		esac
		shift
	done
}

analyserParametres "$@"

[ -z "$dest" ] && auSecours
echo "$dest" | grep -q ^/ || dest="`pwd`/$dest"

echo Obtention… >&2
( obtenirEtAllerDansVersion > /dev/null && tar cf - . ) | ( mkdir -p "$dest" && cd "$dest" && tar xf - )

cd "$dest"

# Récupération des dépendances.

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

if [ -e cache_update.sh ]
then
	./cache_update.sh
fi

rm -Rf $TMP/$$
