#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 20130621 && versionComplete="$version.4f62f2a90ecbea0d6d14e4bc0902056996144023.git" && prerequis="cmake \\ " && modifs="pthr wcstoll" || true
v 20130812 && versionComplete="$version.e8e3d20f20da5ee3e37d347207b01890829a5475.git" && modifs="pthr wcstoll wcscpp champsdebits contribs" || true

# Modifications

champsdebits()
{
	find src \( -name "*.cpp" -o -name "*.h" \) -print0 | xargs -0 egrep -l 'jj_la1_0|jjbitVec2' | while read f
	do
		filtrer "$f" sed \
			-e '/jj_la1_0/s/ int32_t/ uint32_t/g' \
			-e '/jjbitVec[02].*=.*{/{
:-|
s/}/}/
t-)
N
b-|
:-)
}' \
			-e '/jjbitVec[02]/s/ int64_t/ uint64_t/g' \
			-e '/jjbitVec[02]/s/_ILONGLONG(\([^)]*\))/\1ULL/g'
	done
}

contribs()
{
	# https://build.opensuse.org/package/view_file/windows:mingw:win32/mingw32-clucene/clucene-2.3.3.4-contrib-libs.patch?expand=1
	patch -p1 -l < "$SCRIPTS/clucene.contribs.patch"
	optionsConf="$optionsConf -DBUILD_CONTRIBS_LIB=ON"
}

pthr()
{
	filtrer src/shared/CLucene/LuceneThreads.h sed -e '/define *_LuceneThreads_h/a\
#include <pthread.h>
'
}

wcstoll()
{
	# http://sourceforge.net/p/clucene/bugs/208/
	export CXXFLAGS=-D__LONG_LONG_SUPPORTED
}

wcscpp()
{
	# clang trouve une ambiguïté entre le wcsstr C et celui CPP (sachant que le second est un simple appel au premier).
	for i in src/shared/CLucene/util/Misc.cpp src/core/CLucene/search/FieldCacheImpl.cpp src/core/CLucene/search/WildcardQuery.cpp
	do
		filtrer "$i" sed -e s/_tcsstr/::wcsstr/g -e s/_tcschr/::wcschr/g
	done
}

# Variables

archive_git="git://clucene.git.sourceforge.net/gitroot/clucene/clucene"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
optionsConf=
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
cmake -DCMAKE_INSTALL_PREFIX="$dest/" $optionsConf

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
