#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

prerequis="pkgconfig make \\ ncurses iconv ffmpeg mad ogg opus opusfile" # pkgconfig pour ffmpeg et opus; ncurses GNU pour le support des caractères multi-octets.
v 2.5.0 && modifs="cppflags fpic monCc strndupBsd" || true
v 2.5.1 || true
v 2.7.1 || true
v 2.8.0.2019.01.16 && versionComplete="$version.c39b5662a10a463427b54bb6c1e2714db59a65d9.git" || true
v 2.8.0.2019.11.05 && versionComplete="$version.354625c5a229111ecb68457c4238aa6b9a1d9ebe.git" || true
v 2.9.0 || true
v 2.9.1 || true
v 2.10.0 || true
v 2.12.0 || true

argOptions="`options $argOptions=aac`"
if option aac ; then prerequis="$prerequis libfaad mp4" ; fi

# Modifications

cppflags()
{
	filtrer scripts/checks.sh sed -e 's#\$CFLAGS#& $CPPFLAGS#g'
}

strndupBsd()
{
	touch -r xmalloc.h /tmp/h
	# https://bugs.freebsd.org/bugzilla/attachment.cgi?id=176956&action=edit
	filtrer xmalloc.h sed -e '/ifdef HAVE_STRNDUP/a\
char *strndup(const char*, size_t);
'
	touch -r /tmp/h xmalloc.h
}

monCc()
{
	# M'emmerdent, ces gcc codés en dur.
	HOSTCC="$CC" # On repose sur le $CC défini par les prérequis plate-forme.
	export CC HOSTCC
}

archive=http://netcologne.dl.sourceforge.net/project/cmus/cmus-v$version.tar.bz2
pge $version 2.5.1 && archive="https://github.com/cmus/cmus/archive/v$version.tar.gz" || true
archive_git="https://github.com/cmus/cmus.git"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
