#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

prerequis="make \\"
v 0.92.3 && modifs="freebsd" || true
v 0.93.99.2022.10.14 && versionComplete="$version.533f1379af36a5a49cd6bdc074a686937ce9242e.git" && modifs="fbsd2 prefixe" || true

# Modifications

prefixe()
{
	for f in Makefile*
	do
		filtrer "$f" sed -e "s#^PREFIX *:=#PREFIX := $dest#"
	done
}

fbsd2()
{
	[ `uname` = FreeBSD ] || return 0
	filtrer Makefile sed -e 's/ -Wno-unused-but-set-variable//g'
	filtrer Makefile sed -e 's/install -D/install/g'
	# Sur les nouveaux FreeBSD, il n'y a carrément plus de gcc.
	[ -e Makefile.clang ] || cp Makefile Makefile.clang
	filtrer Makefile.clang sed -e '/OBJS=/s/^	*//' -e 's/gcc/clang/g'
	filtrer configure sed -e '/^CCS=/s/="/="clang /'
	
	filtrer utils.h sed -e '/if defined(__FreeBSD__)/a\
#include <sys/socket.h>
'
	filtrer pac.c sed -e '/pac\.h/{
a\
#include <netinet/in.h>
a\
#include <sys/socket.h>
}'
}

# Adaptations au vieux GCC de FreeBSD.
freebsd()
{
	[ `uname` = FreeBSD ] || return 0
	filtrer Makefile sed -e 's/ -Wno-unused-but-set-variable//g'
	filtrer Makefile sed -e 's/install -D/install/g'
	# Sur les nouveaux FreeBSD, il n'y a carrément plus de gcc.
	[ -e Makefile.clang ] || cp Makefile Makefile.clang
	filtrer Makefile.clang sed -e '/OBJS=/s/^	*//' -e '/^ifeq/d' -e '/^else/,/^endif/d' -e 's/gcc/clang/g'
	filtrer configure sed -e '/^CCS=/s/="/="clang /'
}

# Variables

archive="http://freefr.dl.sourceforge.net/project/cntlm/cntlm/cntlm%20$version/cntlm-$version.tar.gz"
archive_git="https://github.com/versat/cntlm.git"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if pg 0.93.99 $version
then
	OPTIONS_CONF=--prefix="$dest"
fi
./configure $OPTIONS_CONF

echo Compilation… >&2
make

echo Installation… >&2
#sudo make install
sudo mkdir -p $dest/bin
sudo cp cntlm $dest/bin/

sutiliser
