#!/bin/bash
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.bash"

logiciel=curl

# Historique des versions gérées

version=7.16.0
version=7.16.1
version=7.16.2
version=7.17.0
version=7.18.0
version=7.19.5
version=7.20.1

version=7.21.0
modifs=dyld105
archis=oui

version=7.23.0

version=7.26.0

# Modifications

# Variables

archive="http://curl.haxx.se/download/$logiciel-$version.tar.bz2"
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

if [ "$archis" = oui -a "`sysctl -n hw.optional.x86_64`" = 1 ]
then
	cp -R . ../$logiciel-$version-x86_64
	cp -R . ../$logiciel-$version-i386
	cd ../$logiciel-$version-x86_64
	export CFLAGS="-arch x86_64"
	export LDFLAGS="$LDFLAGS -arch x86_64"
	./configure --prefix="$dest"
	make
	sudo make install
	sudo rm -Rf "$dest.x86_64"
	sudo mv "$dest" "$dest.x86_64"
	cd ../$logiciel-$version-i386
	export CFLAGS="-arch i386"
	export LDFLAGS="-arch i386"
	./configure --prefix="$dest"
	make
	sudo make install
	cd "$dest"
	for i in . "$dest.x86_64"
	do
		i="$i/bin/curl-config"
		sed -e 's/-arch i386//g' -e 's/-arch x86_64//g' < "$i" > "$TMP/$$/temp.filtrer" && sudo sh -c "cat $TMP/$$/temp.filtrer > $i"
	done
	diff -rq . "$dest.x86_64" 2> /dev/null | sed -e 's/^Files //' -e 's/ and .*differ//' | while read i
	do
		if [ ! -L "$i" ]
		then
			nom="`basename "$i"`"
			suffixe=$nom
			[[ "$nom" = *.* ]] && suffixe=".${nom##*.}"
			case "$suffixe" in
				.h)
					diff -D __x86_64__ "$i" "$dest.x86_64/$i" > "$TMP/$$/temp.diffD" || true
					sudo sh -c "cat $TMP/$$/temp.diffD > $i"
					;;
				*.la|curl-config)
					true
					;;
				*)
					lipo -create "$i" "$dest.x86_64/$i" -output "$TMP/$$/temp.lipo$suffixe" && sudo sh -c "cat $TMP/$$/temp.lipo$suffixe > $i"
					;;
			esac
		fi
	done
	sudo rm -Rf "$dest.x86_64"
else
	echo Configuration… >&2
	./configure --prefix="$dest"
	
	echo Compilation… >&2
	make
	
	echo Installation… >&2
	sudo make install
fi

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"

curl http://curl.haxx.se/ca/cacert.pem > $HOME/.curl-ca-bundle.crt
