#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=curl

# Historique des versions gérées

v 7.16.0 && modifs="multiarch sslcertfile" || true
version=7.16.1
version=7.16.2
version=7.17.0
version=7.18.0
version=7.19.5
version=7.20.1
v 7.21.0 && modifs="multiarch dyld105 sslcertfile" || true
version=7.23.0

version=7.26.0

v 7.38.0 || true
v 7.39.0 || true
v 7.43.0 || true
v 7.49.0 || true
v 7.53.1 || true

# Modifications

sslcertfile()
{
	filtrer lib/curl_setup.h sed -e '/defined.*CURL_WANTS_CA_BUNDLE_ENV/{
i\
#define CURL_CA_BUNDLE (getenv("CURL_CA_BUNDLE") && strlen(getenv("CURL_CA_BUNDLE")) ? getenv("CURL_CA_BUNDLE") : getenv("SSL_CA_CERT"))
}
'
	filtrer configure sed -e "/want_ca=\"unset\"/s#=.*#=\"$dest/share/curl-ca-bundle.crt\"#"
}

multiarchPrecombiner()
{
	f="$2/bin/curl-config"
	sed -e "s/-arch $1//g" < "$f" > "$TMP/$$/temp.filtrer" && sudo sh -c "cat $TMP/$$/temp.filtrer > $f"
}

installerAC()
{
	echo "=== Installation des certificats AC ==="
	(
		export PATH="$dest/bin:$PATH"
		export LD_LIBRARY_PATH="$dest/lib:$LD_LIBRARY_PATH"
		# On précise exactement le curl que l'on veut charger, des fois qu'une surcharge sous forme de fonction shell soit en place.
		"$dest/bin/curl" -k -L http://curl.haxx.se/ca/cacert.pem > .curl-ca-bundle.crt
		destac="`"$dest/bin/curl-config" --ca`"
		sudo mkdir -p "`dirname "$destac"`"
		sudo cp .curl-ca-bundle.crt "$destac"
		cp .curl-ca-bundle.crt "$HOME/"
	)
}

# Variables

archive="http://curl.haxx.se/download/$logiciel-$version.tar.bz2"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

	echo Configuration… >&2
	./configure --prefix="$dest"
	
	echo Compilation… >&2
	make
	
	echo Installation… >&2
	sudo make install
installerAC

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
