#!/bin/bash
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

# Historique des versions gérées

logiciel=darcs
version=1.0.1

version=1.0.3

version=1.0.4pre4
modifs=configureSansDarcs

( cd /tmp && command -v darcs ) > /dev/null \
&& version="2005-10-04@not generate null binary" \
&& modifs=

( cd /tmp && command -v darcs ) > /dev/null \
&& version="2005-11-03@ask-deps"

version=1.0.6

version=1.0.9rc2 ; modifs=

version=2.0.0pre3

version=2.0.0

version=2.0.2

version=2.1.0

v 2.3.0

v 2.3.1 && biblios="haskeline hashed-storage terminfo" || true

( cd /tmp && command -v darcs ) > /dev/null \
&& version="2009-11-14@Resolve issue1224"

v 2.4 || true
v 2.4.1 && biblios="haskeline hashed-storage terminfo html mtl parsec regex-compat" || true
v 2.4.4 && biblios="haskeline:0.6.2.2 hashed-storage:0.4.13 terminfo:0.3.1.2 html:1.0.1.2 mtl:1.1.0.2 parsec:3.0.1 regex-compat:0.93.1" || true
# C'est chiant, un darcs cha me sort les trucs en pseudo ISO8859 (http://www.mail-archive.com/darcs-users@darcs.net/msg17276.html)
v 2.5 && biblios="haskeline:0.6.2.2 hashed-storage:0.5.4 terminfo:0.3.1.2 html:1.0.1.2 mtl:1.1.0.2 parsec:3.1.0 regex-compat:0.93.1 tar:0.3.1.0 text:0.10.0.0" || true
v 2.5.1 && modifs=sortieBrute && biblios="haskeline:0.6.2.2 hashed-storage:0.5.4 terminfo:0.3.1.2 html:1.0.1.2 mtl:1.1.0.2 parsec:3.0.1 regex-compat:0.93.1 tar:0.3.1.0 text:0.11.0.5" || true
v 2.8.2 && biblios="haskeline:0.6.4.7 hashed-storage:0.5.10 mtl:2.1.2 parsec:3.1.3 random:1.0.1.1 regex-compat:0.95.1 tar:0.3.2.0 text:0.11.2.3 vector:0.10.0.1" || true
v 2.8.4 && biblios="haskeline:0.7.0.3 hashed-storage:0.5.10 mtl:2.1.2 parsec:3.1.3 random:1.0.1.1 regex-compat:0.95.1 tar:0.4.0.1 text:0.11.2.3 vector:0.10.0.1" || true

dest=$INSTALLS/$logiciel-$version
archive=http://darcs.net/$logiciel-$version.tar.gz
pge $version 2.3.0 && archive=http://darcs.net/releases/$logiciel-$version.tar.gz
archive_darcs=http://darcs.net
[[ "$version" = 2005* ]] && archive_darcs=http://darcs.net/repos/darcs

inclure ghc

inclureBiblios -t haskell

# Modifications

configureSansDarcs()
{
	# Déjà vu par David Roundy, mais pas encore intégré.
	patch -p0 << TERMINE
--- configure      2005-09-10 21:45:09.000000000 +0200
+++ configure   2005-09-10 21:45:32.000000000 +0200
@@ -1370,7 +1370,7 @@
 
 echo "\$as_me:\$LINENO: checking the release state.." >&5
 echo \$ECHO_N "checking the release state..... \$ECHO_C" >&6
-if test -z "\$DARCS" || test -d "_darcs"; then
+if test ! -z "\$DARCS" && test -d "_darcs"; then
   DARCS_VERSION_STATE=\`perl determine_release_state.pl \$DARCS_VERSION\`;
   I_AM_IN_REPO=1
 else
TERMINE
}

sortieBrute()
{
	# http://www.mail-archive.com/darcs-users@darcs.net/msg17276.html
	filtrer src/darcs.hs grep -v 'hSetBinaryMode.*True'
}

# Boulot

[ -d "$dest" ] && exit 0

if [[ $version = *@* ]] ; then
	obtenirEtAllerDansDarcs -n "${version%%@*}" -p "${version#*@}" "$archive_darcs"
	[[ "$version" = 2005* ]] && autoconf
else
	obtenirEtAllerDans "$archive"
fi

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if pge $version 2.3.0
then
	runghc Setup configure --prefix="$dest" --flags="color terminfo curses"
else
	./configure --prefix="$dest"
fi

echo Compilation… >&2
if pge $version 2.3.0
then
	runghc Setup build
else
	make
fi

echo Installation… >&2
if pge $version 2.3.0
then
	sudo runghc Setup install || true
	[ -d "$dest" ] || exit 1
	sudo mkdir -p "$dest/bin"
	sudo cp dist/build/darcs/darcs "$dest/bin/darcs"
else
	sudo make install
fi

sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
