#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 4.2.52 && modifs="fpic atomicce fbsd10" || true
v 4.3.28 || true
v 4.5.20 || true
v 5.0.21 || true
v 5.2.36 || true
v 5.3.15 || true
v 5.3.21 || true
v 5.3.28 || true
v 6.0.35 || true
v 6.2.38 && retirerModif atomicce || true
v 18.1.32 || true

archive="ftp://sleepycat1.inetu.net/releases/$logiciel-$version.tar.gz"
archive="http://download-uk.oracle.com/berkeley-db/$logiciel-$version.tar.gz"
archive="http://download-uk.oracle.com/berkeley-db/$logiciel-$version.tar.gz"
archive="http://download.oracle.com/berkeley-db/db-$version.tar.gz"
archive="http://download.oracle.com/otn/berkeley-db/db-$version.tar.gz"

atomicce()
{
	# Les versions modernes des compilos embarquent une fonction qui a le même nom qu'une interne des vieux DB. On surcharge donc la définition et son utilisation.
	# À partir de quelque part entre la 6.0.35 et la 6.2.38, changement de fusil d'épaule: DB ne surcharge pas, au contraire il exploite la fonctionnalité; à ce moment il ne faut surtout plus surcharger (la seule utilisation), sans quoi undefined symbol.
	filtrer src/dbinc/atomic.h sed -e 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g'
}

prerequis

destiner

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in $modifs true ; do $modif ; done

echo Configuration… >&2
cd ./build_unix
../dist/configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser
