#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Travail préalable: dossier Perl auquel se greffer.

analyserParametres()
{
	case " $*" in
		*" -d "*)
			PATH="`echo "xxx $*" | sed -e 's/.* -d //g' -e 's/ .*//'`/bin:$PATH"
			;;
	esac
}

analyserParametres "$@"

v_perl="`perl -MConfig -e 'print "$Config{PERL_REVISION}.$Config{PERL_VERSION}.$Config{PERL_SUBVERSION}";'`"
argOptions="+perl_`echo "$v_perl" | tr . _`"

# Historique des versions gérées

# On doit mettre dans nos dépendances toutes celles d'svn, afin que le svn recompilé par perl dans son SVN::Core détecte toutes les biblios externes qui lui permettront d'accéder aux URL http://, https://, etc.
# Notons que SVN::Core compile sa propre version de SVN; pour que les dépendances soient plus ou moins les mêmes, il nous faut une version approchante.
v 1.0.0 && prerequis="perl sqlite apr apr-util expat svn < 1.9 `varsPrerequis prerequis-r "svn < 1.9"`" && modifs="exclusivementPrerequis" || true

# Modifications

# Variables

destiner

prerequis

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo "Compilation & Installation…" >&2
PERL_MM_USE_DEFAULT=1 PERL_EXTUTILS_AUTOINSTALL="--defaultdeps" cpan install SVN::Core
sudoku mkdir -p "$dest" # Pour que sutiliser puisse y déposer son témoin de bonne installation.

# Au moins pour le marqueur de bonne installation.
sutiliser -
