#!/bin/bash
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

if [ "$SCRIPTS" = "" ] ; then SCRIPTS=`which "$0"` ; SCRIPTS=`dirname "$SCRIPTS"` ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS" ; fi
. "$SCRIPTS/util.sh"

logiciel=dlcompat
version=20030629
dest=/usr/local/$logiciel-$version

[ -d "$dest" -o -f "/usr/include/dlfcn.h" ] && exit 0 # Depuis Tiger, on a ce qu'il faut en dl*.

# Test plus poussé.
cat > "$TMP/testdl.c" <<TERMINE
#include <dlfcn.h>
void * dlopen(const char * path, int mode);
int main(int argc, char ** argv) { dlopen("/tmp/bloug", 0000); }
TERMINE
if cc -o "$TMP/testdl" "$TMP/testdl.c" 2> /dev/null || cc -o "$TMP/testdl" -ldl "$TMP/testdl.c" 2> /dev/null
then
	exit 0
fi

cd /tmp
echo Obtention et décompression… >&2
tar xzf `obtenir "http://ovh.dl.sourceforge.net/sourceforge/fink/$logiciel-$version.tar.gz"`

cd /tmp/$logiciel-$version
echo Configuration… >&2
./configure --prefix=/usr/local/$logiciel-$version

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser $logiciel-$version
