#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=duc

# Historique des versions gérées

v 1.3.3 && prerequis="tokyocabinet ncursesw" && modifs="fstatat" || true

# Modifications

fstatat()
{
	case `uname` in
		Darwin)
			[ -f fstatat.h ] || curl -O https://raw.githubusercontent.com/freebsd/freebsd/master/contrib/openbsm/bin/auditdistd/fstatat.h
			[ -f openat.h ] || curl -O https://raw.githubusercontent.com/freebsd/freebsd/master/contrib/openbsm/bin/auditdistd/openat.h
			filtrer openat.h sed -e 's#if (fchdir(fd)#if (fd > 0 \&\& fchdir(fd)#'
			filtrer src/libduc/index.c sed -e '/^#include "db.h"/{
i\
#include "../../fstatat.h"
i\
#include "../../openat.h"
i\
#include "../../compat.h"
}' -e 's/fdopendir(\([^)]*\))/fdopendir2(\1, fd_parent)/g' -e '/closedir/i\
close(scanner->fd);
'
			cat > compat.h <<TERMINE
DIR * fdopendir2(int fd, int ici)
{
	DIR * r;
	fchdir(fd);
	r = opendir(".");
	if(ici > 0)
		fchdir(ici);
	return r;
}
TERMINE
			;;
	esac
}

# Variables

archive="http://duc.zevv.nl/release/duc-$version.tar.gz"
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" --disable-x11

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
