#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

if [ "$SCRIPTS" = "" ] ; then SCRIPTS=`which "$0"` ; SCRIPTS=`dirname "$SCRIPTS"` ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS" ; fi
. "$SCRIPTS/util.sh"

inclure erlang
inclure expat

logiciel=ejabberd

v 0.7 && modifs="compilMac installVarLib" || true
v 1.1.2 && modifs= || true
v 2.1.1 && modifs= || true

archive=http://www.jabberstudio.org/files/ejabberd/$logiciel-$version.tar.gz
archive=http://www.process-one.net/en/projects/$logiciel/download/$version/$logiciel-$version.tar.gz
archive=http://www.process-one.net/downloads/ejabberd/$version/ejabberd-$version.tgz
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

compilMac()
{
	# Merci à Magnus Henoch pour m'avoir donné envie de fouiller dans le man ld
	find src -name Makefile.in | while read fichier ; do
		filtrer "$fichier" sed -e 's/-shared/-bundle -flat_namespace -undefined suppress/'
	done
}

installVarLib()
{
	# Quelle bande d'enculés! Je ne leur ai jamais dit de s'installer dans /var/lib!
	filtrer src/Makefile.in sed -e 's/^DESTDIR[ 	]*=/DESTDIR = @prefix@/'
}

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
cd src
./configure --prefix=$dest --with-expat

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser $logiciel-$version

rm -Rf "$TMP/$$"
