#!/bin/bash
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.bash"

inclure db
inclure sqlite
inclure dovecot

logiciel=exim

# Historique des versions gérées

v 4.77
v 4.80.1 && prerequis="pcre"

prerequis

# Modifications

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="http://exim.mirror.fr/exim/exim4/$logiciel-$version.tar.bz2"

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
sed < src/EDITME > Local/Makefile \
	-e "/^BIN_DIRECTORY=/s#=.*#=$dest/bin#" \
	-e "/^CONFIGURE_FILE=/s#=.*#=$dest/etc/exim#" \
	-e "/^EXIM_USER=/s#=.*#=postfix#" \
	-e "/^SPOOL_DIRECTORY=/s#=.*#=$dest/var/spool/exim#" \
	-e "/^EXIM_MONITOR=/s#=.*#=#" \
	-e "/^# LOOKUP_LDAP=yes/s/^# //" \
	-e "/^# LOOKUP_PASSWD=yes/s/^# //" \
	-e "/^# LOOKUP_SQLITE=yes/s/^# //" \
	-e "/^# AUTH_DOVECOT=yes/s/^# //" \
	-e "/^# SUPPORT_PAM=yes/s/^# //" \
	-e "/^# SUPPORT_MAILDIR=yes/s/^# //" \
	-e "/^# LDAP_LIB_TYPE=OPENLDAP2/s/^# //" \
	-e '/^# LOOKUP_INCLUDE=/{
a\
LOOKUP_INCLUDES='"-I$INSTALLS/include"'
}' \
	-e '/^# LOOKUP_LIBS=/a\
LOOKUP_LIBS='"-L$INSTALLS/lib -lldap -llber -lsqlite3 -ldb -lpam"'
' \
	-e '${
a\
USE_DB=yes
a\
CC=cc $(LOOKUP_INCLUDES)
a\
LDCC=cc $(LOOKUP_INCLUDES) $(LOOKUP_LIBS)
a\
LIBS += $(PCRE_LIBS) $(LOOKUP_LIBS)
}'

echo Compilation… >&2
make || ( filtrer build-`uname`-`uname -m`/Makefile sed -e '/^\.if/,/^\.endif/d' && make )

echo Installation… >&2
sudo make install
sudo mkdir -p "$dest/var/spool/exim/log"
sudo chown -R postfix "$dest/var"
sutiliser "$logiciel-$version"
[ -h /usr/sbin/sendmail -o ! -e /usr/sbin/sendmail ] && sudo rm -f /usr/sbin/sendmail && sudo ln -s "$dest/bin/exim" /usr/sbin/sendmail

rm -Rf "$TMP/$$"

exit 0

# Pour tester:
read mdp
adrip="`ifconfig | grep inet | cut -d ' ' -f 2 | head -1`"
lisRes()
{
	grep --max-count=1 "$1" > /tmp/temp.$$.rep
	grep -q "^5" < /tmp/temp.$$.rep && echo QUIT && touch /tmp/temp.$$.rate && exit 0 || true
}
cause()
{
	if [ -z "$chut" ]
	then
		tee -a /dev/tty
	else
		tee -a /tmp/temp.$$.trace
	fi
}
envoi()
{
	auth=oui
	[ "x$1" = x--sans-auth ] && shift && auth=non
	adr=$adrip
	[ "x$1" = x--localhost ] && shift && adr=127.0.0.1
	dequiaffiche=
	[ "x$1" = x-f ] && shift && dequiaffiche="$1" && shift
	quoi="$1"
	dequi="$2"
	[ "x$dequiaffiche" = x ] && dequiaffiche="$dequi"
	aqui="$3"
	dequiauth="`echo "$dequi" | sed -e 's/-[^@]*@/@/'`"
	plain=`printf ^$dequiauth^$mdp | tr ^ '\000' | openssl base64`
	mkfifo /tmp/temp.$$.fifo
	rm -f /tmp/temp.$$.rate
	cat /tmp/temp.$$.fifo | (
		grep -q ESMTP
		echo EHLO `hostname`
		grep -q "250 "
		[ $auth = oui ] && echo AUTH PLAIN $plain && grep -q "235 "
		echo "MAIL FROM:<$dequi>"
		lisRes "[25]50 "
		echo RCPT TO: $aqui
		lisRes "[25]50 "
		echo DATA
		grep -q "354 "
		echo Subject: essai de Guillaume $quoi
		echo From: $dequiaffiche
		echo
		echo COUCOU DE $dequi
		echo .
		grep -q "250 "
		echo QUIT
		grep -q "221 "
	) | cause | telnet $adr 25 2>&1 | cause > /tmp/temp.$$.fifo
	rm /tmp/temp.$$.fifo
	echo "$quoi" | cut -d ' ' -f 1 | tr -d '\012'
	oui=Oui
	[ -e /tmp/temp.$$.rate ] && oui=Non || true
	couleur='@[0;31m'
	echo "$quoi" | grep -q "^$oui" && couleur='@[0;32m' || true
	echo ": $couleur$oui"'@[0m' | tr @ '\033'
}
envoi Oui1 gui-envoyant@gclo.fre guillaume-destinataire@outters.eue
envoi -f guidouille-envoyant@gclo.fre OuiMais1 gui-envoyant@gclo.fre guillaume-destinataire@outters.eue # Oui, mais From forcé à ce qui est réécrit.
envoi Oui2 gui-envoyant@gclo.fre guillaume@outters.eu
envoi --sans-auth Non1 gui@gclo.fre guillaume-destinataire@outters.eue # Interne non authentifié interdit
envoi --sans-auth Oui3 guillaume@outters.eu guillaume-destinataire@outters.eue # Externe vers interne: sans auth
envoi --sans-auth Non2 guillaume@outters.eu guillaume@outters.eu # Relai interdit
envoi --sans-auth --localhost Oui4 fournil@outters.eue guillaume-destinataire@outters.eue # Du moment qu'il est référencé dans outters.eue.automates, ça passe (serveur PHP émettant).
envoi --sans-auth --localhost Non3 fourmil@outters.eue guillaume-destinataire@outters.eue # Un serveur local qui n'est pas inscrit se fait jeter.
echo "COUCOU de `id`" | mail -s "essai de Guillaume Oui5" guillaume@outters.eu # Juste parce que l'utilisateur courant a été autorisé dans ici.la.automates.
echo "COUCOU de `id`" | mail -s "essai de Guillaume Oui6" guillaume@outters.eue
