#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

inclure db
inclure sqlite
inclure dovecot

logiciel=exim

# Historique des versions gérées

v 4.77 && modifs="menageMakefile lthr majmin" || true
v 4.80.1 && modifs="menageMakefile lthr majmin paf" && prerequis="pcre" || true
v 4.82
v 4.82.1
v 4.87 || true
v 4.89 && modifs="uniquementPrerequis menageMakefile lthr majmin paf2 tlsManuel" && prerequis="pcre openssl" || true
v 4.90.1 || true

prerequis

# Modifications

majmin()
{
	# On définit en plus de RELEASE_VERSION (4.90) une MAJOR (4) et une MINOR (90).
	mm_v="`grep EXIM_RELEASE_VERSION= < src/version.sh | cut -d = -f 2`"
	(
		echo "EXIM_MAJOR_VERSION=`echo "$mm_v" | cut -d . -f 1`"
		echo "EXIM_MINOR_VERSION=`echo "$mm_v" | cut -d . -f 2`"
	) >> src/version.sh
	filtrer scripts/reversion sed -E -e '/echo EXIM_RELEASE_VERSION=|#define EXIM_RELEASE_VERSION/{
h
s/\$EXIM_RELEASE_VERSION/`echo $EXIM_RELEASE_VERSION | cut -d . -f 1`/
s/"//g
s/RELEASE/MAJOR/
p
g
s/\$EXIM_RELEASE_VERSION/`echo $EXIM_RELEASE_VERSION | cut -d . -f 2`/
s/"//g
s/RELEASE/MINOR/
p
g
}'
}

tlsManuel()
{
	# À partir de la 4.89, apparemment, il faut expliciter SUPPORT_TLS pour que celui-ci soit inclus pour que le DKIM soit inclus.
	
	echo "SUPPORT_TLS=yes" >> Local/Makefile
	echo "TLS_LIBS=-L$destopenssl/lib -lssl -lcrypto" >> Local/Makefile
	echo "TLS_INCLUDE=-L$destopenssl/include" >> Local/Makefile
}

menageMakefile()
{
	[ -f Local/Makefile ] || return 0
	filtrer Local/Makefile sed -e '/# Guillaume:/,$d'
	echo '# Guillaume:' >> Local/Makefile
}

paf2()
{
	cp "$SCRIPTS/exim.paf2.c" Local/
	echo "LOCAL_SCAN_SOURCE=Local/exim.paf2.c" >> Local/Makefile
	echo "LOCAL_SCAN_HAS_OPTIONS=yes" >> Local/Makefile
	echo "WITH_CONTENT_SCAN=yes" >> Local/Makefile # paf2 repose sur un SA ou un rspamd, qui ont besoin de cette option.
}

paf()
{
	cp $HOME/src/projets/paf/paf.c Local/ || true
	echo "LOCAL_SCAN_SOURCE=Local/paf.c" >> Local/Makefile
	echo "LOCAL_SCAN_HAS_OPTIONS=yes" >> Local/Makefile
}

lthr()
{
	case `uname` in
		FreeBSD)
			cat > $TMP/$$/testpthr.c <<TERMINE
#include <pthread.h>
int main(int argc, char ** argv)
{
	pthread_create(NULL, NULL, NULL, NULL);
}
TERMINE
			for BIBLIOS_PTHREAD in "" "-lthr"
			do
				cc -o $TMP/$$/testphr $TMP/$$/testpthr.c "$BIBLIOS_PTHREAD" 2> /dev/null >&2 && break || true
			done
			;;
	esac
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="http://exim.mirror.fr/exim/exim4/$logiciel-$version.tar.bz2"
archive="http://ftp.exim.llorien.org/exim/exim4/$logiciel-$version.tar.bz2"

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
# Avec ou sans LDAP?
if false
then
	BIBLIOS_LDAP="-lldap -llber"
else
	CONF_LDAP="# "
fi
sed < src/EDITME >> Local/Makefile \
	-e "/^BIN_DIRECTORY=/s#=.*#=$dest/bin#" \
	-e "/^CONFIGURE_FILE=/s#=.*#=$dest/etc/exim#" \
	-e "/^EXIM_USER=/s#=.*#=`id -u -n`#" \
	-e "/^SPOOL_DIRECTORY=/s#=.*#=$dest/var/spool/exim#" \
	-e "/^EXIM_MONITOR=/s#=.*#=#" \
	-e "/^# LOOKUP_LDAP=yes/s/^# /$CONF_LDAP/" \
	-e "/^# LOOKUP_PASSWD=yes/s/^# //" \
	-e "/^# LOOKUP_SQLITE=yes/s/^# //" \
	-e "/^# AUTH_DOVECOT=yes/s/^# //" \
	-e "/^# SUPPORT_PAM=yes/s/^# //" \
	-e "/^# SUPPORT_MAILDIR=yes/s/^# //" \
	-e "/^# LDAP_LIB_TYPE=OPENLDAP2/s/^# /$CONF_LDAP/" \
	-e '/^# LOOKUP_INCLUDE=/{
a\
LOOKUP_INCLUDES='"-I$INSTALLS/include"'
}' \
	-e '/^# LOOKUP_LIBS=/a\
LOOKUP_LIBS='"-L$INSTALLS/lib $BIBLIOS_LDAP -lsqlite3 -ldb -lpam $BIBLIOS_PTHREAD"'
' \
	-e '${
a\
USE_DB=yes
a\
CC=cc $(LOOKUP_INCLUDES)
a\
LDCC=cc $(LOOKUP_INCLUDES) $(LOOKUP_LIBS)
a\
LIBS += $(PCRE_LIBS) $(LOOKUP_LIBS)
}'
make configure

echo Compilation… >&2
filtrer build-`uname`-`uname -m`/Makefile sed -e '/^\.if/,/^\.endif/d'
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
