#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

inclure x264

logiciel=ffmpeg

# Historique des versions gérées

version=2005-10-14
modifs=panther
OPTIONS_CONF=(--disable-altivec) # h264_chroma_mc8, entre autres, a une variable non initialisée qui fait tout planter.

version=2005-10-29

version=r6177
modifs=
OPTIONS_CONF=(--enable-x264 --enable-gpl --enable-libogg --enable-vorbis --enable-pp --enable-shared)

# Modifications

# L'édition de liens utilise un truc qui ne marche que pour 10.3… et a la bonne
# grâce de nous le signaler.
panther()
{
	export MACOSX_DEPLOYMENT_TARGET=10.3
}

# Variables

dest="/usr/local/$logiciel-$version"
archive_cvs="cvs://anonymous:@mplayerhq.hu:/cvsroot/$logiciel:$logiciel"
archive_svn=svn://svn.mplayerhq.hu/$logiciel/trunk

[ -d "$dest" ] && exit 0

if [[ $version = r* ]] ; then
	obtenirEtAllerDansSvn -r ${version#r} $archive_svn
elif [[ $version = *-* ]] ; then
	obtenirEtAllerDansCvs -d $version $archive_cvs
else
	obtenirEtAllerDans "$archive"
fi

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" "${OPTIONS_CONF[@]}"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sudo utiliser "$logiciel-$version"

rm -Rf /tmp/$$
