#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=ffmpeg

inclure pkgconfig

# Historique des versions gérées

version=2005-10-14
modifs=panther
OPTIONS_CONF="--disable-altivec" # h264_chroma_mc8, entre autres, a une variable non initialisée qui fait tout planter.

version=2005-10-29

version=r6177
modifs=avecX264
OPTIONS_CONF="--enable-x264 --enable-gpl --enable-libogg --enable-vorbis --enable-pp --enable-shared"

v 0.7-rc1 && modifs= && OPTIONS_CONF="--enable-gpl --enable-nonfree --enable-shared --disable-yasm"
v 1.0 && modifs= && OPTIONS_CONF="--enable-gpl --enable-nonfree --enable-shared --enable-libopus" && inclure yasm && inclure opus
v 1.0.1 && prerequis="lame" OPTIONS_CONF="--enable-gpl --enable-nonfree --enable-shared --enable-libopus --enable-libmp3lame"
v 2.5 && modifs="monCc" prerequis="opus lame >= 3.98.3" || true
v 2.5.2 || true
v 3.2.2 || true

# http://lists.freebsd.org/pipermail/freebsd-questions/2012-February/238956.html
if [ `uname` = FreeBSD -a `uname -r | sed -e 's/[^0-9].*//'` -lt 10 ] # Le 10 est arbitraire.
then
	prerequis="$prerequis binutils"
fi

prerequis

# Modifications

monCc()
{
	# binutils: http://lists.freebsd.org/pipermail/freebsd-questions/2012-February/238956.html; mais même avec ça ça ne passe pas, on fait donc un export CC=/usr/bin/gcc (sur mon FreeBSD: /usr/local/bin/gcc == 4.9, /usr/bin/gcc == 4.2). La 4.2 est la plus stable (la 4.9 se vautre fréquemment en SEGFAULT), donc on fera le gros de la compil en 4.2 avec le CC=…, et de temps à autre quand on aura des plantages 64 bits, on lancera le make, faisant un ps auxww | grep cc, on repérera la ligne qui tourne avant qu'elle ne plante, et on la relancera en remplaçant l'/usr/bin/gcc par gcc. Puis make jusqu'au prochain plantage pour continuer en 4.2, etc.
	command -v gcc > /dev/null 2>&1 || CC=cc
	if [ ! -z "$CC" ] ; then
		filtrer configure sed -e '/^host_cc_default=/c\
host_cc_default="'"$CC"'"
' -e '/^cc_default=/c\
cc_default="'"$CC"'"
'
	fi
}

avecX264()
{
	inclure x264
}

# L'édition de liens utilise un truc qui ne marche que pour 10.3… et a la bonne
# grâce de nous le signaler.
panther()
{
	export MACOSX_DEPLOYMENT_TARGET=10.3
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive_cvs="cvs://anonymous:@mplayerhq.hu:/cvsroot/$logiciel:$logiciel"
archive_svn=svn://svn.mplayerhq.hu/$logiciel/trunk
archive="http://ffmpeg.org/releases/ffmpeg-$version.tar.bz2"

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
make -j 4

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
