#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delibere() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delibere ; s="`dirname "$s"`" ; Delibere ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 2.3.2 && prerequis="make pkgconfig \\ zlib freetype expat gperf" || true
# La 2.3.2 est boguée, leur FcObjectStaticName n'est pas généralisé et du coup
# les comparaisons de chaînes par pointeur ne marchent pas partout.
version=2005-06-28
v 2.10.0 && modifs="$modifs glibc225" || true
v 2.10.2 || true
v 2.10.95 || true
v 2.11.1 || true
v 2.12.0 || true
v 2.12.1 || true
v 2.12.2 && retirerModif glibc225 || true
v 2.12.6 || true
#v 2.13.1 || true # La 2.12.91 et suivantes utilisent uuid_generate, spécifique Linux (il faudrait une version qui sache faire du uuid_create sous BSD).
# Les suivantes ont heureusement regagné en tout-terrain.
v 2.13.96 && prerequis="python >= 3 \\ $prerequis" && modifs="$modifs toiDAbord" || true
v 2.14.1 || true
v 2.16.0 || true
v 2.16.2 || true
v 2.17.1 && prerequis="meson ninja \\ $prerequis" || true

suffixe=xz
pge $version 2.14 || suffixe=gz
archive=https://www.freedesktop.org/software/fontconfig/release/$logiciel-$version.tar.$suffixe
pg 2.16 $version ||
archive=https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/$version/fontconfig-$version.tar.bz2
archive_cvs=cvs://anonymous@cvs.freedesktop.org:/cvs/fontconfig:fontconfig

# Modifications

glibc225()
{
	# https://github.com/jwilm/alacritty/issues/773
	
	for i in `grep -rl CHAR_WIDTH .`
	do
		filtrer "$i" sed -e 's/CHAR_WIDTH/CHARWIDTH/g' -e '/#define[ 	]*FC_CHARWIDTH/a\
#define FC_CHAR_WIDTH FC_CHARWIDTH
'
	done
}

toiDAbord()
{
	# Pour inspecter les dossier de polices, le make install lance les binaires tout juste installés, qui reposent sur $LD_LIBRARY_PATH, et donc plantent s'ils n'ont pas leur biblio (tout juste installée aussi) en vue.
	export LD_LIBRARY_PATH="$dest/lib:$LD_LIBRARY_PATH"
	
	# Expérimentation avant la correction de pythonenboite: interposer un programme réinscripteur de $LD_LIBRARY_PATH avant l'appel de fc-cache:
	#filtrer fc-cache/meson.build sed -e "/add_install_script(fccache/s#(#('$TMP/$$/monenv', #"
}

constantes()
{
	# Leurs constantes sont des strings. Mais à partir du moment où elles sont
	# utilisées par deux bibliothèques séparées, on va avoir deux copies de la
	# chaîne, dont les pointeurs ne seront pas égaux. Il faut donc passer par
	# une réserve unique de chaînes.
	# ATTENTION: ne marche pas car certaines constantes s'initialisent à partir
	# de la macro.
	chmod u+w fontconfig/fontconfig.h
	filtrer fontconfig/fontconfig.h sed -e '/FC_CACHE_VERSION/n' -e '\=^\(#define FC_[^"]*\)"\([^"]*\)"\([	 ]*\)\(/\*.*\*/\)\{0,1\}$=s//\1FcObjectStaticName("\2")\3/'
	chmod u-w fontconfig/fontconfig.h 
}

# Boulot

destiner

prerequis

obtenirEtAllerDansVersion

[ ! -f meson.build ] || parmeson=1

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
dossiersPolices="/usr/local/share/fonts,/Users/gui/Library/Fonts,/Library/Fonts,/System/Library/Fonts"
if [ -n "$parmeson" ]
then
	mkdir -p build
	meson setup build --buildtype=release --prefix="$dest" -D"additional-fonts-dirs=$dossiersPolices" $OPTIONS_CONF
	cd build
	make=ninja
else
	./configure --prefix="$dest" --x-includes=/usr/X11R6/include --with-add-fonts="$dossiersPolices"
	make=make
fi

echo Compilation… >&2
$make

echo Installation… >&2
if [ -n "$parmeson" ]
then
	sudokupy $make install
else
sudo make install
fi

sutiliser
