#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; }
calcScripts() { absolutiseScripts "`command -v "$1"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`" ; }
calcScripts "$0"
. "$SCRIPTS/util.sh"

logiciel=fonttools

v 2.4 && modifs=retrouvePython || true

archive=http://netcologne.dl.sourceforge.net/project/fonttools/$version/fonttools-$version.tar.gz

dest=$INSTALLS/$logiciel-$version

retrouvePython()
{
	vp="`python -V 2>&1 | sed -e 's/P/p/' -e 's/ //g' -e 's/\(\.[^.]*\).*/\1/'`"
	(
		sed -e '1,/import sys/!d' < Tools/ttx
		# Récupéré de hg, le lanceur Mercurial qui a le bon sens de faire coïncider dossier d'installation et chemins de recherche Python.
		cat <<TERMINE
import os
libdir = "../lib/$vp/site-packages/FontTools"
if libdir != "@" "LIBDIR" "@":
	if not os.path.isabs(libdir):
		libdir = os.path.join(os.path.dirname(os.path.realpath(__file__)), libdir)
	libdir = os.path.abspath(libdir)
sys.path.insert(0, libdir)
TERMINE
		sed -e '1,/import sys/d' < Tools/ttx
	) > $TMP/$$/ttx.2 && cat $TMP/$$/ttx.2 > Tools/ttx
}

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2

echo Compilation… >&2

echo Installation… >&2
sudo ./setup.py install --prefix=$dest
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
