#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 2.4 && prerequis="python \\ " && modifs=retrouvePython || true
v 2.4.0.1 && versionComplete="$version.57032a0544db2dcf07dac9f78643e8e67437138e.git" || true
v 4.2.4 && modifs= || true

archive=http://netcologne.dl.sourceforge.net/project/fonttools/$version/fonttools-$version.tar.gz
archive=https://github.com/fonttools/fonttools/archive/$version.tar.gz
archive_git=git://git.code.sf.net/p/fonttools/code

retrouvePython()
{
	vp="`python -V 2>&1 | sed -e 's/P/p/' -e 's/ //g' -e 's/\(\.[^.]*\).*/\1/'`"
	(
		sed -e '1,/import sys/!d' < Tools/ttx
		# Récupéré de hg, le lanceur Mercurial qui a le bon sens de faire coïncider dossier d'installation et chemins de recherche Python.
		cat <<TERMINE
import os
libdir = "../lib/$vp/site-packages/FontTools"
if libdir != "@" "LIBDIR" "@":
	if not os.path.isabs(libdir):
		libdir = os.path.join(os.path.dirname(os.path.realpath(__file__)), libdir)
	libdir = os.path.abspath(libdir)
sys.path.insert(0, libdir)
TERMINE
		sed -e '1,/import sys/d' < Tools/ttx
	) > $TMP/$$/ttx.2 && cat $TMP/$$/ttx.2 > Tools/ttx
}

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2

echo Compilation… >&2

echo Installation… >&2
dest0="`pwd`/dest"
rm -Rf "$dest0"
pyextinit "$dest0"
./setup.py install --prefix="$dest0"
for f in dest/bin/*
do
	mv $f $f.py
	pylanceur "`basename "$f"`.py" > "$f"
	chmod a+x "$f"
done
sudoku mkdir -p "$dest"
sudoku cp -Rp "$dest0/." "$dest/."
sutiliser - "$PYEXT"
