#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 2.1.9 && prerequis="make \\ zlib bzip2 libpng" || true
v 2.4.3 && modifs="dyld105"
v 2.4.4
v 2.4.11
v 2.4.12
#v 2.5.3
v 2.5.5
v 2.6.5
v 2.7.1 || true
v 2.9.1 && ajouterModif ftconfig && prerequis="$prerequis harfbuzz >= 2" || true

archive=http://ovh.dl.sourceforge.net/sourceforge/$logiciel/$logiciel-$version.tar.bz2
archive=http://download.savannah.gnu.org/releases/freetype/$logiciel-$version.tar.bz2

ftconfig()
{
	# À partir de la 2.9, freetype fait du pkg-config; on demande cependant freetype-config pour compatibilité (ex.: PHP le requiert encore jusq'aux versions 7.3.x).
	OPTIONS_CONF="$OPTIONS_CONF --enable-freetype-config"
}

# À moins qu'on ne nous désactive explicitement harfbuzz, on l'embarque.
case "$prerequis" in
	*harfbuzz*)
opSiPasPas hb harfbuzz
		optionsEtPrerequisIcu # Nous aurons à transmettre les options ICU à harfbuzz.
		;;
	*)
		# On vire les options hb qui n'ont pas de sens avec cette version.
		argOptions="`options "$argOptions-hb-icu-icu5-icux"`"
		;;
esac

# Si nous sommes l'itération 0 d'une compil Freetype + Harfbuzz (0. freetype --sans-hb ; 1. harfbuzz ; 2. freetype+hb) nous nous compilerons sans Harfbuzz, mais nous nous remettons tout de même l'option, afin que destiner() nous donne la même $dest que l'itération 2, et qu'ainsi l'Harfbuzz du 1. ait pour prérequis ce $dest cible.
case "$GUILI_MOIRE:" in
	*:hb:*) argOptions="`options "$argOptions+hb"`" ;;
esac

destiner

# On installe une première version de nous, sans Harfbuzz, entre notre destiner() et notre prerequis():
# - si on le faisait avant notre destiner(), ce dernier nous estimerait déjà installé et ne poursuivrait pas.
# - si on le faisait après notre prerequis(), Harfbuzz, qui se trouve dans les prérequis, ne nous détecterait pas (enfin ne détecterait pas le freetype itération 0. "de compil" mais qui s'est installé à notre emplacement, donc aux yeux d'harfbuzz c'est nous).
if option hb
then
	moire -i hb --sans-hb
fi

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in compil3264 $modifs ; do $modif "$@" ; done

echo Configuration… >&2
./configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
make
for modif in true $modifspostcompil ; do $modif "$@" ; done

echo Installation… >&2
sudo make install

case "$GUILI_MOIRE:" in
	*:hb:*) guili_deps_pondre ;; # À l'intérieur du moiré (Freetype itération 0), sutiliser() est surchargée pour ne rien faire. Cependant l'Harfbuzz (itération 1) aura besoin de nos dépendances pour les inclure aux siennes. Il nous faut donc au moins le guili_deps_pondre.
esac
sutiliser

cd "$TMP/$$" # Pour éviter que menage() n'efface le dossier de travail si on est en fin de compil 32bits alors que la compile 32+64 attend notre résultat pour continuer sur le même dossier.
