#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

delieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; delieS ; s="`dirname "$s"`" ; delieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 2.1.9 && prerequis="zlib" || true
v 2.4.3 && modifs="dyld105"
v 2.4.4
v 2.4.11
v 2.4.12
#v 2.5.3
v 2.5.5
v 2.6.5
v 2.7.1 || true
v 2.9.1 && prerequis="$prerequis harfbuzz+ft >= 2" || true

archive=http://ovh.dl.sourceforge.net/sourceforge/$logiciel/$logiciel-$version.tar.bz2
archive=http://download.savannah.gnu.org/releases/freetype/$logiciel-$version.tar.bz2

# À moins qu'on ne nous désactive explicitement harfbuzz, on l'embarque.
case "$prerequis" in
	*harfbuzz+ft*)
		case "$argOptions+" in
			*-hb[-+]*) virerPrerequis "harfbuzz+ft" ;;
			*) argOptions="`options "$argOptions=hb"`" ;;
		esac
		;;
esac
option hb || true

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in compil3264 $modifs ; do $modif "$@" ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make
for modif in true $modifspostcompil ; do $modif "$@" ; done

echo Installation… >&2
sudo make install

sutiliser
