#!/bin/bash
# Copyright (c) 2007 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

inclure libtiff
inclure libpng
inclure wxpython

logiciel=gamera

# Historique des versions gérées

version=2007-05-28
modifs=

OPTIONS_CONF=()

# Modifications

# Variables

archive_cvs="cvs://anonymous@gamera.cvs.sourceforge.net:/cvsroot/gamera:gamera"
archive_aomr2="http://bzzt.net/~arnouten/aomr2.tar.gz"
archive_elementtree="http://effbot.org/downloads/elementtree-1.2.6-20050316.tar.gz"
archive_celementtree="http://effbot.org/downloads/cElementTree-1.0.5-20051216.tar.gz"
dest=/usr/local/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration et compilation… >&2
python setup.py build

echo Installation… >&2
sudo python setup.py install --home="$dest"
sudo utiliser $logiciel-$version

echo AOMR2… >&2
obtenirEtAllerDans "$archive_aomr2"
export CPPFLAGS=-I"$dest/include/python2.3/gamera"
python setup.py build
sudo python setup.py install --home="$dest"

echo ElementTree… >&2
obtenirEtAllerDans "$archive_elementtree"
export CPPFLAGS=-I"$dest/include/python2.3/gamera"
python setup.py build
sudo python setup.py install --home="$dest"

echo cElementTree… >&2
obtenirEtAllerDans "$archive_celementtree"
export CPPFLAGS=-I"$dest/include/python2.3/gamera"
python setup.py build
sudo python setup.py install --home="$dest"

sudo utiliser $logiciel-$version

rm -Rf /tmp/$$
