#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 2.26.5 && prerequis="python pkgconfig \\ glib libtiff libjpeg libpng" && modifs="putainDeLibJPEGDeMacOSX" || true
v 2.42.10 && prerequis="python meson ninja pkgconfig \\ glib libtiff libjpeg libpng shared-mime-info gobject-introspection" && modifs="$modifs sansTests" || true
# À partir de glib 2.80, c'est glib elle-même qui fournit GModule-2.0.gir, sous réserve d'avoir l'option +intro
v 2.43.5 && prerequis="$prerequis glycin >= 2" && remplacerPrerequis "glib+intro >= 2.80" && virerPrerequis gobject-introspection && predestiner="$predestiner avecOuSansGlycin" && modifs="$modifs sansDoc" || true
v 2.44.4 || true

# Modifications

avecOuSansGlycin()
{
	optionSi glycin || { virerPrerequis glycin ; OPTIONS_CONF="$OPTIONS_CONF -Dglycin=disabled" ; }
}

sansDoc()
{
	# En 2.43 est ajoutée l'option documentation en true par défaut (revient à false en 2.44).
	# Mais elle requiert docgen qui requiert du git etc.
	OPTIONS_CONF="$OPTIONS_CONF -Ddocumentation=false"
}

sansTests()
{
	# failed to load "/mnt/bdd/tmp/gdk-pixbuf-2.42.10/tests/icc-profile.png": Couldn?t recognize the image file format for file ?/mnt/bdd/tmp/gdk-pixbuf-2.42.10/tests/icc-profile.png?
	# https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234784
	# Est-ce mon install de shared-mime-info? Est-ce mon gdk-pixbuf qui a un support incomplet de PNG?
	
	filtrer meson.build grep -v "subdir('tests')"
}

# Variables

archive="https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/archive/$version/gdk-pixbuf-$version.tar.bz2"

for modif in true $predestiner ; do "$modif" ; done

destiner

prerequis

obtenirEtAllerDansVersion

[ ! -f meson.build ] || parmeson=1

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if [ -n "$parmeson" ]
then
	mkdir -p build
	meson setup build --buildtype=release --prefix="$dest" -Dman=false $OPTIONS_CONF
	cd build
	make=ninja
else
./configure --prefix="$dest"
	make=make
fi

echo Compilation… >&2
$make

echo Installation… >&2
if [ -n "$parmeson" ]
then
	sudokupy $make install
else
sudo make install
fi

sutiliser
