#!/bin/bash
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.bash"

logiciel=ghc

version=6.12.1
modifs=verifierCompat64bit

# Modifications

verifierCompat64bit()
{
	# À FAIRE: comment détecter qu'on est sur de l'x86-64?
	ghcv="`ghc --version | sed -e 's/.* \([0-9.]*\)$/\1/'`"
echo "VERSION $ghcv"
	pge $ghcv 6.12.0 && return 0
	
	cat "`command -v ghc`" | sed -e 's#/ghc #/ghc -optc-m32 -opta-m32 -optl-m32 #' > "$TMP/$$/ghc"
	chmod u+x "$TMP/$$/ghc"
	export PATH="$TMP/$$:$PATH"
	OPTIONS[${#OPTIONS[@]}]="--with-ghc=$TMP/$$/ghc"
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="http://haskell.org/ghc/dist/$version/ghc-$version-src.tar.bz2"

[ -d "$dest" ] && exit 0

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

set -x
echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
#sh boot
./configure --prefix="$dest" "${OPTIONS[@]}"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser $logiciel-$version

rm -Rf "$TMP/$$"
