#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; [ -x "$SCRIPTS" -o ! -x "$0" ] || SCRIPTS="$0" ; case "`basename "$SCRIPTS"`" in *.*) true ;; *sh) SCRIPTS="$1" ;; esac ; case "$SCRIPTS" in /*) ;; *) SCRIPTS="`pwd`/$SCRIPTS" ;; esac ; delie() { while [ -h "$SCRIPTS" ] ; do SCRIPTS2="`readlink "$SCRIPTS"`" ; case "$SCRIPTS2" in /*) SCRIPTS="$SCRIPTS2" ;; *) SCRIPTS="`dirname "$SCRIPTS"`/$SCRIPTS2" ;; esac ; done ; } ; delie ; SCRIPTS="`dirname "$SCRIPTS"`" ; delie
. "$SCRIPTS/util.sh"

logiciel=ghc # On s'installe sous le même chemin qu'un GHC compilé.

# Historique des versions gérées

v 7.10.2 && prerequis="gcc binutils libffi iconv gettext" && modifs="compiloGcc" || true
v 8.2.2 && modifs="compiloGcc unused" || true

# Modifications

compiloGcc()
{
	export CC=gcc CXX=g++
}

# Variables

case `uname` in
	FreeBSD)
		vos="`uname -r | sed -e 's/-.*//'`"
		if pge $version 8 && pge $vos 11
		then
			archive="https://downloads.haskell.org/~ghc/$version/ghc-$version-x86_64-portbld11-freebsd.tar.xz"
		else
			archive="https://downloads.haskell.org/~ghc/$version/ghc-$version-x86_64-portbld-freebsd.tar.xz"
		fi
		;;
	Darwin)
		archive="https://downloads.haskell.org/~ghc/$version/ghc-$version-x86_64-apple-darwin.tar.xz"
		;;
	*) echo "# Pas d'archive binaire connue pour `uname`." >&2 ; exit 1 ;;
esac

unused()
{
	# Pour s'assurer que le compilo accepte telle ou telle option, le configure essaie de compiler avec et chope les alertes "unrecognized compile flag".
	# Problème: pour clang, c'est unused, pas unrecognized.
	# Donc aux yeux du configure, clang mange tout et n'importe quoi.
	filtrer configure sed -e '/grep.*unrecognized/s/ unrecognized / '\''unrecognized\\|unused'\'' /'
}

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
#make

echo Installation… >&2
sudoku make install

sutiliser
