#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 7.10.2 && prerequis="make \\ gcc binutils libffi iconv gettext ncurses" && modifs="compiloGcc" || true
v 8.2.2 && modifs="compiloGcc unused" || true
v 8.10.7 && prerequis="make patchelf \\ ncurses" && modifs="libncurses" || true
v 9.0.2 || true # Et après plus rien pour FreeBSD?
# D'après les ports il existe une 9.2.8 et une 9.4.8, une 9.6.6. Mais ont-elles été publiées?

# On s'installe sous le même chemin qu'un GHC compilé.
#guili_alias="$guili_alias:ghc-$version"
# En fait non on prend carrément le nom ghc, sans quoi ce dernier ne pourra nous écraser:
logiciel=ghc

# Modifications

# À FAIRE: ncurses GuiLI si pas disponible système.
# À FAIRE: sous FreeBSD, libncursesw.so.8 ou .9 est en réalité une .6 (le port s'amuse à incrémenter le num, pourquoi? Changement d'ABI?).

libncurses()
{
	# À FAIRE: rendre ncurses et patchelf optionnels, par ex. en nous relançant en moiré si nous échouons avec le seul système.
	local d radical bonne
	grep -rl libncursesw */*/build */*/*/build | while read f
	do
		ldd "$f" | grep libncursesw | while read biblio reste
		do
			case "$reste" in *"not found"*)
				echo "Embêté par $f avec une référence à $biblio"
				radical="`echo "$biblio" | sed -e 's/[.0-9]*$//'`"
				if [ -z "$bonne" ]
				then
					for d in $INSTALLS/lib /usr/local/lib /usr/lib
					do
						bonne="`cd "$d" && ls $radical.* | sort -r -n -t . -k 3 | head -1`"
						[ -z "$bonne" ] || break
						echo "Trouvé $d/$bonne à la place"
						break
					done
					[ -n "$bonne" ] || exit 1
				fi
				echo "Remplacement $biblio -> $bonne"
				patchelf --replace-needed "$biblio" "$bonne" "$f"
			esac
		done
	done
}

compiloGcc()
{
	export CC=gcc CXX=g++
}

# Variables

case `uname` in
	FreeBSD)
		vos="`uname -r | sed -e 's/-.*//'`"
		if pge $version 8.5
		then
			marchand=unknown
		elif pge $version 8 && pge $vos 11
		then
			marchand=portbld11
		else
			marchand=portbld
		fi
		archive="https://downloads.haskell.org/~ghc/$version/ghc-$version-x86_64-$marchand-freebsd.tar.xz"
		;;
	Darwin)
		archive="https://downloads.haskell.org/~ghc/$version/ghc-$version-x86_64-apple-darwin.tar.xz"
		;;
	*) echo "# Pas d'archive binaire connue pour `uname`." >&2 ; exit 1 ;;
esac

unused()
{
	# Pour s'assurer que le compilo accepte telle ou telle option, le configure essaie de compiler avec et chope les alertes "unrecognized compile flag".
	# Problème: pour clang, c'est unused, pas unrecognized.
	# Donc aux yeux du configure, clang mange tout et n'importe quoi.
	filtrer configure sed -e '/grep.*unrecognized/s/ unrecognized / '\''unrecognized\\|unused'\'' /'
}

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
#make

echo Installation… >&2
sudoku make install

sutiliser
