#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 8.51 && modifs="moinsL bibliosInternes" && prerequis="libpng libtiff+jpeg8 >= 4 libjpeg < 9" || true
v 9.10 || true
v 9.15 || true
v 9.23 && prerequis="libpng libtiff+jpeg9 >= 4 libjpeg >= 9" || true
v 9.52 || true

archive=http://ovh.dl.sourceforge.net/sourceforge/$logiciel/$logiciel-$version.tar.bz2
archive=http://heanet.dl.sourceforge.net/project/ghostscript/GPL%20Ghostscript/$version/ghostscript-$version.tar.bz2
archive=http://downloads.ghostscript.com/public/ghostscript-$version.tar.gz
archive="https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs`echo "$version" | tr -d .`/ghostscript-$version.tar.gz"

# Modifications

moinsL()
{
	# configure vérifie l'utilisabilité de -liconv, en utilisant LDFLAGS (qui contient le -L/usr/local/lib), et ajoute alors -liconv à LIBS… mais sans son -L.
	filtrer configure sed -e '/^[ 	]*LIBS=.*-liconv/s#="#="-L'"$INSTALLS/lib"' #'
}

jpeg8()
{
	# Incompatibilité avec la 9. Il nous faut nous assurer une 8.
	jpeg8="`ls -d "$INSTALLS/libjpeg-"* | grep libjpeg-8 | tail -1`"
	[ -z "$jpeg8" ] && echo "# Une libjpeg 8 (pas 7, pas 9) doit être en place" >&2 && exit 1
	CFLAGS="-I$jpeg8/include $CFLAGS"
	CPPFLAGS="-I$jpeg8/include $CPPFLAGS"
	LDFLAGS="-L$jpeg8/lib $LDFLAGS"
	export CFLAGS LDFLAGS
}

bibliosInternes()
{
	# Ce crétin embarque des biblios complètes, mais il fait passer nos CFLAGS devant, surchargeant donc les susdites et faisant planter la compil qui voit des bouts de l'embarquée, des bouts d'/usr/local.
	preCFlag -I./libpng -I./zlib -I./psi -I./obj -I./base -I./devices
}

# Boulot

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
