#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"
. "$SCRIPTS/garg.sh"

logiciel=git

v 1.7.0.6 && prerequis="perl gettext expat iconv curl" || true
v 1.7.5.4
v 1.7.10.4 && modifs=autoconfer || true
v 1.8.3.2 && modifs=sansConfigurer || true
v 2.9.0 && modifs="lierIconv sansConfigurer sansMoinsR perler" || true
v 2.12.0 || true
v 2.12.2 || true
v 2.15.1 || true
v 2.16.0 || true
v 2.18.0 || true

if option svn
then
	prerequis="$prerequis depsgitsvn"
fi

# Modifications

perler()
{
	# Perl codé en dur.
	perler_perl="$INSTALLS/bin/perl"
	grep -rl /usr/bin/perl . | while read f
	do
		filtrer "$f" sed -e "s#/usr/bin/perl#$perler_perl#"
	done
}

lierIconv()
{
	LDFLAGS="$LDFLAGS -liconv"
}

sansMoinsR()
{
	case `uname` in
		FreeBSD|Linux)
			NO_R_TO_GCC_LINKER=1
			#CC_LD_DYNPATH=-L
			export NO_R_TO_GCC_LINKER #CC_LD_DYNPATH
			;;
	esac
}

autoconfer()
{
	make configure
}

sansConfigurer()
{
	sansConfigure=1
	# L'invocation du make install doit être strictement la même que celle du make, sans quoi il détecte un changement d'environnement et retente toute la compil' (en root). Or comme on passe par sudo pour le make install, et que celui-ci dézingue l'environnement, on doit s'assurer que les variables passées au make traversent aussi le sudo make install. Le plus simple est de les ajouter aux paramètres des deux.
	garg -a paramsMake prefix="$dest" OPENSSLDIR="$INSTALLS" LDFLAGS="$LDFLAGS" CPPFLAGS="$CPPFLAGS" CFLAGS="$CFLAGS"
}

# Variables

archive="http://kernel.org/pub/software/scm/git/git-$version.tar.bz2"
archive="https://github.com/git/git/tarball/v$version?name=/git-$version.tar.gz"

dest="$INSTALLS/$logiciel-$version"

[ -d "$dest" ] && exit 0

prerequis

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if [ -z "$sansConfigure" ]
then
./configure --prefix="$dest"
fi

echo Compilation… >&2
garg paramsMake make

echo Installation… >&2
garg -a paramsMake install
garg paramsMake sudo NO_R_TO_GCC_LINKER=$NO_R_TO_GCC_LINKER make
sutiliser $logiciel-$version

rm -Rf "$TMP/$$"
