#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

prerequis="make \\"
v 1.5.7 && modifs="bsdAveugle" || true
v 1.6.0 || true
v 1.12.0 && prerequis="$prerequis mesa" || true # En fait mesa+osmesa, mais osmesa y est compilé par défaut dans les GuiLI.
v 1.13.0 || true
v 2.0.0 && modifs="bsdAveugle2 glewnoglu" || true

destiner

prerequis

archive="http://freefr.dl.sourceforge.net/project/$logiciel/$logiciel/$version/$logiciel-$version.tgz"

glewnoglu()
{
	# Étrange… On voit partout défini du -DGLEW_NO_GLU par défaut, par contre en tête de Makefile le if semble foireux, s'attendant à ce que le -DGLEW_NO_GLU soit défini explicitement (donc non pas par défaut, en contradiction avec les forçages précédemment mentionnés).
	filtrer Makefile sed -e '/LIBGLU *=/s#=.*#=#'
}

pre32()
{
	if command -v arch 2> /dev/null
	then
		arch -arch x86_64 true 2> /dev/null && filtrer Makefile sed -e '/^LIB.LDFLAGS =/s/$/ -arch x86_64 -arch i386/' -e '/^CFLAGS =/s/$/ -arch x86_64 -arch i386/' -e '/STRIP/d'
	fi
}

dyld105()
{
	filtrer Makefile sed -e '/^LIB.LDFLAGS =/s/$/ -mmacosx-version-min=10.5/'
}

bsdAveugle2()
{
	filtrer config/Makefile.freebsd sed -e 's#-L/usr/X11R6/lib##g' -e 's#-lX11##g' -e 's#-lGL#-lOSMesa#g' -e 's#-I/usr/X11R6/include##g'
	echo "CFLAGS.EXTRA += -DGLEW_OSMESA $CPPFLAGS $CFLAGS" >> config/Makefile.freebsd
	echo "LDFLAGS.EXTRA += $LDFLAGS" >> config/Makefile.freebsd
}

bsdAveugle()
{
	case `uname` in
		FreeBSD)
			if false
			then
				for i in auto/src/glxew_head.h include/GL/glxew.h
				do
					filtrer "$i" grep -v '#include <X11'
				done
			else
				grep -rl '#[ 	]*include.*glxew.h' . | while read i
				do
					filtrer "$i" grep -v '#[ 	]*include.*glxew.h'
				done
			fi
			;;
	esac
}

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif "$@" ; done

echo Compilation… >&2
make
for modif in true $modifspostcompil ; do $modif "$@" ; done

echo Installation… >&2
sudo make GLEW_DEST="$dest" install

sutiliser
