#!/bin/bash
# Copyright (c) 2004-2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

logiciel=glib

v 2.2.3 && prerequis="gettext" || true
v 2.6.5 || true
v 2.12.12 && modifs="micMacGnuIconv pasBesoinDeCarbon" || true
v 2.22.5 || true
v 2.34.3 && modifs=pasBesoinDeCarbon && prerequis="gettext libffi >= 3" || true
v 2.36.4 || true
v 2.38.1 || true
v 2.40.0 && modifs="pasBesoinDeCarbon sansDtrace" || true

prerequis

archive="ftp://ftp.gtk.org/pub/gtk/v`vmaj $version`/$logiciel-$version.tar.bz2"
pge $version 2.12.12 && archive="ftp://ftp.gtk.org/pub/$logiciel/`vmaj $version`/$logiciel-$version.tar.bz2"
pge $version 2.34.3 && archive="http://ftp.acc.umu.se/pub/GNOME/sources/$logiciel/`vmaj $version`/$logiciel-$version.tar.xz"

dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

# Le machin vérifie que biblio et iconv.h sont bien d'accord, soit tout GNU iconv, soit tout système. Problème: sur Darwin, on a un hybride. En plus on s'en fout, parce que l'ifdef n'est utilisé nulle part ailleurs.
micMacGnuIconv()
{
	filtrer glib/gconvert.c grep -v 'error GNU libiconv'
}

pasBesoinDeCarbon()
{
	# N'a pas vraiment besoin de Carbon, qui nous gonfle
	filtrer configure sed -e '/framework.Carbon/s/^/true #/'
}

sansDtrace()
{
	# La 2.40 a du code dtrace, mais sur mon FreeBSD 8.2, ça ne compile pas vraiment.
	optionsConfigure="$optionsConfigure --disable-dtrace"
}

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" $optionsConfigure

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
