#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

prerequis="make pkgconfig \\ expat zlib"
v 2.38.0 && modifs="sfFlags gnu89 sansps2pdf" || true
v 2.40.1 || true
v 2.44.0 || true
v 2.44.1 || true
v 7.1.0 && prerequis="autoconf automake m4 libtool bison python >= 3 \\ $prerequis" || true

# À FAIRE: ne trouve pas gdk, gdk_pixbuf, gtk, pangocairo, webp, gv_php, gv_python3: les passer en optionSi?

optionSi rsvg || true
optionSi gd || true
optionSi fontconfig || true

# Modifications

sansps2pdf()
{
	# Mais on s'en fout d'avoir le manuel en PDF!
	# Et en plus pour ça ils te codent en dur un ps2pdf qui en cas d'absence vautre tout le make.
	# https://github.com/Homebrew/homebrew-core/pull/57132, https://github.com/vvulpes0/homebrew-vv/blob/master/Formula/graphviz.rb
	grep -rl '\(EXTRA_DIST\|DATA\).*pdf' . | while read f
	do
		filtrer "$f" sed -E \
			-e '/^(DATA|EXTRA_DIST) *=/s/\$\(pdf_DATA\)//g' \
			-e '/install-data-am:/s/install-pdfDATA//g'
	done
}

sfFlags()
{
	# https://svnweb.freebsd.org/ports/head/devel/sfio/Makefile?r1=406084&r2=406083&pathrev=406084
	if [ `uname` = FreeBSD -a `uname -r | cut -d . -f 1` -ge 11 ]
	then
		for i in lib/sfio/*.[ch]
		do
			filtrer "$i" sed -e 's|SF_FLAGS|SFIO_FLAGS|g'
		done
	fi
}

gnu89()
{
	# https://gitlab.com/graphviz/graphviz/issues/1365
	case "$CC" in
		gcc*) export CFLAGS="$CFLAGS -std=gnu89" ;;
	esac
}

# Variables

archive="http://www.graphviz.org/pub/graphviz/stable/SOURCES/graphviz-$version.tar.gz"
archive="https://www2.graphviz.org/Packages/stable/portable_source/graphviz-$version.tar.gz"
archive="https://gitlab.com/graphviz/graphviz/-/archive/$version/graphviz-$version.tar.gz"

if opSiPasPas pdf poppler+glib
then
	prerequis="$prerequis pango"
fi

prerequis

destiner

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
[ -f configure ] || ./autogen.sh
./configure --prefix="$dest" --enable-perl=no --enable-python=no --without-x

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
