#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal

# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

inclure glib
inclure libjpeg
inclure libpng
inclure libtiff

logiciel=gtk+

v 2.6.8 && v_atk=">= 1.9" && v_pango=">= 0"|| true
v 2.24.13 && modifs="putainDeLibJPEGDeMacOSX" && v_atk=">= 2.5.3" && v_gdk_pixbuf=">= 2.26" && v_pango=">= 1.20 < 1.30" || true
v 3.6.2 && modifs="putainDeLibJPEGDeMacOSX" && v_atk=">= 2.5.3" && v_gdk_pixbuf=">= 2.26" && v_pango="> 1.30" || true

mac && optionsConf="--enable-quartz-backend --disable-x11-backend" || true

[ -z "$v_atk" ] || inclure atk "$v_atk"
[ -z "$v_pango" ] || inclure pango "$v_pango"
[ -z "$v_gdk_pixbuf" ] || inclure gdk-pixbuf "$v_gdk_pixbuf"

archive=ftp://ftp.gtk.org/pub/gtk/v`vmaj $version`/$logiciel-$version.tar.bz2
pge $version 2.11 && archive=ftp://ftp.gtk.org/pub/gtk/`vmaj $version`/gtk+-$version.tar.bz2 || true
pge $version 2.20 && archive=http://ftp.gnome.org/pub/gnome/sources/gtk+/`vmaj $version`/gtk+-$version.tar.xz || true

dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" $optionsConf  # Attention à ce que le LDFLAGS soit bien défini: sans, -L/usr/X11R6/lib passe en premier, avec une fontconfig obsolète et incompatible avec celle d'/usr/local (FcObjectStaticName pas utilisée, donc les comparaisons de chaînes merdent).

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
