#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

logiciel=gtkmm

# Historique des versions gérées

v 2.6.3 && v_glibmm=">= 2.6" || true
v 2.24.2 && v_glibmm=">= 2.28 < 2.35" && v_gtk="< 2.80" || true
v 3.0.1 && v_glibmm=">= 2.28" || true
v 3.6.0 && v_glibmm=">= 2.34" && v_pangomm=">= 2.27.1" && v_gtk=">= 3.6" && v_cairomm=">= 1.9.2" && v_gdk_pixbuf=">= 2.22.1" && v_atkmm=">= 2.22.2" || true

# Modifications

# Variables

[ -z "$v_gtk" ] || inclure gtk+ "$v_gtk"
[ -z "$v_glibmm" ] || inclure glibmm "$v_glibmm"
[ -z "$v_pangomm" ] || inclure pangomm "$v_pangomm"
[ -z "$v_cairomm" ] || inclure cairomm "$v_cairomm"
[ -z "$v_gdk_pixbuf" ] || inclure gdk-pixbuf "$v_gdk_pixbuf"
[ -z "$v_atkmm" ] || inclure atkmm "$v_atkmm"

dest="$INSTALLS/$logiciel-$version"
archive=http://ftp.gnome.org/pub/GNOME/sources/$logiciel/`vmaj $version`/$logiciel-$version.tar.bz2
pge $version 3.1 && archive=http://ftp.gnome.org/pub/gnome/sources/$logiciel/`vmaj $version`/$logiciel-$version.tar.xz || true

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" --disable-examples --disable-demos

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
