#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delictueux() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delictueux ; s="`dirname "$s"`" ; Delictueux ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

OPTIONS_CONF=

modifs="multiarch moiDAbord"
v 0.9.29 && prerequis="icu graphite" || true
v 0.9.37 || true
v 1.3.2 || true
v 2.3.1 && ft_v=">= 2.8" prerequis="pkgconfig make \\ gettext icu graphite >= 1.2 freetype+hb $ft_v" || true
v 2.6.7 || true
v 2.9.1 && prerequis="autoconf automake m4 libtool \\ $prerequis" && modifs="autoc $modifs" || true
v 3.4.0 || true
v 4.4.1 || true
v 5.3.1 || true
v 7.3.0 || true
v 8.3.1 || true
v 8.5.0 || true
# À partir de la 9 on passe sur du cmake ou meson.
v 9.0.0 && prerequis="python ninja meson \\ gettext icu graphite >= 1.2 freetype+hb $ft_v" || true
v 10.4.0 || true
v 11.5.1 || true
v 12.3.0 || true

# Modifications

optionsEtPrerequisIcu
optionSi glib || true
case ":$GUILI_PILE" in *:cairo:*) argOptions="`options $argOptions-cairo`" ;; esac
# À FAIRE: imposer un cairo avec un freetype d'une version. À l'heure actuelle si on a un cairo+ft-2.7 et un ft-2.9, c'est le ft du cairo qui apparaît en 1er dans le chemin (dép de dép) et donc le configure dit que ft < 2.x pas suffisant => échec. Même si on remettait dans l'ordre il faudrait trouver moyen de demander un cairo avec la même version. C'était le but de la commande ecosysteme, jamais menée à bout. Pour l'heure le seul moyen est de supprimer le cairo et de le recompiler au goût du jour.
optionSi cairo || OPTIONS_CONF="$OPTIONS_CONF --without-cairo"
optionSi fc/fontconfig || OPTIONS_CONF="$OPTIONS_CONF --without-fontconfig"
optionSi graphite && OPTIONS_CONF="$OPTIONS_CONF --with-graphite2" || OPTIONS_CONF="$OPTIONS_CONF --without-graphite2"
# Pour ce qui est du freetype, finalement on ne le prérequiert que s'il est déjà installé dans la version voulue (par exemple itération 0 d'un freetype+hb).
# https://github.com/harfbuzz/harfbuzz/issues/2524
# Ce après l'optionsEtPrerequisIcu() afin qu'il ait toutes ses options (ICU) d'étiquetées.
optionSi ft/freetype || true
optionSi png/libpng || true
pftv="`decoupePrerequis "$prerequis" | grep ^freetype`"
if [ -z "$pftv" ] || versions -lp -li "$pftv" | grep -q .
then
	true
else
	virerPrerequis "`for l in $pftv ; do echo "$l" ; break ; done`"
	argOptions="`options "$argOptions-ft"`"
fi

configure=./configure
autoc()
{
	if [ -f meson.build ]
	then
		mkdir -p build
		parMeson()
		{
			OPTIONS_CONF="`echo " $OPTIONS_CONF" | sed -E -e 's#--with-([^ ]*)#-D\1=enabled#g' -e 's#--without-([^ ]*)#-D\1=disabled#g'`"
			meson setup build --buildtype=release --prefix="$dest" $OPTIONS_CONF
			cd build
		}
		configure=parMeson
		make=ninja
		maki="sudoku ninja install"
		return 0
	fi
	
	make=make
	maki=sudoku make install
	[ -f configure ] || { filtrer autogen.sh sed -e 's/which/command -v/g' && configure=./autogen.sh ; }
}

moiDAbord()
{
	# Comme harfbuzz dépend de freetype qui dépend d'harfbuzz, on peut se retrouver avec une version plus ancienne de nous-mêmes dans nos prérequis.
	# Il serait malencontreux que ses biblios soient alors utilisées pour le lien de nos exécutables, qui n'y trouveraient pas leurs symboles en dernière version.
	# On introduit donc le dossier de compil' en premier dans les chemins de liens.
	export LDFLAGS="-Lsrc $LDFLAGS"
}

# Variables

archive="https://github.com/harfbuzz/harfbuzz/archive/refs/tags/$version.tar.gz"
pge $version 2.7 || \
archive="http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-$version.tar.xz"
pge $version 2.5.0 || archive="`echo $archive | sed -e s/xz/bz2`"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
$configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
$make

echo Installation… >&2
$maki

sutiliser
