#!/bin/bash
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

logiciel=haxe

# Historique des versions gérées

version=2006-12-26
modifs=
OPTIONS_CONF=()

version=2008-06-13
modifs="libz"
OPTIONS_CONF=()

version=r3211
vdate=2010.04.25
modifs="libz"
OPTIONS_CONF=()

version=r3353
vdate=2010.08.14 # Correspond à la 2.06
modifs="libz interp"
OPTIONS_CONF=()

version=r4847
vdate=2012.06.11 # Correspond à la 2.09+
modifs="libz"
OPTIONS_CONF=()

# Modifications

pge $vdate 2010 || inclure neko

libz()
{
	filtrer doc/install.ml sed -e '/List.find.*libz/s#\]#;"/usr/lib/libz.so"]#'
}

interp()
{
	# Ces couillons ne se sont pas rendu compte d'une dépendance de main envers interp.
	filtrer doc/install.ml sed -e 's/"interp";"//' -e 's/"main"/"interp";"main"/'
}

# Variables

archive="$logiciel-$version.tar.bz2"
archive_cvs="cvs://anonymous@cvs.motion-twin.com:/cvsroot:$logiciel"
archive_svn="http://haxe.googlecode.com/svn/trunk"
dest="$INSTALLS/$logiciel-$version"

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Compilation… >&2
echo | ocaml doc/install.ml # Un mot-de-passe CVS à taper.

echo Installation… >&2
sudo sh -c "mkdir -p '$dest/bin' '$dest/lib/haxe' && cp 'bin/$logiciel' '$dest/bin/' && cp -R 'std' '$dest/lib/haxe/'"
sutiliser $logiciel-$version

rm -Rf "$TMP/$$"
