#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; }
calcScripts() { absolutiseScripts "`command -v "$1"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`" ; }
calcScripts "$0"
. "$SCRIPTS/util.sh"

logiciel=hummus

v 3.0.0.99.1.c79134f39cb68dbcbb08648047d12f3324c3d2db.git && prerequis="libtiff 3.9.4 libjpeg 8.3 freetype zlib" || true # Il faudrait un moyen pour que le numéro de version de libjpeg soit calculé depuis le libjpeg embarqué par le libtiff choisi.

archive_git=http://github.com/galkahana/PDF-Writer.git

v_simple="`echo "$version" | sed -e 's/[.][^.]*.git$//'`"
dest=$INSTALLS/$logiciel-$v_simple

[ -d "$dest" ] && exit 0

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
# Le système en cmake ne fait que de la biblio statique, et n'exploite pas nos biblios partagées.
#mkdir Build
#cd Build
#cmake ..
cd PDFWriter
cat > Makefile <<TERMINE
sources := \$(shell find . -name \\*.cpp)
objs := \$(sources:.cpp=.o)

libhummus.so: \${objs}
	c++ -shared -fpic $LDFLAGS -ltiff -ljpeg -lfreetype -lz \$^ -o \$@

%.o: %.cpp
	c++ -c -fpic -I$INSTALLS/include/freetype2 $CPPFLAGS \$< -o \$@
TERMINE

echo Compilation… >&2
make

echo Installation… >&2
sudo mkdir -p "$dest/include/Hummus" "$dest/lib"
sudo cp libhummus.so "$dest/lib/"
sudo cp *.h "$dest/include/Hummus/"
sutiliser "$logiciel-$v_simple"

rm -Rf $TMP/$$
