#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 1.14 && modifs="fbsd10" || true
v 1.15 || true
v 1.16 || true

# Sur mac l'option duo est fortement préconisée (cf. note de lesdeux()).
mac && argOptions="`options "$argOptions=duo"`" || true
if option duo ; then modifs="$modifs lesdeux" ; fi

# Modifications

lesdeux()
{
	# libiconv peut se compiler soit façon système (iconv()), soit façon biblio additionnelle (libiconv(), pour ne pas écraser l'iconv() système).
	# Problème: quand un logiciel (au hasard Python), embarquant des liens avec à la fois des biblios Open Source (habituées à libiconv()) et des biblios système (habituées à iconv()), une seule libiconv.so est chargée par le ld: à elle donc de définir les deux.
	# … Mais pas pour FreeBSD, qui utilise cela en standard.
	# … Mais avec des strong_alias, non supportés par tout le monde (ex.: Darwin, qui dit qu'il "only support weak aliases, mais en fait même pas).
	# Donc on en revient à la bonne vieille méthode de l'appel direct.
	
	cat >> lib/iconv.c <<TERMINE
#if !defined(LIBICONV_PLUG) && !defined(__FreeBSD__)

#if 0
#undef iconvlist
#undef iconvctl
#endif
#undef iconv
#undef iconv_open
#undef iconv_close

#if 0
extern LIBICONV_DLL_EXPORTED int iconvctl (iconv_t icd, int request, void* argument) { return libiconvctl(icd, request, argument); }
extern LIBICONV_DLL_EXPORTED void iconvlist (int (*do_one) (unsigned int namescount, const char * const * names, void* data), void* data) { libiconvlist(do_one, data); }
#endif
extern LIBICONV_DLL_EXPORTED iconv_t iconv_open (const char* tocode, const char* fromcode) { return libiconv_open(tocode, fromcode); }
extern LIBICONV_DLL_EXPORTED size_t iconv (iconv_t icd, ICONV_CONST char* * inbuf, size_t *inbytesleft, char* * outbuf, size_t *outbytesleft) { return libiconv(icd, inbuf, inbytesleft, outbuf, outbytesleft); }
extern LIBICONV_DLL_EXPORTED int iconv_close (iconv_t icd) { return libiconv_close(icd); }

#endif
TERMINE
}

# Variables

archive="http://ftp.gnu.org/pub/gnu/libiconv/libiconv-$version.tar.gz"

prerequis

destiner

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
# Le .la, c'est bien gentil, mais ça ne vaut pas un .so qui pointe vers le .so.x.x.
( cd "$dest/lib" && for i in lib*.so.* ; do lib="`echo "$i" | sed -e 's/\.so\..*/.so/'`" ; [ -e "$lib" ] || sudo ln -s "$i" "$lib" ; done )
pkgconfer iconv

sutiliser
