#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

prerequis="libjpeg libtiff libpng freetype" 

logiciel_maj=ImageMagick
logiciel="`echo $logiciel_maj | tr '[A-Z]' '[a-z]'`"

v 6.2.4.4 || true
v 6.2.5.5 || true
v 6.6.3.0 || true
v 6.6.7.7 || true
v 6.7.3.0 || true
v 6.7.5.6 && modifs=putainDeLibJPEGDeMacOSX || true
v 6.8.3.3 || true
v 6.8.7.3 && modifs= && prerequis="$prerequis cairo pango" || true
v 6.8.8.1 || true
# N.B.: peut utiliser rsvg pour traiter le SVG.
v 6.9.0.2 || true
v 6.9.0.4 && prerequis="libjpegturbo libtiff libpng freetype cairo pango zlib" || true
v 7.0.2.7 || true
v 7.0.3.4 || true
v 7.0.7.11 || true

prerequis

version_min="`echo "$version" | sed -e 's/\.\([^.]*\)$/-\1/'`"
dest="$INSTALLS/$logiciel-$version"
archive=ftp://gd.tuwien.ac.at/pub/graphics/$logiciel_maj/$logiciel_maj-$version_min.tar.bz2
archive=http://mirror.checkdomain.de/imagemagick/$logiciel_maj-$version_min.tar.bz2

[ -d "$dest" ] && exit 0

obtenirEtAllerDans "$archive"

for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
