#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Besoin de GNU make, sans quoi tout se passe bien jusqu'à "don't know how to make MagickCore/ImageMagick-7.Q16HDRI.pc. Stop".
prerequis="langcxx() make pkgconfig \\ glib libjpeg libtiff libpng freetype fontconfig cairo pango zlib"

logiciel_maj=ImageMagick

v 6.2.4.4 || true
v 6.2.5.5 || true
v 6.6.3.0 || true
v 6.6.7.7 || true
v 6.7.3.0 || true
v 6.7.5.6 && modifs=putainDeLibJPEGDeMacOSX || true
v 6.8.3.3 || true
v 6.8.7.3 && modifs= || true
v 6.8.8.1 || true
v 6.8.9.10 || true
# N.B.: peut utiliser rsvg pour traiter le SVG.
v 6.9.0.2 && prerequis="$prerequis librsvg" || true
v 6.9.0.4 || true
v 6.9.13.25 || true
v 7.0.2.7 && modifs="$modifs rawpict scaledpict" || true
v 7.0.3.4 || true
v 7.0.6.1 || true
v 7.0.7.11 || true
v 7.0.8.59 || true
v 7.0.8.68 || true
v 7.0.9.17 || true
v 7.1.0.57 || true
v 7.1.1.47 || true
v 7.1.2.3 || true

rawpict()
{
	# https://github.com/ImageMagick/ImageMagick/issues/8381
	patch -p1 < "`obtenir https://github.com/ImageMagick/ImageMagick/commit/4fe745c511565748c9fd89940e7d3f4020dedd97.diff`"
}

scaledpict()
{
	# https://github.com/ImageMagick/ImageMagick/issues/8384
	patch -p1 < "`obtenir https://github.com/ImageMagick/ImageMagick/commit/9f1ca3f94a2632fcdab57d35036c0f855dfb0a8a.diff`"
}

# À FAIRE: une option omp (OpenMP) qui ne s'active que si notre clang GuiLI a été compilé avec l'option correspondante. Sans quoi ImageMagick tente de se lier à la /usr/lib/libomp.so, incompatible avec le clang GuiLI bien plus récent. Notamment __kmpc_dispatch_deinit est introuvable (symbole publié par les .h mais absent d'/usr/lib/libomp.so).

if versions libjpegturbo | grep -q .
then
	prerequis="`echo "$prerequis" | sed -e 's/libjpeg /libjpegturbo /' -e 's/libtiff /libtiff+jpegturbo /'`"
fi
optionSi libxml || true
optionSi zstd || true
#optionSi zip || true
#optionSi 7z || true
optionSi libzip || true
optionSi xz || true # Pour l'option LZMA ImageMagick.
optionSi graphviz || true
optionSi lcms || true

argOptions="`options "$argOptions=svg"`"
option svg && optionsConf="$optionsConf --with-rsvg=yes" || virerPrerequis librsvg

version_min="`echo "$version" | sed -e 's/\.\([^.]*\)$/-\1/'`"
archive=ftp://gd.tuwien.ac.at/pub/graphics/$logiciel_maj/$logiciel_maj-$version_min.tar.bz2
archive=http://mirror.checkdomain.de/imagemagick/releases/$logiciel_maj-$version_min.tar.xz

destiner

prerequis

obtenirEtAllerDansVersion

for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" $optionsConf

echo Compilation… >&2
make -j4

echo Installation… >&2
sudo make install

sutiliser
