#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; }
calcScripts() { absolutiseScripts "`command -v "$1"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`" ; }
calcScripts "$0"
. "$SCRIPTS/util.bash"

inclure glib

logiciel=inkscape

v 0.41 && modifs="xmlparser finite" && v_gtkmm=">= 0" && v_gtk=">= 0" && v_libxml=">= 0" && v_libxslt=">= 0" && v_sigcpp=">= 0" && v_gc=">= 0" && v_popt=">= 0" || true
v 0.48.2 && modifs="putainDeLibJPEGDeMacOSX" && v_intltool=">= 0.22" && v_littlecms="< 2" && v_glibmm=">= 2.4" && v_gtkmm=">= 2.10 < 2.80" && v_gtk=">= 2" && v_libxml=">= 2.6.11" && v_libxslt=">= 1.0.15" && v_cairo=">= 0" && v_sigcpp=">= 2.0.12" && v_libpng=">= 1.2" && v_gsl=">= 0" && v_gc= && v_popt= || true

[ -z "$v_intltool" ] || inclure intltool "$v_intltool"
[ -z "$v_glibmm" ] || inclure glibmm "$v_glibmm"
[ -z "$v_gtkmm" ] || inclure gtkmm "$v_gtkmm"
[ -z "$v_gtk" ] || inclure gtk+ "$v_gtk"
[ -z "$v_libxml" ] || inclure libxml "$v_libxml"
[ -z "$v_libxslt" ] || inclure libxslt "$v_libxslt"
[ -z "$v_cairo" ] || inclure cairo "$v_cairo"
[ -z "$v_sigcpp" ] || inclure sigc++ "$v_sigcpp"
[ -z "$v_libpng" ] || inclure libpng "$v_libpng"
[ -z "$v_gsl" ] || inclure gsl "$v_gsl"
[ -z "$v_popt" ] || inclure libpopt "$v_popt"
[ -z "$v_gc" ] || inclure gc "$v_gc"

archive=http://switch.dl.sourceforge.net/project/inkscape/inkscape/$version/inkscape-$version.tar.gz

xmlparser()
{
	if perl -mXML::Parser < /dev/null 2> /dev/null
	then
		true
	else
		pushd /tmp/
		obtenirEtAllerDans http://search.cpan.org/CPAN/authors/id/M/MS/MSERGEANT/XML-Parser-2.34.tar.gz
		cd /tmp/
		tar xzf /Users/installs/XML-Parser-2.34.tar.gz
		cd XML-Parser-2.34
		perl Makefile.PL
		make
		sudo make install
		popd
	fi
}

finite()
{
	# std::isfinite n'est définie par cmath que si _GLIBCPP_USE_C99, mais cette
	# macro fout le bazar (CXXFLAGS=-D_GLIBCPP_USE_C99=1 ./configure…).
	filtrer src/object-edit.cpp sed -e 's/std::isfinite/finite/'
}

# Variables

dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if 0 # mac
then
	cd packaging/macosx
	#./osx-build.sh a
	./osx-build.sh c
	./osx-build.sh b
	sudo ./osx-build.sh i
else
	mac && optionsConf="--enable-osxapp" || true
	./configure --prefix="$dest" $optionsConf
fi

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
