#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 0.41 && modifs="finite" && prerequis="glib gtkmm gtk libxml libxslt libsigcxx gc popt" || true
v 0.48.2 && modifs="putainDeLibJPEGDeMacOSX" && prerequis="glib intltool >= 0.22 littlecms < 2 glibmm >= 2.4 gtkmm >= 2.10 < 2.80 gtk >= 2 libxml >= 2.6.11 libxslt >= 1.0.15 cairo libsigcxx >= 2.0.12 libpng >= 1.2 gsl gc popt" || true

archive=http://switch.dl.sourceforge.net/project/inkscape/inkscape/$version/inkscape-$version.tar.gz
archive=https://media.inkscape.org/dl/resources/file/inkscape-$version.tar.bz2

finite()
{
	# std::isfinite n'est définie par cmath que si _GLIBCPP_USE_C99, mais cette
	# macro fout le bazar (CXXFLAGS=-D_GLIBCPP_USE_C99=1 ./configure…).
	filtrer src/object-edit.cpp sed -e 's/std::isfinite/finite/'
}

# Variables

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if 0 # mac
then
	cd packaging/macosx
	#./osx-build.sh a
	./osx-build.sh c
	./osx-build.sh b
	sudo ./osx-build.sh i
else
	mac && optionsConf="--enable-osxapp" || true
	./configure --prefix="$dest" $optionsConf --with-perl --with-python
fi

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
