#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

while [ $# -gt 0 ]
do
	case "$1" in
		*)
			for i in domaine dest
			do
				eval test -z \$$i && eval $i="$1" && break
			done
			;;
	esac
	shift
done

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi <domaine à gérer> <répertoire destination>
TERMINE
	exit 1
}

[ -z "$domaine" -o -z "$dest" ] && auSecours
echo "$dest" | grep -q ^/ || dest="`pwd`/$dest"

v 0.9.1 && petitnom=nemesis && vbis=alpha-1 || true
v 0.9.3 && vbis=alpha-3 || true
v 1.1.2 && petitnom=primo && vbis= || true

archive="http://download.jappix.org/jappixorg/jappix-$version-$petitnom-$vbis.zip"
archive="https://download.jappix.org/$version/jappix-$version-$petitnom.zip"

mkdir -p "$dest"

(
( obtenirEtAllerDansVersion && tar cf - . || echo "BOUH $?" >&3 ) | ( cd "$dest" && tar xf - )
) 3>&1 | ! grep -q BOUH

cd "$dest"

if ! pge $version 1
then
patch -p0 <<TERMINE
--- ./css/pageengine.css	2013-02-07 10:10:57.000000000 +0100
+++ ./css/pageengine.css	2013-02-07 10:13:43.000000000 +0100
@@ -133,6 +133,14 @@
 	display: none;
 }
 
+#page-engine .chat .top {
+	display: none;
+}
+
+#page-engine .chat .content {
+	top: 2px;
+}
+
 #page-engine .chat .content,
 #page-engine .chat .list {
 	bottom: 93px;
TERMINE
fi

dossiers=". conf access avatars cache backgrounds logos logs music send share updates"
(
cd store
mkdir -p $dossiers
chown `id -u`:www $dossiers
chmod g+rwx $dossiers
for i in $dossiers
do
	cat > $i/index.html <<TERMINE
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Jappix - Forbidden</title>
</head>

<body>
	<h1>Forbidden</h1>
	<h4>This is a private folder</h4>
</body>

</html>
TERMINE
done
)

cat > store/conf/hosts.xml <<TERMINE
<?xml version="1.0" encoding="utf-8" ?>
<jappix xmlns="jappix:conf:hosts">
	<main>$domaine</main>
	<muc>muc.$domaine</muc>
	<pubsub>pubsub.$domaine</pubsub>
	<vjud>vjud.$domaine</vjud>
	<anonymous>anonymous.$domaine</anonymous>
	<bosh>http://$domaine:5280/http-bind</bosh>
	<bosh_main></bosh_main>
	<bosh_mini></bosh_mini>
	<static></static>
	<upload></upload>
</jappix>
TERMINE
cat > store/conf/installed.xml <<TERMINE
<?xml version="1.0" encoding="utf-8" ?>
<jappix xmlns="jappix:conf:installed">
	<installed>true</installed>
</jappix>
TERMINE
cat > store/conf/main.xml <<TERMINE
<?xml version="1.0" encoding="utf-8" ?>
<jappix xmlns="jappix:conf:main">
	<name>$domaine</name>
	<desc>Messagerie instantanée</desc>
	<owner_name></owner_name>
	<owner_website></owner_website>
	<legal></legal>
	<resource>Jappix</resource>
	<lock>on</lock>
	<anonymous>off</anonymous>
	<http_auth>off</http_auth>
	<registration>off</registration>
	<bosh_proxy>on</bosh_proxy>
	<manager_link>off</manager_link>
	<groupchats_join></groupchats_join>
	<encryption>on</encryption>
	<https_storage>off</https_storage>
	<https_force>off</https_force>
	<compression>on</compression>
	<multi_files>off</multi_files>
	<developer>off</developer>
	<statistics>on</statistics>
</jappix>
TERMINE
