#!/bin/bash
# Copyright (c) 2004-2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

logiciel=lesstif

# Historique des versions gérées

version=0.93.95b
modifs="sansBinTrue sansBacktrace sansBiblios"

version=0.94.4
modifs=

dest=/usr/local/$logiciel-$version
archive=http://ovh.dl.sourceforge.net/sourceforge/$logiciel/$logiciel-$version.tar.bz2

# Modifications

sansBinTrue()
{
	filtrer configure sed -e 's:/bin/true:true:'
}

sansBacktrace()
{
	for v in "" -2.1 ; do
		( cd lib/Xm$v && patch -p0 << TERMINE
--- ./DebugUtil.c	Wed Aug 18 17:08:49 2004
+++ ./DebugUtil.c	Mon Aug 30 14:26:15 2004
@@ -2495,6 +2495,9 @@
 #endif
 }
 
+int backtrace(void ** trace, int maxSize) { return 0; }
+char ** backtrace_symbols(void ** trace, int size) { return NULL; }
+
 extern void
 _LtDebugPrintStackTrace()
 {
TERMINE
	)
	done
}

sansBiblios()
{
	filtrer lib/Mrm-2.1/Makefile sed -e '/^LIBS =/c\
LIBS = -lX11 -lXt
'
}

# Boulot

[ -d "$dest" ] && exit 0

if [[ $version = *-* ]] ; then
	obtenirEtAllerDansCvs -d $version $archive_cvs
else
	obtenirEtAllerDans "$archive"
fi

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix=$dest --enable-production

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sudo mkdir -p $dest/docs
sudo mv $dest/LessTif $dest/docs/lesstif
sutiliser "$logiciel-$version"

rm -Rf /tmp/$$
