#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

prerequis="readline expat gettext openssl"
modifs="concatCpp cmdUnsigned"
v 3.0.6 || true
v 3.3.0 || true
v 3.5.4 || true
v 3.7.3 || true
v 3.7.15 || true

# Modifications

cmdUnsigned()
{
	filtrer src/ftpclass.cc sed -e 's#static const char pre_cmd#static const unsigned char pre_cmd#'
}

concatCpp()
{
	# clang++ nous fait remarquer qu'en C++11 on aère un peu les concaténations préprocesseur.
	filtrer src/module.cc sed -e 's#PKGLIBDIR"/"VERSION":"PKGLIBDIR#PKGLIBDIR "/" VERSION ":" PKGLIBDIR#g'
	filtrer src/resource.cc sed -e 's#PACKAGE"/"VERSION#PACKAGE "/" VERSION#g'
}

# Variables

archive="http://lftp.yar.ru/ftp/lftp-$version.tar.bz2"
pge $version 4.6.0 || archive="http://lftp.yar.ru/ftp/old/lftp-$version.tar.bz2"

case "$argOptions+" in
	*-ossl[-+]*) virerPrerequis openssl ;;
	*) prerequisOpenssl ; OPTIONS_CONF="--without-gnutls --with-openssl" ;;
esac

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser
