#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 2025.8.26 && versionComplete="$version.14b7fcd.git" || true

archive_git=https://github.com/BrianGladman/aes.git

configurer()
{
	# Le système en cmake ne fait que de la biblio statique, et n'exploite pas nos biblios partagées.
	cat > Makefile <<TERMINE
CXX := $CXX
CC := $CC
CPPFLAGS := $CPPFLAGS
LDFLAGS := $LDFLAGS
biblios := $biblios
dest := $dest

#sourcescpp := `find . -name "*.cpp" | grep -v /python_binding/ | tr '\012' ' '`
#sourcesc := `find . -name "*.c" | grep -v /python_binding/ | tr '\012' ' '`
# Finalement on ne prend que le script nécessaire pour une compatibilité HummusPDF / PDF-Writer (cf. les quelques .c qu'ils ont copiés directement dans leurs sources: on prend les mêmes).
sourcesc := aes_modes.c aes_ni.c aescrypt.c aeskey.c aestab.c
sources := \${sourcescpp} \${sourcesc}
objscpp := \$(sourcescpp:.cpp=.o)
objsc := \$(sourcesc:.c=.o)
objs := \${objscpp} \${objsc}
dest := $dest

libaesgm.so: \${objs}
	\$(CC) -shared -fpic \$(LDFLAGS) \$(biblios) \${objs} -o \$@

.c.o:
	\$(CC) -c -fpic \$(CPPFLAGS) \$< -o \$@

install: libaesgm.so
	mkdir -p \$(dest)/lib \$(dest)/include
	cp libaesgm.so \$(dest)/lib/
	cp *.h \$(dest)/include
TERMINE
}

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
configurer

echo Compilation… >&2
make

echo Installation… >&2
sudoku make install
pkgconfer -laesgm Aesgm "Brian Gladman's AES implementation, packaged for HummusPDF"

sutiliser
