#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

modifs="compil3264 dyld105 ccMac"
#v r10015 || true
v 0.8.6 && modifs="$modifs inclusions_ao" || true
v 1.0.0 || true
v 1.1.0 || true
v 1.2.0 || true

inclusions_ao()
{
	filtrer src/plugins/macosx/ao_macosx.c sed -e '/^#include/{
x
s/./&/
t-(
g
:-(
x
}' -e '/^$/{
x
s/^#.*$//
t-)
b-/
:-)
i\
#include <limits.h>
i\
#include <string.h>
s/^.*$/coucou/
:-/
x
}'
}

prerequis

archive=http://downloads.xiph.org/releases/ao/$logiciel-$version.tar.gz
archive_svn=http://svn.xiph.org/trunk/`echo "$logiciel" | sed -e 's/lib//g'`

destiner

conf=./configure
case "$version" in
	r*)
		obtenirEtAllerDansSvn -r `echo "$version" | sed -e 's/^r//'` $archive_svn
		export ACLOCAL_FLAGS="-I $INSTALLS/share/aclocal"
		conf=./autogen.sh
		;;
	*)
obtenirEtAllerDansVersion
		;;
esac

echo Correction… >&2
for modif in true $modifs ; do $modif "$@" ; done

echo Configuration… >&2
$conf --prefix="$dest"

echo Compilation… >&2
make
for modif in true $modifspostcompil ; do $modif "$@" ; done

echo Installation… >&2
sudoku make install

sutiliser
