#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delibere() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delibere ; s="`dirname "$s"`" ; Delibere ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 1.5.3 && prerequis="meson >= 0.50 ninja pkgconf+ig+-strict \\" || true # pkgconf non strict pour lui permettre d'aller chercher dans les dossiers systèmes pour les paquets GL, X11 etc.
v 1.5.10 || true

predestiner="$predestiner preGlx"

# Modifications

preGlx()
{
	local glx_racine options trouve=
	
	for glx_racine in "" /usr/local
	do
	# Nous tournons en phase de détection des prérequis, donc sans encore les modifs dont celle qui aura déterminé le $CC le plus adapté. Pour nous mettre dans les même conditions de compil que post-modifs, nous devons donc manuellement invoquer comme configurateur d'environnement le compiloSysVersion() habituel.
		case "$glx_racine" in
			"") options= ;;
			*) options="-I$glx_racine/include -L$glx_racine/lib" ;;
		esac
		if compilable -i compiloSysVersion _compiler_c $options -lGLX -- '#include <GL/glx.h>' 'int main(int argc, const char ** argv) { glXWaitGL(); return 0; }'
		then
			# N.B.: en réalité le meson recherche via pkg-config, donc notre test compilable() n'est pas représentatif.
			#       Ceci dit le pkgconf +ig +-strict en prérequis est censé connaître les chemins que nous testons ici (le +strict retirant les chemins système, ).
			modifierOptions =glx
			trouve=1
			break
		fi
	done
	case "$trouve" in "")
		modifierOptions -glx
		gris "libepoxy: compilé sans glx (introuvable)"
	;; esac
	
	if ! option glx
	then
		OPTIONS_MESON="$OPTIONS_MESON -Dglx=no -Degl=no" # À FAIRE?: dissocier EGL de GLX?
	fi
}

# Variables

archive="https://github.com/anholt/libepoxy/archive/refs/tags/$version.tar.gz" # En fait toutes les versions n'ont pas généré un beau .xz, on repose sur le .tar.gz brut de sources qui au moins est toujours présent.

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
mkdir -p _build && cd _build
meson --prefix="$dest" $OPTIONS_MESON

echo Compilation… >&2
ninja

echo Installation… >&2
# sudokupy ne devrait plus être nécessaire avec un python emboité.
sudokupy ninja install
sutiliser
