#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 1.26 && prerequis="iconv" && modifs="avecVersionScript" || true
v 1.29 || true
v 2.2.0 || true
v 2.3.7 || true

# Modifications

avecVersionScript()
{
	# Le configure détecte la capacité à exploiter l'option -Wl,--version-script=contest.map,
	# mais avec un contenu pourri (référençant un symbole non défini dans le .c).
	# Alors peut-être que GNU ld laisse passer, mais FreeBSD ld non.
	# En conséquent ça lui plante la compile, ce qui laisse croire au configure que ça ne sert à rien de coller l'option, ce qui génère une biblio non versionnée, ce qui plante tout le système puisque le curl installé par paquets a besoin d'une libpsl qui a besoin de certains symboles versionnés de libidn.
	# https://people.freebsd.org/~deischen/symver/library_versioning.txt
	# https://maskray.me/blog/2020-11-26-all-about-symbol-versioning
	filtrer configure sed -e 's/global: sym/global: */'
}

# Variables

lv="$logiciel"
pge $version 2 && lv="${lv}2" || true
archive="https://mirror.ibcp.fr/pub/gnu/libidn/$lv-$version.tar.gz"

prerequis

destiner

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
