#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.sh"

# Historique des versions gérées

logiciel=libjpeg

v 6.2 && version_biblio=63 || true # version_biblio pour AquaScribus, entre autres.
v 8.1 || true
v 8.2 && modifs="compil3264 dyld105" && modifspostconf=dylib || true
v 8.3 || true
v 8.4 || true
v 9 || true
v 9.1 || true

# Modifications

dylib()
{
	cat >> Makefile << TERMINE

libjpeg.dylib: \$(LIBOBJECTS)
	\$(RM) \$@
	cc \$(LDFLAGS) -dynamiclib -flat_namespace -Wl,-compatibility_version -Wl,$version_biblio.0.0 -Wl,-current_version -Wl,$version_biblio.0.0 -o \$@ \$^ -install_name \$(libdir)/\$@
TERMINE
	filtrer Makefile sed -e '/^install-lib:/a\
\	mkdir -p \$(libdir)
' -e '/^install-headers:/a\
\	mkdir -p \$(includedir)
' -e '/^install:/{
a\
\	mkdir -p \$(bindir)
a\
\	mkdir -p \$(mandir)
}'
	mac || return 0
	
	filtrer Makefile sed -e '/^all:/s/$/ libjpeg.dylib/' -e '/^install-lib:/{
s/$/ libjpeg.dylib/
a\
\	\$(INSTALL_LIB) libjpeg.dylib \$(libdir)/\$(binprefix)libjpeg.dylib
}'
}

# Variables

vnum="`echo "$version" | sed -e 's/[^0-9].*//'`"
vMinEnAlpha()
{
	vmin="`echo "$1" | sed -e 's/^[^.]*[.]*//'`"
	vminoctalval="`expr "$vmin" + 96`"
	vminoctal="`printf '%3.3o' "$vminoctalval"`"
	echo @ | tr @ \\$vminoctal
}
valpha="$vnum`vMinEnAlpha "$version"`"
archive="http://freshmeat.net/redir/$logiciel/5665/url_tgz/jpegsrc.v$valpha.tar.gz"
pge $vnum 8 && archive="http://www.ijg.org/files/jpegsrc.v$valpha.tar.gz"

# Constitution

destiner

obtenirEtAllerDans "$archive"

echo Correction… >&2
for modif in true $modifs; do $modif "$@" ; done

echo Configuration… >&2
./configure --prefix="$dest" $OPTIONS_CONF
for modif in true $modifspostconf ; do $modif "$@" ; done

echo Compilation… >&2
make
for modif in true $modifspostcompil ; do $modif "$@" ; done

echo Installation… >&2
pge $vnum 8 || sudo make install-lib
sudo make install
sutiliser

rm -Rf "$TMP/$$"
