#!/bin/sh
# Copyright (c) 2004,2008 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delicat() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delicat ; s="`dirname "$s"`" ; Delicat ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

prerequis=zlib
modifs=multiarch

v 1.2.5
v 1.2.25
v 1.2.37
v 1.4.1 && modifs="$modifs compat12" || true
v 1.4.4 || true
v 1.5.2 && retirerModif compat12 || true # Attention, la 1.5 retire des accès directs sur lesquels repose un vieux wx.
v 1.5.6
v 1.5.13
v 1.5.17
v 1.6.12 && modifs="$modifs feenableexcept" || true
v 1.6.16 || true
v 1.6.23 || true
v 1.6.24 || true
v 1.6.34 || true
v 1.6.35 || true
v 1.6.36 || true
v 1.6.37 || true
v 1.6.44 || true
v 1.6.47 || true

archive="http://switch.dl.sourceforge.net/sourceforge/png-mng/$logiciel-$version.tar.bz2"
pge $version 1.2.25 && archive="ftp://ftp.simplesystems.org/pub/libpng/png/src/$logiciel-$version.tar.bz2"
vmin="`echo "$version" | sed -e 's/\.//' -e 's/\..*//'`"
archive="http://freefr.dl.sourceforge.net/project/libpng/libpng$vmin/$version/libpng-$version.tar.xz"

feenableexcept()
{
	# Le test de feenableexcept dans le configure est bourrin (déclaration, invocation, et malgré l'alerte on croise les doigts pour qu'à l'édition de liens il tombe sur la définition),
	# alors qu'en compil normale, sous FreeBSD, on ne le retrouve dans /usr/include/fenv.h que sous condition d'avoir __BSD_VISIBLE.
	# https://sourceware.org/pipermail/newlib/2020/017738.html
	# Mais on ne doit pas définir __BSD_VISIBLE globalement, sous peine de perdre tout un paquet de fonctionnalités (timer_t par exemple). D'autant que là on n'est que dans les tests.
	case `uname` in FreeBSD) true ;; *) return ;; esac
	filtrer contrib/libtests/pngvalid.c sed -e '/fenv\.h/{
i\
#define __BSD_VISIBLE 1
a\
#undef __BSD_VISIBLE
}'
}

# Pour être invocable par des trucs qui ne connaissaient que la 1.2.
compat12()
{
	filtrer png.h sed -e '/png_set_expand_gray_1_2_4_to_8/i\
#define png_set_gray_1_2_4_to_8 png_set_expand_gray_1_2_4_to_8
'
}

apng()
{
	local rustine="`obtenir "https://altushost-swe.dl.sourceforge.net/project/libpng-apng/libpng16/$version/libpng-$version-apng.patch.gz?viasf=1"`"
	gunzip < "$rustine" | patch -p1
}

argOptions="`options "$argOptions=apng"`" # APNG est intégré d'office, si non non désiré. Notons que la libpng empaquetée pour FreeBSD est celle-ci (donc si on remplace par une sans, boum, plus de FIrefox par exemple).
if option apng ; then modifs="$modifs apng" ; fi

destiner

prerequis

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion
for modif in true $modifs ; do $modif "$@" ; done

echo Configuration… >&2
if pge $version 1.2.25
then
	./configure --prefix="$dest"
else
filtrer scripts/makefile.macosx sed -e '/^prefix=/c\
prefix='"$dest"'
' -e '/^LDFLAGS=/c\
LDFLAGS=-L. -L$(ZLIBLIB) -lpng -lz
' -e 's=-dynamiclib=-dynamiclib -install_name $(DL)/$@='
cp scripts/makefile.macosx Makefile
fi

echo Compilation… >&2
make

echo Installation… >&2
sudo mkdir -p "$dest" && sudo make install
pge 1.2.5 $version && [ "`uname -s`" = Darwin ] && sudo rm -f "$INSTALLS/lib/libpng.dylib" && sudo ln -s "$dest/lib/libpng.3.$version.dylib" "$INSTALLS/lib/libpng.dylib" # Ces couillons ont merdé leur Makefile, avec deux suffixes différents pour les biblios mais l'un est vide (d'où les libpng. qui traînent).
sutiliser
