#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

delieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; delieS ; s="`dirname "$s"`" ; delieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

set -e

# https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html
v 6.0.18 && prerequis="gcc >= 4.8.0 \\" || true
v 6.0.19 && prerequis="gcc >= 4.8.3 \\" || true
v 6.0.20 && prerequis="gcc >= 4.9.0 \\" || true
v 6.0.21 && prerequis="gcc >= 5.1.0 \\" || true
v 6.0.22 && prerequis="gcc >= 6.1.0 \\" || true
v 6.0.23 && prerequis="gcc >= 7.1.0 \\" || true
v 6.0.24 && prerequis="gcc >= 7.2.0 \\" || true

# destiner avant prérequis: on ne prérequiert que si on n'a pas pu télécharger une version binaire dans destiner.
destiner
installerBinaireSilo # Celui-ci fait un exit 0 s'il a trouvé.

prerequis

cd $TMP/$$

empaqueter()
{
	local GUILI_PATH="$GUILI_PATH"
	[ -n "$GUILI_PATH" ] || GUILI_PATH="$INSTALLS"
	
	# Où est notre libstdc++.so?
	
	local lib libstdcxx fouilles
	for lib in lib64 lib
	do
		libstdcxx="$destgcc/$lib/libstdc++.so"
		[ ! -f "$libstdcxx" ] || break
		fouilles="$fouilles $libstdcxx"
		libstdcxx=
	done
	[ -n "$libstdcxx" ] || err "# libstdc++.so introuvable (j'ai cherché:$fouilles)."
	
	# Recopie des biblios, et des dépendances.
	
	mkdir -p dest/lib
	(
		find "`dirname "$libstdcxx"`" -mindepth 1 -maxdepth 1 -name "libstdc++.so*"
		biblios "$libstdcxx" | egrep "^(`echo "$GUILI_PATH" | tr : \|`)/"
	) | while read biblio
	do
		cp "$biblio" "dest/lib/"
	done
}

empaqueter

sudoku -d "$INSTALLS" mkdir "$dest"
( cd dest && tar cf - . ) | ( sudoku sh -c "cd $dest && tar xf - --no-same-owner" )

sutiliser
