#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=libstemmer

version="`curl -s http://snowball.tartarus.org/dist/ | grep _c.tgz | sed -e 's/.*>\([0-9]*-[A-Z][a-z][a-z]-[0-9][0-9][0-9][0-9] [0-9][0-9]:[0-9][0-9]\).*/\1/' | php -r 'echo strftime("%Y-%m-%d", strtotime(file_get_contents("php://stdin")))."\n";'`"
modifs=makefile

# Modifications

makefile()
{
	filtrer Makefile sed -e '/^CFLAGS/s/$/ -fpic/' -e '/^all: /s/$/ libstemmer.so/'
	cat >> Makefile <<TERMINE
libstemmer.so: \$(snowball_sources:.c=.o)
	gcc -shared -o \$@ \$^
TERMINE
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="http://snowball.tartarus.org/dist/libstemmer_c.tgz"

[ -d "$dest" ] && exit 0

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
[ -z "$avec_lucene" ] || options="--with-clucene"

echo Compilation… >&2
make

echo Installation… >&2
sudo mkdir -p "$dest/lib"
sudo cp libstemmer.so "$dest/lib/"
sudo cp -R include "$dest/"

sutiliser $logiciel-$version

rm -Rf "$TMP/$$"
