#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

archive="http://snowball.tartarus.org/dist/libstemmer_c.tgz"

dateArchive()
{
	local archive="$1"
	local dtexte="`curl -I "$archive" | grep '^Last-Modified' | cut -d ' ' -f 2-`"
	case `uname` in
		Linux) date -d "$dtexte" +%Y.%m.%d ;;
		*) LC_ALL=C date -jf "%a, %e %b %Y %H:%M:%S %Z" "$dtexte" +%Y.%m.%d ;;
	esac
}
version="`dateArchive "$archive"`"
modifs=makefile

# Modifications

makefile()
{
	filtrer Makefile sed -e '/^CFLAGS/s/$/ -fpic/' -e '/^all: /s/$/ libstemmer.so/'
	filtrer Makefile sed -e '/^all: /s/ libstemmer.o//'
	filtrer Makefile sed -e '/^all: /s/ stemwords//'
	cat >> Makefile <<TERMINE
libstemmer.so: \$(snowball_sources:.c=.o)
	cc -shared -o \$@ \$^
TERMINE
}

# Variables

destiner

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion "libstemmer_c.$version.tgz"

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2

echo Compilation… >&2
make

echo Installation… >&2
sudo mkdir -p "$dest/lib"
sudo cp libstemmer.so "$dest/lib/"
sudo cp -R include "$dest/"

sutiliser
