#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=libtorrent

v 0.15.4 && modifs="boostfs2 dyld105"
v 0.16.0 && modifs="dyld105 putainDeLibJPEGDeMacOSX boostRoot"

inclure openssl

dest="$INSTALLS/$logiciel-$version"
archive="http://libtorrent.googlecode.com/files/libtorrent-rasterbar-$version.tar.gz"

# Modifications

# Ne marche pas. Il faudrait plutôt requérir un boot < 1.46 (en 1.45, le FS 2 était paraît-il le défaut).
boostfs2()
{
	# http://stackoverflow.com/questions/9864871/libtorrent-rasterbar-compiling-examples
	filtrer CMakeLists.txt sed -e '/DBOOST_DISABLE_EXCEPTION/a\
add_definitions(-DBOOST_FILESYSTEM_VERSION=2)
'
	CFLAGS="$CFLAGS -DBOOST_FILESYSTEM_VERSION=2"
	CPPFLAGS="$CPPFLAGS -DBOOST_FILESYSTEM_VERSION=2"
	CXXFLAGS="$CXXFLAGS -DBOOST_FILESYSTEM_VERSION=2"
	filtrer configure sed -e '/HAVE_BOOST_FILESYSTEM/a\
$as_echo "#define BOOST_FILESYSTEM_VERSION 2" >>confdefs.h
'
}

boostRoot()
{
	export BOOST_ROOT="$INSTALLS"
}

[ -d "$dest" ] && exit 0

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
export CFLAGS="$CFLAGS -arch i386" CPPFLAGS="$CPPFLAGS -arch i386"  CXXFLAGS="$CXXFLAGS -arch i386" LDFLAGS="$LDFLAGS -arch i386" OBJCFLAGS="$OBJCFLAGS -arch i386" OBJCXXFLAGS="$OBJCXXFLAGS -arch i386"
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser "$logiciel-$version"

rm -Rf /tmp/$$
