#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delicat() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delicat ; s="`dirname "$s"`" ; Delicat ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

modifs=multiarch

v 3.7.2 || true
#version=2005-05-05 && modifs=detectionGLMac
v 3.9.4 && modifs="$modifs jpeg9" && prerequis="zlib $prerequis_libjpeg" || true
v 3.9.7 || true
v 4.0.3 || true
v 4.0.6 || true
v 4.0.7 || true
v 4.0.8 || true
v 4.0.9 || true

prerequis

detectionGLMac()
{
	[ `uname` = Darwin ] || return 0
	
	OPTIONS_CONF="$OPTIONS_CONF --with-apple-opengl-framework"
	
	patch -p0 << TERMINE
--- acinclude.m4	12 Sep 2004 09:15:05 -0000	1.4
+++ acinclude.m4	5 May 2005 09:05:31 -0000
@@ -120,7 +120,7 @@
 
 dnl ---------------------------------------------------------------------------
 dnl Available from the GNU Autoconf Macro Archive at:
-dnl http://www.gnu.org/software/ac-archive/htmldoc/ax_check_gl.html
+dnl http://www.gnu.org/software/ac-archive/ax_check_gl.html
 dnl ---------------------------------------------------------------------------
 AC_DEFUN([AX_CHECK_GL],
 [AC_REQUIRE([AC_PATH_X])dnl
@@ -137,10 +137,15 @@
 if test "X\$with_apple_opengl_framework" = "Xyes"; then
   AC_DEFINE([HAVE_APPLE_OPENGL_FRAMEWORK], [1],
             [Use the Apple OpenGL framework.])
-  GL_CFLAGS="-framework OpenGL"
+  GL_LIBS="-framework OpenGL"
 else
-  GL_CFLAGS="\${PTHREAD_CFLAGS}"
-  GL_LIBS="\${PTHREAD_LIBS} -lm"
+  AC_LANG_PUSH(C)
+
+  AX_LANG_COMPILER_MS
+  if test X\$ax_compiler_ms = Xno; then
+    GL_CFLAGS="\${PTHREAD_CFLAGS}"
+    GL_LIBS="\${PTHREAD_LIBS} -lm"
+  fi
 
   #
   # Use x_includes and x_libraries if they have been set (presumably by
@@ -155,8 +160,6 @@
     fi
   fi
 
-  AC_LANG_PUSH(C)
-
   AC_CHECK_HEADERS([windows.h])
 
   AC_CACHE_CHECK([for OpenGL library], [ax_cv_check_gl_libgl],
@@ -166,20 +169,20 @@
   ax_save_LIBS="\${LIBS}"
   LIBS=""
   ax_check_libs="-lopengl32 -lGL"
-    for ax_lib in \${ax_check_libs}; do
-    if test "X\$CC" = "Xcl"; then
+  for ax_lib in \${ax_check_libs}; do
+    if test X\$ax_compiler_ms = Xyes; then
       ax_try_lib=\`echo \$ax_lib | sed -e 's/^-l//' -e 's/$/.lib/'\`
     else
       ax_try_lib="\${ax_lib}"
     fi
     LIBS="\${ax_try_lib} \${GL_LIBS} \${ax_save_LIBS}"
-    AC_TRY_LINK([
+    AC_LINK_IFELSE(
+    [AC_LANG_PROGRAM([[
 # if HAVE_WINDOWS_H && defined(_WIN32)
 #   include <windows.h>
 # endif
-# include <GL/gl.h>
-],
-    [glBegin(0)],
+# include <GL/gl.h>]],
+                     [[glBegin(0)]])],
     [ax_cv_check_gl_libgl="\${ax_try_lib}"; break])
   done
   LIBS=\${ax_save_LIBS}
@@ -201,10 +204,11 @@
 
 dnl ---------------------------------------------------------------------------
 dnl Available from the GNU Autoconf Macro Archive at:
-dnl http://www.gnu.org/software/ac-archive/htmldoc/ax_check_glu.html
+dnl http://www.gnu.org/software/ac-archive/ax_check_glu.html
 dnl ---------------------------------------------------------------------------
 AC_DEFUN([AX_CHECK_GLU],
 [AC_REQUIRE([AX_CHECK_GL])dnl
+AC_REQUIRE([AC_PROG_CXX])dnl
 GLU_CFLAGS="\${GL_CFLAGS}"
 if test "X\${with_apple_opengl_framework}" != "Xyes"; then
   AC_CACHE_CHECK([for OpenGL Utility library], [ax_cv_check_glu_libglu],
@@ -215,7 +219,7 @@
   LIBS=""
   ax_check_libs="-lglu32 -lGLU"
   for ax_lib in \${ax_check_libs}; do
-    if test "X\$CC" = "Xcl"; then
+    if test X\$ax_compiler_ms = Xyes; then
       ax_try_lib=\`echo \$ax_lib | sed -e 's/^-l//' -e 's/$/.lib/'\`
     else
       ax_try_lib="\${ax_lib}"
@@ -227,25 +231,27 @@
     # "conftest.cc"; and Microsoft cl doesn't know what to do with such a
     # file.
     #
-    if test "X\$CXX" != "Xcl"; then
-      AC_LANG_PUSH([C++])
+    AC_LANG_PUSH([C++])
+    if test X\$ax_compiler_ms = Xyes; then
+      AC_LANG_PUSH([C])
     fi
-    AC_TRY_LINK([
+    AC_LINK_IFELSE(
+    [AC_LANG_PROGRAM([[
 # if HAVE_WINDOWS_H && defined(_WIN32)
 #   include <windows.h>
 # endif
-# include <GL/glu.h>
-],
-    [gluBeginCurve(0)],
+# include <GL/glu.h>]],
+                     [[gluBeginCurve(0)]])],
     [ax_cv_check_glu_libglu="\${ax_try_lib}"; break])
-    if test "X\$CXX" != "Xcl"; then
-      AC_LANG_POP([C++])
+    if test X\$ax_compiler_ms = Xyes; then
+      AC_LANG_POP([C])
     fi
+    AC_LANG_POP([C++])
   done
   LIBS=\${ax_save_LIBS}
   CPPFLAGS=\${ax_save_CPPFLAGS}])
   if test "X\${ax_cv_check_glu_libglu}" = "Xno"; then
-    no_gl="yes"
+    no_glu="yes"
     GLU_CFLAGS=""
     GLU_LIBS=""
   else
@@ -258,23 +264,25 @@
 
 dnl ---------------------------------------------------------------------------
 dnl Available from the GNU Autoconf Macro Archive at:
-dnl http://www.gnu.org/software/ac-archive/htmldoc/ax_check_glut.html
+dnl http://www.gnu.org/software/ac-archive/ax_check_glut.html
 dnl ---------------------------------------------------------------------------
+
 AC_DEFUN([AX_CHECK_GLUT],
 [AC_REQUIRE([AX_CHECK_GLU])dnl
 AC_REQUIRE([AC_PATH_XTRA])dnl
 
 if test "X\$with_apple_opengl_framework" = "Xyes"; then
-  GLUT_CFLAGS="-framework GLUT \${GLU_CFLAGS}"
-  GLUT_LIBS="-lobjc \${GL_LIBS}"
+  GLUT_CFLAGS="\${GLU_CFLAGS}"
+  GLUT_LIBS="-framework GLUT -lobjc \${GL_LIBS}"
 else
   GLUT_CFLAGS=\${GLU_CFLAGS}
+  GLUT_LIBS=\${GLU_LIBS}
 
   #
   # If X is present, assume GLUT depends on it.
   #
   if test "X\${no_x}" != "Xyes"; then
-    GLUT_LIBS="\${X_PRE_LIBS} -lXmu -lXi \${X_EXTRA_LIBS} \${GLU_LIBS}"
+    GLUT_LIBS="\${X_PRE_LIBS} -lXmu -lXi \${X_EXTRA_LIBS} \${GLUT_LIBS}"
   fi
 
   AC_LANG_PUSH(C)
@@ -288,19 +296,19 @@
   LIBS=""
   ax_check_libs="-lglut32 -lglut"
   for ax_lib in \${ax_check_libs}; do
-    if test "X\$CC" = "Xcl"; then
+    if test X\$ax_compiler_ms = Xyes; then
       ax_try_lib=\`echo \$ax_lib | sed -e 's/^-l//' -e 's/$/.lib/'\`
     else
       ax_try_lib="\${ax_lib}"
     fi
     LIBS="\${ax_try_lib} \${GLUT_LIBS} \${ax_save_LIBS}"
-    AC_TRY_LINK([
+    AC_LINK_IFELSE(
+    [AC_LANG_PROGRAM([[
 # if HAVE_WINDOWS_H && defined(_WIN32)
 #   include <windows.h>
 # endif
-# include <GL/glut.h>
-  ],
-    [glutMainLoop()],
+# include <GL/glut.h>]],
+                     [[glutMainLoop()]])],
     [ax_cv_check_glut_libglut="\${ax_try_lib}"; break])
 
   done
--- tools/tiffgt.c	3 Feb 2005 19:46:49 -0000	1.3
+++ tools/tiffgt.c	5 May 2005 09:05:35 -0000
@@ -31,8 +31,13 @@
 #include <string.h>
 #include <unistd.h>
 
+#if HAVE_APPLE_OPENGL_FRAMEWORK
+#include <OpenGL/gl.h>
+#include <GLUT/glut.h>
+#else
 #include <GL/gl.h>
 #include <GL/glut.h>
+#endif
 
 #include "tiffio.h"
 
TERMINE
	autoconf
}

jpeg9()
{
	# libjpeg9 définit TRUE et FALSE comme valeurs d'un enum; si elles sont déjà définies, ça fout le boxon.
	cat > /tmp/hop.c <<TERMINE
#include <sys/types.h>
#include <stdio.h>
#define TRUE 1
#include <jmorecfg.h>
TERMINE
	cc -c -o /tmp/hop.o -I$INSTALLS/include /tmp/hop.c 2> /dev/null >&2 && return || true
	for i in jpeg ojpeg
	do
		filtrer libtiff/tif_${i}.c sed -e '/include "jpeglib.h"/{
i\
#undef TRUE
i\
#undef FALSE
}'
	done
}

# Variables

archive=ftp://ftp.remotesensing.org/pub/$logiciel/tiff-$version.tar.gz
archive="ftp://download.osgeo.org/libtiff/tiff-$version.tar.gz"
archive="https://download.osgeo.org/libtiff/tiff-$version.tar.gz"
archive="https://gitlab.com/libtiff/libtiff/-/archive/Release-v`echo "$version" | tr . -`/libtiff-Release-v`echo "$version" | tr . -`.tar.bz2"
archive="https://download.osgeo.org/libtiff/tiff-$version.tar.xz" # Depuis la 4.4.
archive_cvs=cvs://cvsanon:@cvs.maptools.org:/cvs/maptools/cvsroot:libtiff

destiner

obtenirEtAllerDansVersion

OPTIONS_CONF=
for modif in true $modifs ; do $modif "$@" ; done

echo Configuration… >&2
./configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
