#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delibere() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delibere ; s="`dirname "$s"`" ; Delibere ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

. "$SCRIPTS/libuv.util.sh"

# Historique des versions gérées

prerequis="m4 autoconf automake libtool \\" && modifs="deguillemette"
v 1.23.0 || true # Dernière version avant "remove epoll syscall wrappers", cf. https://gitlab.kitware.com/cmake/cmake/-/issues/19086
if eventfd
then
v 1.38.0 || true
v 1.44.2 || true
v 1.45.0 && modifs="$modifs mmsg" || true
v 1.46.0 || true
v 1.48.0 || true
v 1.49.0 && modifs="$modifs futimens1" || true
v 1.50.0 && modifs="$modifs thread_setname" || true
v 1.51.0 || true
v 1.52.1 || true
fi

# Modifications

thread_setname()
{
	# Les vieux FreeBSD ont un pthread_set_name_np qui fait comme le pthread_setname_np standardisé, juste sans retour.
	# Il se trouve que libuv utilise encore cette alternative pour OpenBSD.
	
	case `uname` in FreeBSD) true ;; *) return ;; esac
	
	compilable_c -lpthread -- '#include <pthread_np.h>' 'int main(int argc, char ** argv) { pthread_setname_np(0, "coucou"); return 0; }' && return || true
	compilable_c -lpthread -- '#include <pthread_np.h>' 'int main(int argc, char ** argv) { pthread_set_name_np(0, "coucou"); return 0; }' || return 0 # Là on ne peut plus rien, on ne retraite pas le fichier et on laissera la compil' planter.
	
	gris "Compilation avec le pthread_set_name_np OpenBSD"
	
	filtrer src/unix/thread.c sed -e 's/defined(__OpenBSD__)/defined(__OpenBSD__) || defined(__FreeBSD__)/'
	
	compilable_c -lpthread -- '#include <pthread_np.h>' 'int main(int argc, char ** argv) { pthread_get_name_np(0, 0, 0); return 0; }' ||
	filtrer src/unix/thread.c sed -e '/int uv__thread_getname[^;]*$/{
a\
return UV_ENOSYS;
a\
#define pthread_get_name_np(a, b, c) {}
}
'
}

futimens1()
{
	compilable_c -- '#include <sys/stat.h>' 'int main(int argc, char ** argv) { struct timespec times[2]; return futimens(0, times); }' && return || gris "Compilation sans timespec (non implémentée sur ce système)"
	
	# À FAIRE?: réimplémenter utimensat(…, AT_SYMLINK_NOFOLLOW) plutôt que le dégrader en utimes() qui follow?
	filtrer src/unix/fs.c sed -E -e \
'
s/struct timespec/struct timeval/g
s/tv_nsec/tv_usec/g
s/(st_[a-z]*tim)\.tv_usec/\1.tv_nsec/g
s/1e9/1e6/g
s/futimens/futimes/g
s/utimensat\(AT_FDCWD, (.*), (0|AT_SYMLINK_NOFOLLOW)\)/utimes(\1)/g
s#([^ ]*) = ([a-z_]*\.st_[a-z]*tim);#\1.tv_sec = \2.tv_sec; \1.tv_usec = \2.tv_nsec / 1000;#g
s/return[^;]*UTIME_(NOW|OMIT)[^;]*;/{}/g
'
}

mmsg()
{
	# La présence de sendmmsg et recvmmsg (lots de trames UDP) est supposée pour FreeBSD, mais tout dépend de la version.
	
	local HAVE_MMSG=1
	compilable_c -- '#include <sys/socket.h>' 'int main(int argc, char ** argv) { return sendmmsg(0, 0, 0, 0); }' || { gris "Compilation sans mmsg UDP (non implémentés sur ce système)" ; HAVE_MMSG=0 ; }
	filtrer src/unix/udp.c sed -E -e '/#include <sys\/un.h>/a\
#define HAVE_MMSG '"$HAVE_MMSG"'
/(int|void) (uv__udp_recvmmsg|uv_udp_using_recvmmsg|uv__udp_sendmsg)/h;/^}/{x;s/.*//;x;}' -e '/defined\(__FreeBSD__\)/{
x
s/././
x
t-O
b
:-O
s/defined\(__FreeBSD__\)/HAVE_MMSG/
}'
}

deguillemette()
{
	# Notre aclocal est un aclocal -Ietc.
	filtrer autogen.sh sed -e 's/^"\$\(ACLOCAL\)"/$ACLOCAL/'
}

# Variables

archive=https://dist.libuv.org/dist/v$version/libuv-v$version.tar.gz

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
[ -x configure ] || { chmod u+x autogen.sh ; ./autogen.sh ; }
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
