#!/bin/sh
# Copyright (c) 2005,2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# N.B.: pourrait s'intéresser à ICU: le configure (en 2.9.10) précise "Disabling ICU support". Qu'apporte ICU?
v 2.6.19 && prerequis="make \\ gettext zlib" || true
v 2.6.22 || true
v 2.6.31 || true
#v 2.7.3 || true # Compil bof sous Mac OS X 10.4 PPC
v 2.7.7 || true
v 2.9.0 && modifs=pthread290 || true
v 2.9.2 && modifs= || true
v 2.9.7 || true
v 2.9.9 || true
v 2.9.10 || true
v 2.9.12 || true
v 2.9.14 || true
v 2.10.4 || true
v 2.11.6 || true
v 2.12.9 || true
v 2.13.5 || true
v 2.15.1 || true

if pge $version 2.10
then
archive=https://gitlab.gnome.org/GNOME/libxml2/-/archive/v$version/libxml2-v$version.tar.gz
v_maj="`echo "$version" | cut -d . -f 1-2`"
archive=https://download.gnome.org/sources/libxml2/$v_maj/libxml2-$version.tar.xz
prerequis="pkgconfig \\ $prerequis"
else
archive=http://xmlsoft.org/sources/libxml2-$version.tar.gz
fi

forcagePython()
{
	# Si Python est détecté par exemple dans /bin, le ocnfigure va tout faire pour s'y greffer, même si ce n'est pas le Python avec lequel viennent les include et autres éléments de développement (ex.: un OS qui a un Python binaire dans un dossier système et un "de dév" dans /usr/local). On doit donc le forcer à utiliser notre version de dév.
	OPTIONS_CONF="$OPTIONS_CONF --with-python=$destpython"
}

pthread290()
{
	# http://git.gnome.org/browse/libxml2/commit/?id=3f6cfbd1d38d0634a2ddcb9a0a13e1b5a2195a5e
	patch -p1 <<TERMINE
diff --git a/threads.c b/threads.c
index f206149..7e85a26 100644
--- a/threads.c
+++ b/threads.c
@@ -146,6 +146,7 @@ struct _xmlRMutex {
 static pthread_key_t globalkey;
 static pthread_t mainthread;
 static pthread_once_t once_control = PTHREAD_ONCE_INIT;
+static pthread_once_t once_control_init = PTHREAD_ONCE_INIT;
 static pthread_mutex_t global_init_lock = PTHREAD_MUTEX_INITIALIZER;
 #elif defined HAVE_WIN32_THREADS
 #if defined(HAVE_COMPILER_TLS)
@@ -915,7 +916,7 @@ xmlCleanupThreads(void)
 #ifdef HAVE_PTHREAD_H
     if ((libxml_is_threaded)  && (pthread_key_delete != NULL))
         pthread_key_delete(globalkey);
-    once_control = PTHREAD_ONCE_INIT;
+    once_control = once_control_init;
 #elif defined(HAVE_WIN32_THREADS) && !defined(HAVE_COMPILER_TLS) && (!defined(LIBXML_STATIC) || defined(LIBXML_STATIC_FOR_DLL))
     if (globalkey != TLS_OUT_OF_INDEXES) {
         xmlGlobalStateCleanupHelperParams *p;
TERMINE
}

[ -d "$dest" ] && exit 0

# Si python est installé, le configure va chercher à créer la biblio pour. Soit on ajoute un --without-python, soit on s'assure qu'il soit complet (avec ses en-têtes), donc le plus simple pour ça c'est d'inclure python.
command -v python > /dev/null 2>&1 && prerequis="python \\ $prerequis" && modifs="$modifs forcagePython" || true

destiner

prerequis

obtenirEtAllerDansVersion

echo Corrections… >&2
for modif in true $modifs
do
	$modif
done

echo Configuration… >&2
./configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
make -j 3

echo Installation… >&2
sudo make install
#[ -e "$dest/include/libxml" ] || sudo ln -s libxml2/libxml "$dest/include/libxml"
sutiliser
