#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=lilypond

# Historique des versions gérées

v 2.18.2 && prerequis="guile < 1.9 tex" && modifs="gsfonts" || true

prerequis

# Modifications

gsfonts()
{
	destPolices=/usr/share/fonts # À FAIRE: dans $INSTALLS/share/fonts, après avoir mkdir -pé le dossier, et configuré fc-list pour voir le contenu de ce répertoire.
	
	[ -e $destPolices/c059013l.pfb ] && return # À FAIRE: voir note ci-dessous.
	
	case oui in
		oui)
			# Il nous faut une vieille version:
			# https://bugzilla.redhat.com/show_bug.cgi?id=1160132
			mkdir polices
			cd polices
			curl -s -O 'http://arm.koji.fedoraproject.org//packages/urw-fonts/2.4/19.fc21/src/urw-fonts-2.4-19.fc21.src.rpm'
			rpm2cpio urw-fonts-2.4-19.fc21.src.rpm | cpio -idm
			tar xjf urw-fonts-1.0.7pre44.tar.bz2
			sudo cp c0590*.pfb $destPolices/
			sudo fc-cache
			cd ..
			;;
		1)
			( obtenirEtAllerDans "http://downloads.ghostscript.com/public/ghostscript-9.15.tar.gz" )
			;;
		0)
			curl -L 'https://www.archlinux.org/packages/extra/any/gsfonts/download/' > gsfonts.tar.xz
			7za x gsfonts.tar.xz
			tar xf gsfonts.tar
			sudo cp usr/share/fonts/Type1/c0590*.pfb $destPolices/
			sudo fc-cache
			;;
	esac
}

# http://stackoverflow.com/questions/18787375/how-do-i-extract-the-contents-of-an-rpm
rpm2cpio()
{
	pkg=$1
	if [ "$pkg" = "" -o ! -e "$pkg" ]; then
		echo "no package supplied" 1>&2
		exit 1
	fi
	
	leadsize=96
	o=`expr $leadsize + 8`
	set `od -j $o -N 8 -t u1 $pkg`
	il=`expr 256 \* \( 256 \* \( 256 \* $2 + $3 \) + $4 \) + $5`
	dl=`expr 256 \* \( 256 \* \( 256 \* $6 + $7 \) + $8 \) + $9`
	# echo "sig il: $il dl: $dl"
	
	sigsize=`expr 8 + 16 \* $il + $dl`
	o=`expr $o + $sigsize + \( 8 - \( $sigsize \% 8 \) \) \% 8 + 8`
	set `od -j $o -N 8 -t u1 $pkg`
	il=`expr 256 \* \( 256 \* \( 256 \* $2 + $3 \) + $4 \) + $5`
	dl=`expr 256 \* \( 256 \* \( 256 \* $6 + $7 \) + $8 \) + $9`
	# echo "hdr il: $il dl: $dl"
	
	hdrsize=`expr 8 + 16 \* $il + $dl`
	o=`expr $o + $hdrsize`
	EXTRACTOR="dd if=$pkg ibs=$o skip=1"
	
	COMPRESSION=`($EXTRACTOR |file -) 2>/dev/null`
	if echo $COMPRESSION |grep -q gzip; then
		DECOMPRESSOR=gunzip
	elif echo $COMPRESSION |grep -q bzip2; then
		DECOMPRESSOR=bunzip2
	elif echo $COMPRESSION |grep -q xz; then
		DECOMPRESSOR=unxz
	elif echo $COMPRESSION |grep -q cpio; then
		DECOMPRESSOR=cat
	else
		# Most versions of file don't support LZMA, therefore we assume
		# anything not detected is LZMA
		DECOMPRESSOR=`which unlzma 2>/dev/null`
		case "$DECOMPRESSOR" in
			/* ) ;;
			*  ) DECOMPRESSOR=`which lzmash 2>/dev/null`
				case "$DECOMPRESSOR" in
				/* ) DECOMPRESSOR="lzmash -d -c" ;;
				*  ) DECOMPRESSOR=cat ;;
				esac
				;;
		esac
	fi
	
	$EXTRACTOR 2>/dev/null | $DECOMPRESSOR
}

# Variables

dest="$INSTALLS/$logiciel-$version"
vmaj="`echo "$version" | cut -d . -f 1-2`"
archive="http://download.linuxaudio.org/lilypond/sources/v$vmaj/lilypond-$version.tar.gz"

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
