#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 4.82 && modifs="srcBsd confBsdAvecSrcATrous" || true
v 4.84 || true
v 4.85 || true
v 4.87 || true
v 4.88 || true
v 4.89 || true

# Modifications

srcBsd()
{
	[ FreeBSD = `uname` ] || return 0
	[ ! -d /usr/src/sys ] || return 0
	
	fbsd="`uname -r | cut -d - -f 1`.0"
	sfbsd="https://svnweb.freebsd.org/base/release/$fbsd/sys"
	mkdir -p racine/sys
	cd racine/sys
	for f in sys/conf.h sys/types.h kern/kern_lockf.c fs/devfs/devfs_int.h sys/filedesc.h
	do
		mkdir -p "./`dirname $f`"
		curl -s "$sfbsd/$f?view=co" > "$f"
	done
	cd ..
	sudo cp -R * /usr/src/./
	cd ..
}

confBsdAvecSrcATrous()
{
	# Nos environnement de dév kernel est incomplet (on l'a reconstitué à la main, cf. srcBsd), il y a donc quelques petites choses que le Configure ne pourra pas trouver.
	export FREEBSD_MAKE_CONF=/rien/du/tout
	# Le Configure repose sur une option du make BSD que n'a pas le GNU make.
	chmod u+w Configure
	filtrer Configure sed -e '/-VCFLAGS/s#\$LSOF_MAKE#/usr/bin/make#g'
}

# Variables

archive="https://www.mirrorservice.org/sites/lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_$version.tar.bz2"

destiner

prerequis

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion
tar xf ${logiciel}_${version}_src.tar
cd ${logiciel}_${version}_src

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./Configure -n "`uname | tr A-Z a-z`"

echo Compilation… >&2
make

echo Installation… >&2
sudo mkdir -p "$dest/bin"
sudo cp lsof "$dest/bin/"

sutiliser
