#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=lsof

v 4.82 && modifs=paslirelaconf || true
v 4.84 || true
v 4.85 || true
v 4.87 || true
v 4.88 || true

# Modifications

paslirelaconf()
{
	export FREEBSD_MAKE_CONF=/rien/du/tout
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/${logiciel}_$version.tar.bz2"

[ -d "$dest" ] && exit 0

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion
tar xf ${logiciel}_${version}_src.tar
cd ${logiciel}_${version}_src

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./Configure freebsd

echo Compilation… >&2
make

echo Installation… >&2
sudo mkdir -p "$dest/bin"
sudo cp lsof "$dest/bin/"

sutiliser $logiciel-$version

rm -Rf "$TMP/$$"
