#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; [ -x "$SCRIPTS" -o ! -x "$0" ] || SCRIPTS="$0" ; case "`basename "$SCRIPTS"`" in *.*) true ;; *sh) SCRIPTS="$1" ;; esac ; case "$SCRIPTS" in /*) ;; *) SCRIPTS="`pwd`/$SCRIPTS" ;; esac ; delie() { while [ -h "$SCRIPTS" ] ; do SCRIPTS2="`readlink "$SCRIPTS"`" ; case "$SCRIPTS2" in /*) SCRIPTS="$SCRIPTS2" ;; *) SCRIPTS="`dirname "$SCRIPTS"`/$SCRIPTS2" ;; esac ; done ; } ; delie ; SCRIPTS="`dirname "$SCRIPTS"`" ; delie
. "$SCRIPTS/util.sh"

v 5.5.34 && prerequis="" || true
v 5.5.63 || true
v 10.2.22 && modifs="sansLto sansRelro" || true
v 10.3.13 || true

archive="http://mariadb.mirrors.ovh.net/MariaDB//mariadb-$version/source/mariadb-$version.tar.gz"

sansRelro()
{
	# Les versions récentes des linkers (gnu ld entre autres) incluent des protections contre la réécriture de la section code.
	# Malheureusement sur mon FreeBSD 10.2 + clang 7.0.1 + GNU ld récent, avec cette option, un programme tout simple comme comp_sql segfault au lancement.
	# On désactive donc.
	filtrer CMakeLists.txt egrep -ve "-z,relro|-z,now"
}

sansLto()
{
	# Sur mon FreeBSD 10.2 (avec un clang monté en 7 + un binutils GNU), pétage lorsque tokudb essaie d'ajouter les Link-Time Optimizations:
	# celles-ci requièrent en effet un greffon à ld (celui de GNU dans mon cas), greffon qui doit être mis à disposition par le compilo.
	# Or le greffon n'est pas compilé par défaut avec Clang (et il semble même déconseillé de le faire, cf. https://llvm.org/docs/GoldPlugin.html).
	# Donc on désactive et puis c'est tout.
	filtrer storage/tokudb/CMakeLists.txt sed -e 's/ -flto //g' -e 's/ -fuse-linker-plugin//g'
}

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
cmake -DCMAKE_INSTALL_PREFIX="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser
