#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 5.5.34 && prerequis="zlib libexecinfo iconv cmake lz4 openssl libevent" || true
v 5.5.63 || true
v 10.2.22 && modifs="pasDUsrLocalInclude sansLto sansRelro" || true
v 10.3.13 || true
v 10.4.11 && modifs="$modifs sansDl vMroonga jemalloc" || true

archive="http://mariadb.mirrors.ovh.net/MariaDB//mariadb-$version/source/mariadb-$version.tar.gz"

# Modifications

jemalloc()
{
	# Font chier ces gars qui développent uniquement pour Linux.
	# https://jira.mariadb.org/browse/MDEV-20248#comment-132718
	
	filtrer storage/rocksdb/rocksdb/port/jemalloc_helper.h sed -e '/ifndef JEMALLOC_CXX_THROW/{
i\
#ifndef JEMALLOC_USABLE_SIZE_CONST
i\
#define JEMALLOC_USABLE_SIZE_CONST const
i\
#endif
}'
}

vMroonga()
{
	# Pas de bol, mroonga inscrit sa version dans un fichier sobrement intitulé "version", dans un dossier faisant partie des chemins d'inclusion. Or tout plein de fichiers de la libc++ de clang 8 (cstddef, mutex, locale, etc.) font un #include <version> qui tombe sur ce fichier texte au lieu du version[.hpp] attendu.
	# https://forum.directadmin.com/threads/how-to-mariadb-10-3-12-on-freebsd-11-2.57486/
	# http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-dbs/mysql/mariadb/clang_version_header_conflict.patch?h=master
	mv storage/mroonga/version storage/mroonga/version.txt
	filtrer storage/mroonga/CMakeLists.txt sed -e 's#/version #/version.txt #'
}

sansDl()
{
	# À FAIRE: une détection un peu plus précise de la nécessité d'un -ldl.
	case "`uname`" in
		FreeBSD) true ;;
		*) return 0 ;;
	esac
	for f in plugin/auth_pam/CMakeLists.txt wsrep-lib/src/CMakeLists.txt
	do
		filtrer "$f" sed -e 's/ dl//'
	done
}

pasDUsrLocalInclude()
{
	# Ils codent en dur /usr/local pour libexecinfo. Problème: ça va nous ramener tout plein de trucs non forcément désirés (dont par exemple une OpenSSL récente, alors qu'on a peut-être demandé une 1.0).
	filtrer cmake/os/FreeBSD.cmake sed -e "s#/usr/local#$destlibexecinfo#g"
}

sansRelro()
{
	# Les versions récentes des linkers (gnu ld entre autres) incluent des protections contre la réécriture de la section code.
	# Malheureusement sur mon FreeBSD 10.2 + clang 7.0.1 + GNU ld récent, avec cette option, un programme tout simple comme comp_sql segfault au lancement.
	# On désactive donc.
	filtrer CMakeLists.txt egrep -ve "-z,relro|-z,now"
}

sansLto()
{
	# Sur mon FreeBSD 10.2 (avec un clang monté en 7 + un binutils GNU), pétage lorsque tokudb essaie d'ajouter les Link-Time Optimizations:
	# celles-ci requièrent en effet un greffon à ld (celui de GNU dans mon cas), greffon qui doit être mis à disposition par le compilo.
	# Or le greffon n'est pas compilé par défaut avec Clang (et il semble même déconseillé de le faire, cf. https://llvm.org/docs/GoldPlugin.html).
	# Donc on désactive et puis c'est tout.
	filtrer storage/tokudb/CMakeLists.txt sed -e 's/ -flto //g' -e 's/ -fuse-linker-plugin//g'
}

destiner

prerequisOpenssl
prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
cmake -DCMAKE_INSTALL_PREFIX="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser
