#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

prerequis="cmake \\ boost"
v 1.3.1 && installation=installationManuelle || true
v 1.4.3 || true
v 1.5.0 && installation=installationMake || true

# Modifications

apiVersion()
{
	( grep 'set(API_VERSION [0-9.]*)' < CMakeLists.txt | sed -e 's/.*set(API_VERSION //' -e 's/).*//' ; grep API_VERSION= configure.ac | cut -d = -f 2 ) 2> /dev/null | sort -n | tail -1
}

pkgconfeMoi()
{
	local api="`apiVersion`"
	pkgconfer -p "" mdds-$api
}

installationManuelle()
{
	local api="`apiVersion`"
	rm -Rf dest && mkdir -p dest/include
	cp -R include dest/include/mdds-$api
	ln -s mdds-$api/mdds dest/include/mdds
	find dest -name Makefile.am -exec rm {} \;
	sudoku "$SCRIPTS/installer" dest "$dest"
}

installationMake()
{
	local api="`apiVersion`"
	( cd build && sudoku make install )
	sudoku ln -s mdds-$api/mdds "$dest/include/mdds"
}

# Variables

archive="https://gitlab.com/mdds/mdds/-/archive/$version/mdds-$version.tar.bz2"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX="$dest" ..

echo Compilation… >&2
make

echo Installation… >&2
cd ..
$installation
pkgconfeMoi

sutiliser
