#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=mod_fastcgi

# Historique des versions gérées

v 2.4.6

# Modifications

# Variables

archive="http://www.fastcgi.com/dist/$logiciel-$version.tar.gz"
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
destApache="`apxs -q LIBEXECDIR | sed -E 's#/(modules|libexec)##g'`"
sed < Makefile.AP2 > Makefile -e "s#/usr/local/apache2#$destApache#"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
varap()
{
	"`apxs -q SBINDIR`/`apxs -q TARGET`" -V | sed -e "/$1/"'!d' -e 's/^[^"]*"//' -e 's/"[^"]*$//'
}
conf="`varap SERVER_CONFIG_FILE`"
echo "$conf" | grep -q ^/ || conf="`varap HTTPD_ROOT`/$conf"
sed -e '/^LoadModule.*fastcgi/d' -e '/# LoadModule/a\
LoadModule fastcgi_module modules/mod_fastcgi.so
' < "$conf" > "$TMP/$$/httpd.conf" && sudo tee < "$TMP/$$/httpd.conf" "$conf" > /dev/null

rm -Rf "$TMP/$$"
