#!/bin/sh

SCRIPTS="`command -v "$0"`" ; [ -x "$SCRIPTS" -o ! -x "$0" ] || SCRIPTS="$0" ; case "`basename "$SCRIPTS"`" in *.*) true ;; *sh) SCRIPTS="$1" ;; esac ; absolutiseScripts() { case "$SCRIPTS" in /*) true ;; *) SCRIPTS="$1/$SCRIPTS" ;; esac ; } ; delie() { while [ -h "$SCRIPTS" ] ; do SCRIPTS0="$SCRIPTS" ; SCRIPTS="`readlink "$SCRIPTS"`" ; absolutiseScripts "`dirname "$SCRIPTS0"`" ; done ; } ; absolutiseScripts "`pwd`" ; delie ; SCRIPTS="`dirname "$SCRIPTS"`" ; delie
. "$SCRIPTS/util.sh"

destsys=/usr/local/share/fonts/

set -e

logiciel=msfonts
version="0.0.1"

destiner

prerequis="curl cabextract fontconfig"
prerequis

cd /tmp/
rm -Rf msfonts
mkdir msfonts
cd msfonts

mkdir paquets
cd paquets
#curl -o /tmp/0.exe "http://cznic.dl.sourceforge.net/project/mscorefonts2/cabs/PowerPointViewer.exe"
#curl -o /tmp/1.exe "http://skylink.dl.sourceforge.net/project/mscorefonts2/cabs/EUupdate.EXE"
curl -O https://www.freedesktop.org/software/fontconfig/webfonts/webfonts.tar.gz
find . -name \*.tar.gz -exec tar xzf {} \;

mkdir ../polices
cd ../polices
find ../paquets \( -name \*.exe -o -name \*.EXE \) -exec cabextract {} \;

echo "========"

SANSSU=0 sudo mkdir -p "$destsys"
find . -name \*.ttf -o -name \*.TTF
find . -name \*.ttf -o -name \*.TTF -exec sudo cp {} "$destsys/" \;

SANSSU=0 sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH "`command -v fc-list`"

sudo mkdir "$dest" # Pour poser notre témoin de bonne installation.
sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
