#!/bin/sh

set -e

~/src/installs/cabextract

cd /tmp/
mkdir msfonts
cd msfonts
curl -o /tmp/0.exe "http://cznic.dl.sourceforge.net/project/mscorefonts2/cabs/PowerPointViewer.exe"
curl -o /tmp/1.exe "http://skylink.dl.sourceforge.net/project/mscorefonts2/cabs/EUupdate.EXE"
cabextract /tmp/0.exe
cabextract ppviewer.cab
cabextract /tmp/1.exe
echo "========"
ls -l *.ttf *.TTF
sudo cp *.ttf *.TTF /usr/share/fonts/
fc-list
