#!/bin/sh

dest=/usr/local/share/fonts/

set -e

~/src/installs/cabextract
PATH=$HOME/local/bin:/usr/local/bin:$PATH

cd /tmp/
mkdir msfonts
cd msfonts

mkdir paquets
cd paquets
#curl -o /tmp/0.exe "http://cznic.dl.sourceforge.net/project/mscorefonts2/cabs/PowerPointViewer.exe"
#curl -o /tmp/1.exe "http://skylink.dl.sourceforge.net/project/mscorefonts2/cabs/EUupdate.EXE"
curl -O https://www.freedesktop.org/software/fontconfig/webfonts/webfonts.tar.gz
find . -name \*.tar.gz -exec tar xzf {} \;

mkdir ../polices
cd ../polices
find ../paquets \( -name \*.exe -o -name \*.EXE \) -exec cabextract {} \;

echo "========"

sudo mkdir -p "$dest"
find . -name \*.ttf -o -name \*.TTF
find . -name \*.ttf -o -name \*.TTF -exec sudo cp {} "$dest/" \;

sudo fc-list
