#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.sh"

inclure readline

logiciel=mysql

# Historique des versions gérées

v 5.0.24a && prerequis="readline" || true
v 5.0.51 && OPTIONS_CONF="--without-editline --with-readline=yes --with-charset=utf8 CPPFLAGS=-I$INSTALLS/include" && modifs=poumReadline || true
v 5.1.46 && OPTIONS_CONF= || true
v 5.1.50 && OPTIONS_CONF= || true
v 5.5.18 && prerequis="readline cmake" && OPTIONS_CONF="-DWITH_LIBEDIT=OFF -DWITH_READLINE=ON -DWITH_UNIT_TESTS=OFF" && modifs="poumReadline cheminsInstallDb" || true
v 5.5.32 && OPTIONS_CONF="-DWITH_LIBEDIT=OFF -DWITH_READLINE=ON -DWITH_UNIT_TESTS=OFF" && modifs="poumReadline cheminsInstallDb" || true
v 5.6.15 && modifs="$modifs inclusionsEnOrdre mesParamsInit" || true

vmaj="`echo $version | sed -e 's#^\([^.]*.[^.]*\).*#\1#'`"

# Modifications

mesParamsInit()
{
	# Leur foutu démarreur ignore royalement tous les paramètres qu'on lui passe. Résultat, impossible de configurer une base hors de $INSTALLS.
	# Il y a apparemment un mysql-multi.server.sh: à voir si ça ne ferait pas l'affaire.
	filtrer support-files/mysql.server.sh sed -e '/parse_server_arguments[^(]*$/s/$/ "$@"/'
}

poumReadline()
{
	rm -Rf include/readline # Leur version intégrée possède une définition pour laquelle dans mysql.cc ils disent justement « comme cette définition n'existe pas dans readline, on la définit ici » et du coup doublon et boum. On utilise une vraie readline, mais leur include intégré passe devant nos CPPFLAGS, il faut donc le faire sauter.
}

inclusionsEnOrdre()
{
	# Évidemment ils n'ont jamais songé qu'on pouvait avoir installé une vieille version (ou une nouvelle des biblios externes intégrées), et que le CFLAGS ferait prendre le pas à leurs include sur les include embarqués.
	preCFlag "-I. -I./include -I../include -I../../include -I`pwd`/extra/yassl/include"
}

cheminsInstallDb()
{
	# Chez Oracle, ce sont de bien priètres intégrateurs.
	for i in scripts/mysql_install_db.*
	do
		filtrer "$i" sed \
			-e "s#@prefix@#$dest#g" \
			-e "s#@bindir@#$dest/bin#g" \
			-e "s#@libexecdir@#$dest/bin#g" \
			-e "s#@pkgdatadir@#$dest/share#g" \
			-e "s#@scriptdir@#$dest/bin#g"
	done
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive=http://mirrors.ircam.fr/pub/mysql/Downloads/MySQL-$vmaj/$logiciel-$version.tar.gz
archive=http://mirrors.dotsrc.org/mysql/Downloads/MySQL-$vmaj/$logiciel-$version.tar.gz

[ -d "$dest" ] && exit 0

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if pge $version 5.5.18
then
	cmake -DCMAKE_INSTALL_PREFIX="$dest" $OPTIONS_CONF
else
	./configure --prefix="$dest" $OPTIONS_CONF
fi

echo Compilation… >&2
make
plugins=
pge $version 5.1.50 && pge 5.2 $version && plugins='plugin-load=innodb=ha_innodb_plugin.so'
cat <<TERMINE > my.cnf.exemple
# https://mariadb.com/blog/starting-mysql-low-memory-virtual-machines
# http://www.tocker.ca/2014/03/10/configuring-mysql-to-use-minimal-memory.html

[mysqld]
datadir=$HOME/var/mysql
performance_schema = off # LE truc dont se passer sur petites machines en 5.6 (bouffe d'office 350 Mo de RAM).
innodb_buffer_pool_size = 8M
innodb_log_buffer_size = 1M
key_buffer_size = 10K
$plugins

[server]
bind-address = 127.0.0.1
max_connections = 20
TERMINE

echo Installation… >&2
sudo make install
# À partir de la 5.5, avec le passage d'Oracle et à CMake, ça devient du grand n'importe quoi côté organisation du système de fichiers.
sudo rm -Rf "$dest/mysql-test" "$dest/sql-bench"
[ -d "$dest/scripts" ] && sudo mv "$dest/scripts/"* "$dest/bin/" && sudo rm -Rf "$dest/scripts"
[ -d "$dest/support-files" ] && sudo mkdir -p "$dest/share/mysql/" && sudo mv "$dest/support-files/"* "$dest/share/mysql/" && sudo rm -Rf "$dest/support-files"
sudo cp my.cnf.exemple "$dest/"
sutiliser "$logiciel-$version"

#[ -d "$HOME/var/mysql" ] || mysql_install_db --datadir="$HOME/var/mysql"
# Pour une machine déja installée:
#sudo mysql_upgrade -uroot -p

rm -Rf "$TMP/$$"

echo "# Si vous passez de la 5.5 à la 5.6, n'oubliez pas de recréer les tables oubliées par l'installeur officiel. Sinon votre $HOME/var/mysql/`hostname`.err va se remplir de traces. Cf. http://dba.stackexchange.com/questions/54608/innodb-error-table-mysql-innodb-table-stats-not-found-after-upgrade-to-mys" >&2
