#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; }
calcScripts() { absolutiseScripts "`command -v "$1"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`" ; }
calcScripts "$0"
. "$SCRIPTS/util.sh"

logiciel=ncurses
case `basename "$0"` in
	ncursesw)
		logiciel=ncursesw
		;;
esac
OPTIONS_CONF="$OPTIONS_CONF --enable-widec"

v 5.9 && prerequis="pkgconfig" && modifs="pointeurs fpic avecPkgconfig" || true

archive=http://ftp.gnu.org/pub/gnu/ncurses/ncurses-$version.tar.gz

dest=$INSTALLS/$logiciel-$version

avecPkgconfig()
{
	# tmux (pour ne citer que lui) teste via pkg-config ncurses puis ncursesw; sans pkg-config il n'essaie de trouver, à la mimine, que ncurses. Du coup installons le .pc, qui rendra plus simple le configure de nombre de logiciels.
	# Cependant l'algo pourri du configure de ncurses 5.9 essaie d'installer le .pc dans ../lib/pkgconfig par rapport à l'exécutable pkg-configk, ce qui contrevient à notre organisation (chaque logiciel s'installe avec ses fichiers dans son arbo propre $INSTALLS/paquet-version, et des liens symboliques sont ensuite tirés de l'arbo générale $INSTALLS).
	# En effet si on le laisse faire, il va nous placer ses .pc à des endroits périlleux:
	# - si $prerequis inclut pkgconfig, le PATH trouvera $INSTALLS/pkgconfig-version/bin/pkg-config, et donc le .pc sera installé dans $INSTALLS/pkgconfig-version/lib/pkgconfig, répertoire qui disparaîtra si on change de version de pkgconfig.
	# - si on bidouille pour le faire pointer sur $INSTALLS/bin/pkg-config (ex.: prerequis dans un sous-shell pour ne pas toucher notre $PATH, et $PATH modifié manuellement pour inclure $INSTALLS/bin), c'est un peu mieux (il ira taper dans $INSTALLS/lib/pkgconfig), mais le $INSTALLS/lib/pkgconfig/ncursesw.pc sera non pas un lien symbolique vers un .pc installé avec notre ncurses, mais le fichier final de la dernière version installée de ncurses. Résultat, si on veut basculer vers une version plus ancienne, on n'a plus son .pc.
	# Donc il nous faut corriger ce configure pourri.
	filtrer configure awk \
		'
			{ print; }
			heredoc { if($0 == heredoc) heredoc = ""; next; }
			/<</ { heredoc = $0; sub(/.*<<[ \\]*/, "", heredoc); sub(/ .*/, "", heredoc); }
			/^ *if / { ++niveau; }
			/^ *fi/ { --niveau; }
			/enable_pc_files=/ && !ou { ou = 1; }
			ou == 1 && !niveau {
				ou = 2;
				destpc = "'"$dest/lib/pkgconfig"'";
				print "enable_pc_files=yes ; PKG_CONFIG_LIBDIR="destpc" ; echo \"$as_me:"NR": *** forçage fichiers .pc dans "destpc" ***\" >&5 ; echo \"forçage fichiers .pc: OUI MON GARS, dans "destpc"\" >&6";
			}
		'
}

pointeurs()
{
	filtrer ./c++/cursesf.h sed -e '/NCursesUserForm.*NCursesFormField/s/NCursesFormField/NCursesFormField */'
	filtrer ./c++/cursesm.h sed -e '/NCursesUserMenu.*NCursesMenuItem/s/NCursesMenuItem/NCursesMenuItem */'
}

[ -d "$dest" ] && exit 0

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" --with-shared --without-debug --without-normal $OPTIONS_CONF

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
