#!/bin/bash
# Copyright (c) 2004-2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

if [ "$SCRIPTS" = "" ] ; then SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS" ; fi
. "$SCRIPTS/util.bash"

inclure lesstif

logiciel=nedit

# Historique des versions gérées

version=5.4
modifs=corrigerMotif

version=5.5

dest=/usr/local/$logiciel-$version
archive=ftp://cri.univ-tlse1.fr/pub/unix/nedit/NEdit/v${version//./_}/$logiciel-$version-src.tar.bz2

# Modifications

corrigerMotif()
{
	filtrer makefiles/Makefile.macosx sed -e 's/^CFLAGS=/CFLAGS=-DBUILD_UNTESTED_NEDIT /' -e 's/^MOTIFLINK=/@MOTIFLINK=/' -e 's/^#MOTIFLINK=/MOTIFLINK=/' -e 's/^@MOTIFLINK=/#MOTIFLINK=/'
	#MOTIFLINK=-L${MOTIFDIR}/lib -lXm.2
}

# Boulot

[ -d "$dest" ] && exit 0

if [[ $version = *-* ]] ; then
	obtenirEtAllerDansCvs -d $version $archive_cvs
else
	obtenirEtAllerDans "$archive"
fi

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
#./configure --prefix="$dest"

echo Compilation… >&2
make macosx

echo Installation… >&2
sudo sh << TERMINE
mkdir -p $dest/bin
cp source/nedit $dest/bin
cp source/nc $dest/bin/ned
mkdir -p $dest/man/man1
cp doc/*.man $dest/man/man1/
mv $dest/man/man1/nc.man $dest/man/man1/ned.man
TERMINE
sudo utiliser "$logiciel-$version"

rm -Rf /tmp/$$
