#!/bin/bash
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

inclure ocaml
inclure gc

logiciel=neko

# Historique des versions gérées

version=2006-12-26
modifs=adapmac
OPTIONS_CONF=()

version=2008-06-13
modifs="adapmoi virerTout"
OPTIONS_CONF=()

# Modifications

adapmac()
{
	uname | grep -q Darwin || return
	#filtrer Makefile sed -e 's/-shared/-dynamiclib -flat_namespace -undefined suppress/'
	filtrer Makefile sed -e 's/^ *# *\(MACOSX *= *1\)/\1/'
}

adapmoi()
{
	filtrer Makefile sed -e '/CFLAGS =/s#$# -I/usr/local/include -L/usr/local/lib#' -e '/LIBNEKO_LIBS =/s/-ldl//'
	filtrer libs/std/process.c sed -e 's#wait.h#sys/wait.h#'
}

virerTout()
{
	rm -Rf libs/mod_neko
}

# Variables

archive="$logiciel-$version.tar.bz2"
archive_cvs="cvs://anonymous@cvs.motion-twin.com:/cvsroot:$logiciel"
dest=/usr/local/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

#echo Configuration… >&2

echo Compilation… >&2
yes s | make

echo Installation… >&2
sudo sh -c "mkdir -p '$dest/bin' '$dest/lib' ; cp bin/neko* '$dest/bin/' ; cp bin/*.ndll bin/lib* '$dest/lib/'"
sutiliser $logiciel-$version

rm -Rf /tmp/$$
