#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

inclure libpng
inclure libjpeg
inclure libtiff

logiciel=netpbm

# Historique des versions gérées

version=10.26.30

# Modifications

# Variables

dest="/usr/local/$logiciel-$version"
archive=http://belnet.dl.sourceforge.net/sourceforge/$logiciel/$logiciel-$version.tgz

[ -d "$dest" ] && exit 0

if [[ $version = *-* ]] ; then
	obtenirEtAllerDansCvs -d $version $archive_cvs
else
	obtenirEtAllerDans "$archive"
fi

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
sed \
	-e '/^PKGDIR_DEFAULT /s#=.*$#= '"$dest"'#' \
	-e '/^ZLIB /s#=.*$#= libz.dylib#' \
	-e '/^TIFFLIB /s#=.*$#= libtiff.dylib#' \
	-e '/^TIFFHDR_DIR /s#=.*$#= /usr/local/include#' \
	-e '/^JPEGLIB /s#=.*$#= libjpeg.dylib#' \
	-e '/^JPEGHDR_DIR /s#=.*$#= /usr/local/include#' \
	-e '/^PNGLIB /s#=.*$#= libpng.dylib#' \
	-e '/^PNGHDR_DIR /s#=.*$#= /usr/local/include#' \
	< Makefile.config.in > Makefile.config
cat << TERMINE >> Makefile.config
DEFAULT_TARGET = nonmerge
NETPBMLIBTYPE=dylib
NETPBMLIBSUFFIX=dylib
STATICLIB_TOO=n
NETPBMLIB_RUNTIME_PATH=
CC = cc -no-cpp-precomp
CFLAGS_SHLIB = -fno-common
LDSHLIB = -dynamiclib -install_name \$(NETPBM_RUNTIME_PATH)/libnetpbm.\$(MAJ).dylib
LINKERISCOMPILER = Y
TERMINE

echo Compilation… >&2
make

echo Installation… >&2
sudo make package pkgdir="$dest"
sudo utiliser "$logiciel-$version"

rm -Rf /tmp/$$
