#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

v 1.9.1 && modifs="" && prerequis="pcre openssl zlib" || true
v 1.10.1 || true
v 1.11.5 || true
v 1.12.2 || true
v 1.15.8 || true
v 1.15.12 || true

archive="http://nginx.org/download/nginx-$version.tar.gz"

# Variables

moduleNginxSiOption()
{
	local o="$1"
	local s="$2"
	if option "$o"
	then
		case "$s" in
			http*://*) # Module externe
				local suffixe="`echo "$s" | sed -e 's#.*/[^.]*##' -e 's#.*\.[^.][^.][^.][^.][^.]*##'`"
				local nomArchive="`basename "$s"`"
				if echo "$nomArchive" | egrep -vqe '-[0-9]+\.[0-9]+(\.[0-9]+)*(\.[a-z][a-z0-9]*)+$' # Si le nom de l'archive ne porte pas de numéro de version (ex.: git), on lui en donne un daté.
				then
					nomArchive="nginx_module_$o.`date +%Y%m%d`$suffixe"
				fi
				local d="`obtenirEtAllerDans "$s" "$nomArchive" ; pwd`"
				[ -n "$d" -a -d "$d" ] || return 1
				OPTIONS_CONF="$OPTIONS_CONF --add-module=$d"
				;;
			*) # Module interne
				OPTIONS_CONF="$OPTIONS_CONF --with-$s"
				;;
		esac
	fi
}

OPTIONS_CONF=

moduleNginxSiOption realip http_realip_module
moduleNginxSiOption upstreamcheck https://github.com/yaoweibin/nginx_upstream_check_module/archive/master.zip
moduleNginxSiOption headersmore https://github.com/openresty/headers-more-nginx-module/archive/master.zip

# Boulot

destiner

prerequis

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif "$@" ; done

echo Configuration… >&2
./configure --prefix="$dest" --with-http_ssl_module --with-cc-opt="$CPPFLAGS $CFLAGS" --with-ld-opt="$LDFLAGS" $OPTIONS_CONF

echo Compilation… >&2
make
for modif in true $modifspostcompil ; do $modif "$@" ; done

echo Installation… >&2
sudo make install

sutiliser
