#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; }
calcScripts() { absolutiseScripts "`command -v "$1"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`" ; }
calcScripts "$0"
. "$SCRIPTS/util.sh"

logiciel=nodejs

v 0.10.33 && prerequis="libexecinfo" || true
v 0.12.4 && prerequis="libexecinfo" && modifs="pthreadtInt doubleResult neReconstruisPasTout" || true
v 5.3.0 && prerequis="libexecinfo" && modifs="cstds neReconstruisPasTout sansGold" || true

archive="http://nodejs.org/dist/v$version/node-v$version.tar.gz"

sansGold()
{
    # https://github.com/nodejs/node/issues/4212
    GYP_DEFINES="linux_use_gold_flags=0 $GYP_DEFINES"
    export GYP_DEFINES
}

cstds()
{
	# FILE est utilisé sans être déclaré.
	filtrer deps/v8/src/base/platform/platform.h sed -e '/include <vector>/a\
#include <cstdio>
'
	filtrer deps/v8/src/log-utils.h sed -e '/#include "src\/allocation/{
i\
#include <cstdio>
i\
#include <cstdarg>
}'
}

pthreadtInt()
{
	filtrer deps/v8/src/base/platform/platform-posix.cc sed -e '/return static_cast<int>.pthread_self...;/s/pthread_self/(int64_t)pthread_self/'
}

doubleResult()
{
	filtrer deps/v8/src/base/platform/platform-freebsd.cc sed -e '/GetSharedLibraryAddresses/,/^}/{
s/> result/> retour/
s/return result/return retour/
s/result.push_back/retour.push_back/
}'
}

neReconstruisPasTout()
{
	filtrer Makefile sed -e '/^install:/s/:.*/:/'
}

dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

prerequis

if true
then
	cd "$TMP/node-v$version"
	echo "EN AVANT, FAITES-VOUS PLAISIR" >&2
	bash
else

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
MAKE="make -j 3" make

fi

echo Installation… >&2
# Bon, de toute façon cet abruti recompile tout. Le make précédent est donc inutile.
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
