#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

prerequis="make \\"

v 3.09.3 && modifs="sansGcc" || true
v 3.10.2 || true
v 3.11.2 || true
v 3.12.0 || true
v 3.12.1 || true
v 4.03.0 && modifs="" || true
v 4.04.1 && modifs="installBytePourrie" || true
v 4.12.0 && modifs= || true

# Modifications

installBytePourrie()
{
	patch <<TERMINE
--- Makefile	2017-04-13 17:39:53.000000000 +0200
+++ Makefile	2017-09-06 21:33:09.000000000 +0200
@@ -248,11 +248,10 @@
 	if test -n "\$(WITH_OCAMLDOC)"; then (cd ocamldoc; \$(MAKE) install); fi
 	if test -n "\$(WITH_DEBUGGER)"; then (cd debugger; \$(MAKE) install); fi
 	cp config/Makefile \$(INSTALL_LIBDIR)/Makefile.config
-	if test -f ocamlopt; then \$(MAKE) installopt; else \\
+	if test -f ocamlopt; then \$(MAKE) installopt; fi
 	   cd \$(INSTALL_BINDIR); \\
-	   ln -sf ocamlc.byte\$(EXE) ocamlc\$(EXE); \\
-	   ln -sf ocamllex.byte\$(EXE) ocamllex\$(EXE); \\
-	   fi
+	   [ -e ocamlc\$(EXE) ] || ln -sf ocamlc.byte\$(EXE) ocamlc\$(EXE); \\
+	   [ -e ocamllex\$(EXE) ] || ln -sf ocamllex.byte\$(EXE) ocamllex\$(EXE)
 
 # Installation of the native-code compiler
 installopt:
TERMINE
}

sansGcc()
{
	command -v gcc > /dev/null 2>&1 || filtrer configure sed -e '/aspp=.*gcc/s/gcc/cc/g'
}

# Variables

version_maj="`echo "$version" | sed -e 's/\.[^.]*$//'`"
archive="http://caml.inria.fr/pub/distrib/$logiciel-$version_maj/$logiciel-$version.tar.gz"

prerequis

destiner

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure -prefix "$dest"

echo Compilation… >&2
make world
make opt

echo Installation… >&2
sudo make install

sutiliser
