#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.sh"

logiciel=ocaml

# Historique des versions gérées

v 3.09.3 && modifs="sansGcc" || true
v 3.10.2 || true
v 3.11.2 || true
v 3.12.0 || true
v 3.12.1 || true
v 4.03.0 && modifs="" || true

# Modifications

sansGcc()
{
	command -v gcc > /dev/null 2>&1 || filtrer configure sed -e '/aspp=.*gcc/s/gcc/cc/g'
}

# Variables

version_maj="`echo "$version" | sed -e 's/\.[^.]*$//'`"
archive="http://caml.inria.fr/pub/distrib/$logiciel-$version_maj/$logiciel-$version.tar.gz"
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure -prefix "$dest"

echo Compilation… >&2
make world
make opt

echo Installation… >&2
sudo make install
sutiliser $logiciel-$version

rm -Rf $TMP/$$
