#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

prerequis

v 1.1.1.1 && prerequis="libao r10015 libogg 1.1.2 libvorbis 1.1.1 vorbis-tools 1.1.1" || true
v 1.1.1.2 && prerequis="libao 0.8.6 libogg 1.1.3 libvorbis 1.1.2 vorbis-tools 1.1.1" || true
v 1.4.0.1 && prerequis="libao 1.0.0 libogg 1.2.1 libvorbis 1.3.2 vorbis-tools 1.4.0" || true
v 1.4.0.2 && prerequis="libao 1.1.0 libogg 1.2.2 libvorbis 1.3.2 vorbis-tools 1.4.0" || true
v 1.4.0.3 && prerequis="libao 1.1.0 libogg 1.3.0 libvorbis 1.3.3 vorbis-tools 1.4.0" || true
v 1.4.0.4 && prerequis="libao 1.2.0 libogg 1.3.2 libvorbis 1.3.4 vorbis-tools 1.4.0" || true
v 1.4.0.5 && prerequis="libao 1.2.0 libogg 1.3.3 libvorbis 1.3.6 vorbis-tools 1.4.0" || true
v 1.4.0.6 && prerequis="libao 1.2.0 libogg 1.3.4 libvorbis 1.3.6 vorbis-tools 1.4.0" || true
v 1.4.2.1 && prerequis="libao 1.2.0 libogg 1.3.5 libvorbis 1.3.7 vorbis-tools 1.4.2" || true
v 1.4.2.2 && prerequis="libao 1.2.2 libogg 1.3.6 libvorbis 1.3.7 vorbis-tools 1.4.3" || true

prerequis
destiner

# Nous sommes une coquille vide.
sudoku mkdir -p "$dest"

sutiliser
