#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 6.0.1 && prerequis="openssl < 3 zlib" && modifs="pasfortiche" || true
v 7.8.1 || true
v 7.9.1 || true
v 8.0.1 || true
v 8.1.1 || true
# À partir de là les serveurs en diffie-hellman-group*-exchange-sha1 sont (par défaut) rejetés.
# https://www.openssh.com/legacy.html
v 8.2.1 || true
v 8.4.1 || true
v 8.6.1 || true

# Modifications

# Variables

version_p="`echo "$version" | sed -e 's/\.\([0-9][0-9]*\)$/p\1/'`"
archive=http://ftp.fr.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-$version_p.tar.gz

prerequisOpenssl

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
# privsep-path: si on est installés en tant que non root, juste pour avoir la partie cliente d'OpenSSH, /var/empty va être difficile à créer.
./configure --prefix="$dest" --with-privsep-path=/tmp/empty

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
