#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=openssl

# Historique des versions gérées

version=0.9.8g

version=1.0.0

version=1.0.0a
mac && archis=oui
modifspostconf="dyld105postconf"

version=1.0.0e
modifs=perlredir

v 1.0.1e && modifs="perlredir sansdoc" || true
v 1.0.1g || true
v 1.0.1h || true
v 1.0.1j || true
v 1.0.2c || true
v 1.0.2d || true
v 1.0.2f || true

# Modifications

perlredir()
{
	# Le traiteur assembleur en Perl s'emmêle les pinceaux lorsque la sortie standard est un SSH.
	filtrer crypto/perlasm/x86_64-xlate.pl sed -e '/$stddev!=$outdev/s//& || (!$stddev \&\& !defined($outdev))/'
}

# Perl 5.18.0 est un peu trop méchant (plus strict sur certains points).
# https://github.com/openembedded/oe-core/blob/master/meta/recipes-connectivity/openssl/openssl-1.0.1e/openssl-fix-doc.patch
docItem()
{
	find . -name \*.pod -print0 | xargs -0 grep -l '^=item [0-9]' | while read f
	do
		filtrer "$f" sed -e 's#^=item \([0-9]\)#=item Z<>\1#'
	done
}

docItemComplet()
{
	rustineDocItemComplet="`obtenir http://rt.openssl.org/Ticket/Attachment/36986/20049/ openssl.bogue3057.diff`"
	patch -p1 < "$rustineDocItemComplet" || true

	rustineDocItemComplet="`obtenir http://dl.dropboxusercontent.com/u/8224157/public/tmp/openssl-1.0.1c-pod_syntax_error.patch`"
	patch -p1 < "$rustineDocItemComplet" || true

	rustineDocItemComplet="`obtenir "http://pkgs.fedoraproject.org/cgit/openssl.git/plain/openssl-1.0.1e-backports.patch?id2=HEAD" openssl.bogueqqc.diff`"
	patch -p1 < "$rustineDocItemComplet" || true
}

sansdoc()
{
	# Cette petite histoire de l'incompat entre les docs d'OpenSSL et Perl 5.18 m'échaude furieusement, après les deux tentatives docItem et docItemComplet on a encore un gruyère. On zappe donc tout, merde.
	filtrer Makefile.org sed -e '/^install: /s/install_docs//g'
}

dyld105postconf()
{
	mac || return 0
	filtrer Makefile sed -e "/^SHARED_LDFLAGS=/s#\$# $LDFLAGS#"
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive=http://www.openssl.org/source/$logiciel-$version.tar.gz

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

if [ "$archis" = oui -a "`sysctl -n hw.optional.x86_64`" = 1 ]
then
	cp -R . ../$logiciel-$version-x86_64
	cp -R . ../$logiciel-$version-i386
	cd ../$logiciel-$version-x86_64
	./Configure darwin64-x86_64-cc shared --prefix="$dest" --openssldir="$dest"
	for modif in true $modifspostconf ; do $modif ; done
	make
	sudo make install
	sudo rm -Rf "$dest.x86_64"
	sudo mv "$dest" "$dest.x86_64"
	cd ../$logiciel-$version-i386
	./config shared --prefix="$dest" --openssldir="$dest"
	for modif in true $modifspostconf ; do $modif ; done
	make
	sudo make install
	cd "$dest"
set -x
	diff -rq . "$dest.x86_64" 2> /dev/null | sed -e 's/^Files //' -e 's/ and .*differ//' | while read i
	do
		if [ ! -L "$i" ]
		then
			suffixe=
			nom="`basename "$i"`"
			[[ "$nom" = *.* ]] && suffixe=".${nom##*.}"
			case "$suffixe" in
				.h)
					diff -D __x86_64__ "$i" "$dest.x86_64/$i" > "$TMP/$$/temp.diffD" || true
					sudo sh -c "cat $TMP/$$/temp.diffD > $i"
					;;
				*)
					lipo -create "$i" "$dest.x86_64/$i" -output "$TMP/$$/temp.lipo$suffixe" && sudo sh -c "chmod u+w $i ; cat $TMP/$$/temp.lipo$suffixe > $i" # Les engines sont installés en non inscriptibles, ce qui nous embête bien.
					;;
			esac
		fi
	done
	sudo rm -Rf "$dest.x86_64"
else
	echo Configuration… >&2
	./config shared --prefix="$dest" --openssldir="$dest"
	for modif in true $modifspostconf ; do $modif ; done
	
	echo Compilation… >&2
	make
	
	echo Installation… >&2
	sudo make install
fi

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
