#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 0.9.8.7 && prerequis="perl >= 5 \\" && modifs="multiarch sansdoc" || true
v 0.9.8.13 || true # Première version à ne pas planter sur une Ubuntu 18.04 GCC 7.3.0 64 bits (avant, un bout d'assembleur mal ficelé vautre).
v 0.9.8.33 || true
v 1.0.0 || true
v 1.0.0.1 || true
mac && archis=oui
modifspostconf="dyld105postconf"

v 1.0.0.5 && modifs="multiarch perlredir sansdoc" || true
v 1.0.1.5 && modifs="multiarch perlredir sansdoc uniquementPrerequis" || true
v 1.0.1.7 || true
v 1.0.1.8 || true
v 1.0.1.10 || true
v 1.0.2.3 || true
v 1.0.2.4 || true
v 1.0.2.6 || true
# Corrige une faille béante au 2016-03-01, mais mon vieux mod_php a l'air d'être lié à /usr/local/lib/libopenssl.so, et ne trouve plus dans cette version ses fonctions SSLv2_…. Il faudrait sans doute le recompiler, mais bon, un 5.2, quand même…
v 1.0.2.7 || true
v 1.0.2.8 || true
v 1.0.2.11 || true
v 1.0.2.14 || true
v 1.0.2.15 || true
v 1.0.2.16 || true
v 1.0.2.17 || true
v 1.0.2.18 || true
v 1.0.2.19 || true
v 1.0.2.20 || true
v 1.0.2.21 || true
v 1.1.0.3 || true
v 1.1.0.4 || true
v 1.1.0.7 || true
v 1.1.0.8 || true
v 1.1.0.9 || true
v 1.1.0.10 || true
v 1.1.0.11 || true
v 1.1.0.12 || true
v 1.1.1.2 || true
v 1.1.1.3 || true
v 1.1.1.4 || true
v 1.1.1.5 || true
v 1.1.1.6 || true
v 1.1.1.7 || true

# Modifications

perlredir()
{
	# Le traiteur assembleur en Perl s'emmêle les pinceaux lorsque la sortie standard est un SSH.
	filtrer crypto/perlasm/x86_64-xlate.pl sed -e '/$stddev!=$outdev/s//& || (!$stddev \&\& !defined($outdev))/'
}

# Perl 5.18.0 est un peu trop méchant (plus strict sur certains points).
# https://github.com/openembedded/oe-core/blob/master/meta/recipes-connectivity/openssl/openssl-1.0.1e/openssl-fix-doc.patch
docItem()
{
	find . -name \*.pod -print0 | xargs -0 grep -l '^=item [0-9]' | while read f
	do
		filtrer "$f" sed -e 's#^=item \([0-9]\)#=item Z<>\1#'
	done
}

docItemComplet()
{
	rustineDocItemComplet="`obtenir http://rt.openssl.org/Ticket/Attachment/36986/20049/ openssl.bogue3057.diff`"
	patch -p1 < "$rustineDocItemComplet" || true

	rustineDocItemComplet="`obtenir http://dl.dropboxusercontent.com/u/8224157/public/tmp/openssl-1.0.1c-pod_syntax_error.patch`"
	patch -p1 < "$rustineDocItemComplet" || true

	rustineDocItemComplet="`obtenir "http://pkgs.fedoraproject.org/cgit/openssl.git/plain/openssl-1.0.1e-backports.patch?id2=HEAD" openssl.bogueqqc.diff`"
	patch -p1 < "$rustineDocItemComplet" || true
}

sansdoc()
{
	# Cette petite histoire de l'incompat entre les docs d'OpenSSL et Perl 5.18 m'échaude furieusement, après les deux tentatives docItem et docItemComplet on a encore un gruyère. On zappe donc tout, merde.
	for f in Makefile.org Configurations/unix-Makefile.tmpl
	do
		if [ -e "$f" ]
		then
			filtrer "$f" sed -e '/^install: /s/install_docs//g'
		fi
	done
}

dyld105postconf()
{
	mac || return 0
	filtrer Makefile sed -e "/^SHARED_LDFLAGS=/s#\$# $LDFLAGS#"
}

configManuel()
{
	arch="$1" ; shift
	pf="`uname | tr A-Z a-z`"
	case "$pf-$arch" in
		darwin-x86_64) pf=darwin64 ;;
	esac
	./Configure "$pf-$arch-cc" "$@"
}

# Variables

v_alpha="`echo "$version" | awk -F . 'BEGIN{t="abcdefghijklmnopqrstuvwxyz"}{c="";n=$4;while(n>25){n-=25;c=c"z"}if(n)c=c""substr(t,n,1);print $1"."$2"."$3""c}'`"
v_maj="`echo "$v_alpha" | tr -d 'a-z'`"
archive=http://www.openssl.org/source/$logiciel-$v_alpha.tar.gz
# Difficile maintenant de trouver la source sur un serveur HTTP non 'S'.
archive=http://artfiles.org/openssl.org/source/$logiciel-$v_alpha.tar.gz
case "$version" in
	0.9.*) archive="https://ftp.openssl.org/source/old/0.9.x/openssl-$v_alpha.tar.gz" ;;
	1.0.*|1.1.0.*) archive="https://ftp.openssl.org/source/old/$v_maj/openssl-$v_alpha.tar.gz" ;;
esac

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

	echo Configuration… >&2
	config="./config"
	[ -z "$multiarch_arch" ] || config="configManuel $multiarch_arch"
	$config shared --prefix="$dest" --openssldir="$dest"
	for modif in true $modifspostconf ; do $modif ; done
	
	echo Compilation… >&2
	make
	
	echo Installation… >&2
	sudo make install

sutiliser
