#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

# openssl pour libopusurl.
v 0.7 && prerequis="pkgconfig \\ opus libogg openssl" && modifs="sansCompat" || true
v 0.9 || true
v 0.11 || true
v 0.12 || true

# Modifications

sansCompat()
{
	# Sous FreeBSD, ftime est implémenté dans libcompat. Problème: celui-ci n'est pas relocatable, donc ne peut être embarqué dans une biblio.
	# On essaie donc de placer une libcompat recompilée dans le chemin, pour que le lien final se fasse sur elle plutôt que sur la biblio système.
	
	[ `uname` = FreeBSD ] || return 0
	fbsd="`uname -r | cut -d - -f 1`.0"
	sfbsd="https://svnweb.freebsd.org/base/release/$fbsd"
	curl -k -o ftime.c "$sfbsd/lib/libcompat/4.1/ftime.c?view=co"
	cc -c -o ftime.o ftime.c -fPIC
	ar cr libcompat.a ftime.o
	
	LDFLAGS="-L`pwd` $LDFLAGS"
	export LDFLAGS
}

# Variables

archive=http://downloads.xiph.org/releases/opus/$logiciel-$version.tar.gz

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
