#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=opus-tools

# Historique des versions gérées

v 0.1.5 && prerequis="opus ogg" && modifs="composer" || true
v 0.1.6 || true
v 0.1.9 && prerequis="opus ogg flac" || true

prerequis

# Modifications

composer()
{
	patch -p0 <<TERMINE
--- src/opusenc.c	2017-02-05 21:46:39.000000000 +0100
+++ src/opusenc.c	2017-02-05 21:48:07.000000000 +0100
@@ -151,6 +151,8 @@
   printf(" --comment          Add the given string as an extra comment\n");
   printf("                      This may be used multiple times\n");
   printf(" --artist           Author of this track\n");
+  printf(" --composer         Composer of this track\n");
+  printf(" --track            Track number on the album\n");
   printf(" --title            Title for this track\n");
   printf(" --album            Album or collection this track belongs to\n");
   printf(" --date             Date for this track\n");
@@ -279,6 +280,8 @@
     {"version-short", no_argument, NULL, 0},
     {"comment", required_argument, NULL, 0},
     {"artist", required_argument, NULL, 0},
+    {"composer", required_argument, NULL, 0},
+    {"track", required_argument, NULL, 0},
     {"title", required_argument, NULL, 0},
     {"album", required_argument, NULL, 0},
     {"date", required_argument, NULL, 0},
@@ -541,6 +543,12 @@
         }else if(strcmp(long_options[option_index].name,"artist")==0){
           save_cmd=0;
           comment_add(&inopt.comments, &inopt.comments_length, "artist", optarg);
+        } else if(strcmp(long_options[option_index].name,"composer")==0){
+          save_cmd=0;
+          comment_add(&inopt.comments, &inopt.comments_length, "composer", optarg);
+        } else if(strcmp(long_options[option_index].name,"track")==0){
+          save_cmd=0;
+          comment_add(&inopt.comments, &inopt.comments_length, "track", optarg);
         } else if(strcmp(long_options[option_index].name,"title")==0){
           save_cmd=0;
           comment_add(&inopt.comments, &inopt.comments_length, "title", optarg);
TERMINE
}

# Variables

archive="http://downloads.xiph.org/releases/opus/$logiciel-$version.tar.gz"
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
