#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delictueux() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delictueux ; s="`dirname "$s"`" ; Delictueux ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 1.8.0 && prerequis="glib xft" || true
# https://mail.gnome.org/archives/gtk-i18n-list/2013-June/msg00003.html; et le configure montre qu'il ne voudra pas détecter fontconfig, donc freetype, s'il n'a pas harfbuzz.
# Et l'on recale un harfbuzz+glib tout à la fin pour être sûrs qu'il ne va pas en charger un autre lié par freetype+hb mais sans glib.
v 1.29.3 && modifs="putainDeLibJPEGDeMacOSX" && prerequis="python pkgconfig \\ glib fontconfig >= 2.11 freetype+hb cairo >= 1.12 harfbuzz+glib" || true
v 1.32.3 || true
v 1.35.3 && modifs= || true
v 1.36.5 || true
v 1.36.8 || true
v 1.44.7 && prerequis="meson ninja \\ $prerequis" || true
v 1.49.1 && prerequis="$prerequis fribidi" || true
v 1.50.12 && remplacerPrerequis "fontconfig >= 2.13" || true
v 1.56.3 && remplacerPrerequis "fontconfig >= 2.15" || true
v 1.56.4 || true
v 1.57.0 || true

# Modifications

# Variables

trucz=xz
pge $version 1.32 || trucz=bz2
archive=https://ftp.gnome.org/pub/GNOME/sources/pango/`vmaj $version`/$logiciel-$version.tar.$trucz

destiner

# Petit souci sur ma config
# Harfbuzz et libzip se sont compilées avec une libbz2.a 1.0.7 (et ont donc les symboles BZ2_etc. embarqués), les autres (dont Freetype) à partir du .so 1.0.8 (et requièrent donc un -lbz2).
# Là-dedans pkg-config s'est embrouillé les pédales et oublie de préciser la dépendance.
# En plus l'ami meson en fout un peu partout, il faut donc jongler avec les diverses variables qu'il accepte pour faire passer nos modifications (https://github.com/mesonbuild/meson/issues/6377 ou https://patches.dpdk.org/patch/43897/).
aveclbz2()
{
	filtrer meson.build sed -e "/^common_ldflags = /a\\
common_ldflags += [ '-L$destbzip2/lib', '-lbz2' ]
"
	export LDFLAGS="-L$destbzip2/lib -lbz2 $LDFLAGS" LD_LIBRARY_PATH="$destbzip2/lib:$LD_LIBRARY_PATH" LD="$CC -L$destbzip2/lib -lbz2" CFLAGS="-I$destbzip2/include $CFLAGS"
}
prerequis="bzip2 $prerequis bzip2" && ajouterModif aveclbz2

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if pge $version 1.40
then
	meson build --prefix="$dest"
	make=ninja
	cd build
else
./configure --prefix="$dest" $OPTIONS_CONF
	make=make
fi

echo Compilation… >&2
$make

echo Installation… >&2
sudoku $make install

sutiliser
