#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delicat() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delicat ; s="`dirname "$s"`" ; Delicat ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 8.21 || true
v 8.35 || true
v 8.36 || true
v 8.37 || true
v 8.39 || true
v 8.40 || true
v 8.41 || true
v 8.42 || true
v 8.43 || true
v 8.44 || true
v 8.45 || true
# /!\ Sur de grosses regex (4000 caractères = un gros | sur 400 expressions, cherché sur une base SQLite de 70 Mo) les perfs sont pourries (4x plus lent qu'une PCRE1).
v 10.37 || true
v 10.42 || true
v 10.43 || true
v 10.44 || true
v 10.45 || true
v 10.46 || true

if option cxx
then
	prerequis="$prerequis cxx()"
else
	OPTIONS_CONF="$OPTIONS_CONF --disable-cpp"
fi

# Modifications

# Variables

archive="https://github.com/PCRE2Project/pcre2/releases/download/pcre2-$version/pcre2-$version.tar.gz"
pge $version 10 || archive="https://altushost-swe.dl.sourceforge.net/project/pcre/pcre/$version/pcre-$version.tar.bz2"


destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" --enable-unicode-properties --enable-jit $OPTIONS_CONF # unicodeprops en tout cas connu en 8.39; glib en a besoin; le JIT pour être utilisé de façon optimale depuis lua (pour rspamd).

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
