#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=phpunit

version=3.3.17
modifs="php_bin libBin"

version=3.4.12
modifs="php_bin libBin"

# Modifications

inclure php

php_bin()
{
	grep -v '@php_bin@' . | while read i
	do
		filtrer "$i" sed -e "s#@php_bin@#`command -v php`#g"
	done
}

libBin()
{
	mkdir ../tmpPhpunit
	mv * ../tmpPhpunit
	mkdir bin lib lib/php
	mv ../tmpPhpunit/phpunit.php bin/phpunit
	mv ../tmpPhpunit/PHPUnit lib/php/
	filtrer bin/phpunit sed -e "s#set_include_path(dirname(__FILE__) . PATH_SEPARATOR#set_include_path(dirname(__FILE__) . '/../lib/php' . PATH_SEPARATOR#"
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="http://pear.phpunit.de/get/PHPUnit-$version.tgz"

[ -d "$dest" ] && exit 0

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion
cd PHPUnit-$version

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Installation… >&2
sudo cp -R . "$dest"

sudo utiliser $logiciel-$version
