#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=pijul

# Historique des versions gérées

v 0.2.2016.06.02 && versionComplete="$version@sanakirja txn.debug accessible only in debug mode" && prerequis="rust python < 3 libssh0" && modifs="auPropre pourPseudoCargo vraiesDeps pasDeDepSrc" && inclusionsForcees="ansi_term cookie libc miniz-sys rand num-bigint num-complex num-rational openssl strsim unicode-width" || true

# Modifications

vraiesDeps()
{
	# Pour la version de 2016-06-20.

	# index/fl/at/flate2: miniz y est marqué en optionnel (alors qu'il est obligatoire en 0.2.13). Il faut le repasser en optional: false.
	# index/co/ok/cookie: openssl non optionnel dans cookie (index et Cargo.toml)
	# index/co/ok/cookie: virer les 0.2.3, 4, 5 (seule la 2 utilise url-0.5, encore compatible avec les autres)
	# index/3/s/ssh: bitflags 0.5 et non 0.3
	# index/3/n/num: num_complexe non optionnel, idem pour bigint et rational.
	# index/nu/m-/num-bigint: rand non optionnel
	# index/cl/ap/clap: strsim pas optionnel, ansi_term, unicode_width, libc

	for i in libpijul/Cargo.toml pijul/Cargo.toml
	do
		filtrer "$i" sed -e '/^\[dependencies\]/{
a\
cookie = "<= 0.2.2"
}'
	done
}

auPropre()
{
	darcs revert -a libpijul/Cargo.toml pijul/Cargo.toml
}

pourPseudoCargo()
{
	# Une section [bin] pour dire ce qu'on attend en fin de compte.
	filtrer pijul/Cargo.toml sed -e '1{
i\
[bin]
i\
name = "pijul"
}'
}

pasDeDepSrc()
{
	# La section dependencies.<src>, ça ne marche pas trop, avec notre pseudocargo.
	filtrer libpijul/Cargo.toml sed -e '/^\[dependencies\./d' -e '/^path *=/d' -e '/^\[dependencies\]/{
a\
sanakirja = "0.4.4"
}'
}

# Variables

archive_darcs="http://pijul.org"
dest="$INSTALLS/$logiciel-$version"

[ -d "$dest" ] && exit 0

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
echo Compilation… >&2
cd libpijul
pseudocargo --include-optional "$inclusionsForcees"
cd ..
cd pijul
[ -e src/libpijul ] || ln -s ../../libpijul src/libpijul
pseudocargo --include-optional "$inclusionsForcees"

echo Installation… >&2
sudo mkdir -p "$dest/bin"
find "$CARGODEST" -maxdepth 1 -type f -name "pijul-[0-9]*" -perm +0001 -exec sudo cp {} "$dest/bin/pijul" \;
sutiliser "pijul-$version"

rm -Rf "$TMP/$$"
