#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

inclure libjpeg
inclure libpng
inclure freetype

logiciel=PIL

# Historique des versions gérées

version=1.1.5

dest=/usr/local/$logiciel-$version
archive=http://effbot.org/downloads/Imaging-$version.tar.gz

# Modifications

manque()
{
	echo "http://www.pythonmac.org/wiki/FAQ#head-8838d40da5d563166ca8b13cfb71cd2e856e81e3" >&2
	echo 'sudo python `python -c "import pimp; print pimp.__file__"` -u http://www.python.org/packman/version-0.3/darwin-7.7.0-Power_Macintosh.plist -f -i _tkinter-2.3-binary' >&2
	exit 0
}

# Boulot

[ -d "$dest" ] && exit 0

if [[ $version = *-* ]] ; then
	obtenirEtAllerDansCvs -d $version $archive_cvs
else
	obtenirEtAllerDans "$archive"
fi

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
python setup.py build_ext -i
python selftest.py

echo Compilation… >&2

echo Installation… >&2
sudo python setup.py install --prefix="$dest"
sudo cp libImaging/ImPlatform.h libImaging/Imaging.h /System/Library/Frameworks/Python.framework/Versions/Current/include/python*/

rm -Rf /tmp/$$
