#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delicat() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delicat ; s="`dirname "$s"`" ; Delicat ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

versions -1 pkgconf+ig | grep -q . && exit 0 || true

v 0.15.0 || true
v 0.23 || true
v 0.28 || true
v 0.29.1 && prerequis="iconv" && modifs="sisicestbienuniconvgnu" || true
v 0.29.2 || true

sisicestbienuniconvgnu()
{
	#filtrer glib/glib/gconvert.c grep -v '#error.*iconv'
	CPPFLAGS="$CPPFLAGS -DUSE_LIBICONV_GNU=1"
	LDFLAGS="$LDFLAGS -liconv"
	export CPPFLAGS LDFLAGS
}

archive="http://www.freedesktop.org/software/pkgconfig/releases/$logiciel-$version.tar.gz"
pge $version 0.23 && archive="http://pkgconfig.freedesktop.org/releases/pkg-config-$version.tar.gz"

prerequis

if option strict
then
	rech=
else
	rech="$INSTALLS/lib/pkgconfig:/usr/lib/pkgconfig"
fi

destiner

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" --with-internal-glib --with-pc-path="$rech"

echo Correction… >&2
# La modif suivante était nécessaire pour que certains paquets daignent cesser de surcharger mon PATH; malheureusement elle m'empêche aussi d'utiliser (proprement) mon PATH pour surcharger /usr/local. Cela dit le --with-pc-path semble répondre à ce besoin.
true ||
filtrer main.c sed -e '/getenv.*PKG_CONFIG_PATH/a\
add_search_dir("'"$INSTALLS"'/lib/pkgconfig");
'

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser
