#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

OPTIONS_CONF=
OPTIONS_CMAKE=

# Historique des versions gérées

prerequis="python cmake pkgconfig \\ libpng"
v 0.22.5 && modifs="llongmax" || true
v 0.24.4 && modifs="llongmax" || true
v 0.32.0 && modifs="llongmax" && prerequis="$prerequis libopenjp2" || true
v 0.34.0 || true
v 0.52.0 && prerequis="$prerequis cairo libtiff curl" || true
v 0.72.0 && modifs="$modifs nssVisible" && prerequis="$prerequis nss curl" || true # Pour la signature des PDF.
v 0.75.0 || true
v 0.84.0 || true

# Pour LibreOffice, il nous faut les en-têtes internes (Inkscape a le même souci, cf. https://bugs.launchpad.net/inkscape/+bug/254849).
if option xpdf
then
	OPTIONS_CONF="$OPTIONS_CONF --enable-xpdf-headers"
	OPTIONS_CMAKE="$OPTIONS_CMAKE -DENABLE_UNSTABLE_API_ABI_HEADERS=1"
fi

# Modifications

nssVisible()
{
	if true
	then
		export CPPFLAGS="-I$destnss/include/nss $CPPFLAGS"
		export CXXFLAGS="-I$destnss/include/nss $CXXFLAGS"
		export CFLAGS="-I$destnss/include/nss $CFLAGS"
	else
	filtrer poppler/SignatureHandler.h sed -E -e '/<(cert|cms|cryptohi|sec[a-z]*)\.h>/s#<#<nss//#'
	fi
}

llongmax()
{
	# Une Linuxerie.
	filtrer poppler/Lexer.cc sed -e '/long long.*LLONG_MAX/{
i\
#ifndef LLONG_MAX
i\
#define LLONG_MAX 9223372036854775807LL
i\
#endif
}'
	filtrer poppler/PDFDoc.cc sed -e '/^#define/{
x
s/././
x
t
h
i\
#ifndef LLONG_MAX
i\
#define LLONG_MAX 9223372036854775807LL
i\
#endif
}'
}

# Variables

archive="http://poppler.freedesktop.org/poppler-$version.tar.xz"
pge $version 0.24 || archive="http://poppler.freedesktop.org/poppler-$version.tar.gz"

optionSi ft/freetype && prerequis="$prerequis bzip2" && export LDFLAGS="$LDFLAGS -lbz2" || true

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if pge $version 0.60 # Quelle version exactement? > 0.52 < 0.72
then
	mkdir -p build
	cd build
	cmake -DCMAKE_INSTALL_PREFIX="$dest" $OPTIONS_CMAKE ..
else
	./configure --prefix="$dest" $OPTIONS_CONF
fi

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser
