#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.sh"

logiciel=postgresql

v 8.0.1 && modifs="detectionPerl detectionReadline" && contribs="pgcrypto" || true
v 8.0.3 || true
v 9.1.2 && modifs="bsdAvecPythonThreade detectionPerl detectionReadline" || true
v 9.2.1 && modifs="detectionPerl detectionReadline" && contribs="$contribs hstore" || true
v 9.2.9 || true
v 9.2.18 || true
v 9.5.3  || true
v 9.6.1 && modifs="detectionPerl detectionReadline pathZic" || true
v 9.6.5 || true
v 9.6.6 || true

detectionReadline()
{
	filtrer configure sed -e 's#" -lncurses"#" -lncursesw" " -lncurses"#g'
}

bsdAvecPythonThreade()
{
	filtrer configure sed -e '/freebsd.*)$/,/;;/d'
}

detectionPerl()
{
	avecPerl="--without-perl"
	if command -v perl 2> /dev/null >&1
	then
		if perl -MConfig -e 'print $Config{useshrplib}' | grep -q true
		then
			avecPerl="--with-perl"
		fi
	fi
	
	OPTIONS_CONF="$OPTIONS_CONF $avecPerl"
}

pathZic()
{
	filtrer src/timezone/Makefile sed -e "/ZIC *:*=/s#=#=PATH=\"$PATH\" LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH\" #"
}

dest="$INSTALLS/$logiciel-$version"
archive=http://ftp.postgresql.org/pub/source/v$version/postgresql-$version.tar.bz2
pge $version 9 || jar=http://jdbc.postgresql.org/download/postgresql-8.0-310.jdbc3.jar

[ -d "$dest" ] && exit 0

prerequis

obtenirEtAllerDansVersion

echo Corrections… >&2
for modif in true $modifs
do
	"$modif"
done

echo Configuration… >&2

./configure --prefix="$dest" --enable-thread-safety --with-python --with-pam --with-rendezvous --with-openssl $OPTIONS_CONF

echo Compilation… >&2
make
sed < contrib/start-scripts/freebsd > share.init.postgresql -e "/^prefix=/s#=.*#=$INSTALLS#"
chmod a+x share.init.postgresql

echo Installation… >&2
sudo make install
pge $version 9 || sudo cp `obtenir "$jar"` "$dest/lib/postgresql.jar"
for contrib in $contribs
do
	( cd contrib/$contrib && make && sudo make install )
done
sudo cp share.init.postgresql "$dest/share/init.postgresql"

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
