#!/bin/bash
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.bash"

inclure db

logiciel=postfix

# Historique des versions gérées

version=2.5.1
PFCCARGS=-DHAS_DB

version=2.8.7
PFCCARGS=

# Modifications

creeComptes()
{
	case `uname` in
		FreeBSD)
			if ! grep -q postdrop /etc/group
			then
				qui=postfix
				id=4096
				sudo pw groupadd $qui -g $id && sudo pw useradd $qui -u $id -g $id -s /coquille/vide
				qui=postdrop
				id=4097
				sudo pw groupadd $qui -g $id
			fi
			;;
	esac
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="ftp://mir1.ovh.net/ftp.postfix.org/postfix-release/official/$logiciel-$version.tar.gz"

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
configurer()
{
	CCARGS=
	while [ $# -ge 2 ]
	do
		param="$3"
		echo "$3" | grep -q '^/' && param="$dest$param"
		[ -z "$1" ] || CCARGS="$CCARGS -DDEF_$1=\\\"$param\\\""
if false
then
		[ "x$param" = xno ] || filtrer postfix-install sed -e '1a\
'"$2=$param"'
'
fi
		shift
		shift
		shift
	done
}
configurer \
	COMMAND_DIR   command_directory /sbin \
	CONFIG_DIR    config_directory  /etc/postfix \
	DAEMON_DIR    daemon_directory  /libexec \
	DATA_DIR      data_directory    /var/run \
	MAILQ_PATH    mailq_path        /bin/mailq \
	MANPAGE_DIR   manpage_directory /man \
	NEWALIAS_PATH newaliases_path   /bin/newaliases \
	QUEUE_DIR     queue_directory   /var/spool/postfix \
	SENDMAIL_PATH sendmail_path     /sbin/sendmail \
	''            tempdir           /var/run \
	''            html_directory    no \
	''            mail_owner        postfix \
	''            readme_directory  no \
	''            setgid_group      postdrop

make makefiles CCARGS="$CCARGS $PFCCARGS -I$INSTALLS/include" AUXLIBS="-R$INSTALLS/lib -L$INSTALLS/lib -ldb"

echo Compilation… >&2
make

echo Installation… >&2
creeComptes
sudo make upgrade
sudo chown -R postfix:postfix "$dest/var/run"
sutiliser "$logiciel-$version"
[ -h /usr/sbin/sendmail -o ! -e /usr/sbin/sendmail ] && sudo rm -f /usr/sbin/sendmail && sudo ln -s "$dest/sbin/sendmail" /usr/sbin/sendmail

rm -Rf $TMP/$$
