#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.sh"

logiciel=postgis
version=2.0.1
modifs="rechXml detecteLog2"
modifspostconf="compAvecLocal"

inclure libxml
inclure geos
inclure proj
inclure gdal
inclure jsonc

dest="$INSTALLS/$logiciel-$version"
archive=http://download.osgeo.org/postgis/source/postgis-$version.tar.gz

rechXml()
{
	filtrer configure sed -e '/^CPPFLAGS=".XML2_CPPFLAGS"/c\
CPPFLAGS="$XML2_CPPFLAGS $CPPFLAGS"
' -e '/^CPPFLAGS=".PROJ_CPPFLAGS/c\
CPPFLAGS="$PROJ_CPPFLAGS $CPPFLAGS"
'
}

compAvecLocal()
{
	for i in liblwgeom libpgcommon raster/loader loader
	do
		filtrer "$i/Makefile" sed -e "/^CFLAGS *=.*[^\\]$/s#\$# $CPPFLAGS#" -e "/^RTCORE_CFLAGS *=/s#\$# $CPPFLAGS#"
	done
}

detecteLog2()
{
	cat > /tmp/log2.c <<TERMINE
#include <math.h>

int main(int argc, char ** argv)
{
	double n;
	n = log2(567.22);
}
TERMINE
	cc -lm -o /tmp/log2 /tmp/log2.c 2> /dev/null || filtrer raster/rt_core/rt_api.c sed -e '/include.*math.h/a\
#define log2(n) (log(n) / log(2))
'
}

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Corrections… >&2
for modif in true $modifs
do
	$modif
done

echo Configuration… >&2
./configure --prefix="$dest"
for modif in true $modifspostconf ; do $modif "$@" ; done

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
