#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=prosody

# Historique des versions gérées

v 0.8.2 && modifs="maCompil" && prerequis="libidn >= 1.11" || true
v 0.9.6 && prerequis="libidn >= 1.24" || true

prerequis

# Modifications

maCompil()
{
	filtrer configure sed \
		-e "/^# Defaults/,/# Help/s#^CFLAGS=\"\(.*\)\"#CFLAGS=\"\1 $CFLAGS\"#" \
		-e "/^# Defaults/,/# Help/s#^LDFLAGS=\"\(.*\)\"#LDFLAGS=\"\1 $LDFLAGS\"#"
}

# Variables

archive="http://prosody.im/downloads/source/$logiciel-$version.tar.gz"
dest=$INSTALLS/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
patch -p0 <<TERMINE
--- prosody.cfg.lua.install	2013-01-11 17:38:35.000000000 +0100
+++ prosody.cfg.lua.install	2013-01-11 18:10:10.000000000 +0100
@@ -16,6 +16,11 @@
 -- Settings in this section apply to the whole server and are the default settings
 -- for any virtual hosts
 
+pidfile = "$dest/var/run/prosody.pid";
+prosody_user = "prosody";
+prosody_group = "prosody";
+bosh_ports = { { interface = "127.0.0.1"; port = 5280; path = "http-bind"; } }
+
 -- This is a (by default, empty) list of accounts that are admins
 -- for the server. Note that you must create the accounts separately
 -- (see http://prosody.im/doc/creating_accounts for info)
@@ -42,7 +47,7 @@
 		"private"; -- Private XML storage (for room bookmarks, etc.)
 		"vcard"; -- Allow users to set vCards
 		--"privacy"; -- Support privacy lists
-		--"compression"; -- Stream compression
+		"compression"; -- Stream compression
 
 	-- Nice to have
 		"legacyauth"; -- Legacy authentication. Only used by some old clients and bots.
@@ -133,7 +138,7 @@
 -- You need to add a VirtualHost entry for each domain you wish Prosody to serve.
 -- Settings under each VirtualHost entry apply *only* to that host.
 
-VirtualHost "localhost"
+VirtualHost "gclo.fr"
 
 VirtualHost "example.com"
 	enabled = false -- Remove this line to enable this host
@@ -153,7 +158,7 @@
 -- For more information on components, see http://prosody.im/doc/components
 
 ---Set up a MUC (multi-user chat) room server on conference.example.com:
---Component "conference.example.com" "muc"
+Component "conference.gclo.fr" "muc"
 
 -- Set up a SOCKS5 bytestream proxy for server-proxied file transfers:
 --Component "proxy.example.com" "proxy65"
TERMINE
if pge $version 0.9
then

	patch -p0 <<TERMINE
--- prosody.cfg.lua.install	2013-01-11 17:38:35.000000000 +0100
+++ prosody.cfg.lua.install	2013-01-11 18:10:10.000000000 +0100
@@ -64,11 +64,11 @@
 		--"admin_telnet"; -- Opens telnet console interface on localhost port 5582
 	
 	-- HTTP modules
-		--"bosh"; -- Enable BOSH clients, aka "Jabber over HTTP"
+		"bosh"; -- Enable BOSH clients, aka "Jabber over HTTP"
 		--"http_files"; -- Serve static files from a directory over HTTP
 
 	-- Other specific functionality
-		--"posix"; -- POSIX functionality, sends server to background, enables syslog, etc.
+		"posix"; -- POSIX functionality, sends server to background, enables syslog, etc.
 		--"groups"; -- Shared roster support
 		--"announce"; -- Send announcement to all online users
 		--"welcome"; -- Welcome users who register accounts
TERMINE
else
	patch -p0 <<TERMINE
--- prosody.cfg.lua.install	2013-01-11 17:38:35.000000000 +0100
+++ prosody.cfg.lua.install	2013-01-11 18:10:10.000000000 +0100
@@ -59,7 +64,7 @@
 		--"admin_telnet"; -- Opens telnet console interface on localhost port 5582
 
 	-- Other specific functionality
-		--"posix"; -- POSIX functionality, sends server to background, enables syslog, etc.
-		--"bosh"; -- Enable BOSH clients, aka "Jabber over HTTP"
+		"posix"; -- POSIX functionality, sends server to background, enables syslog, etc.
+		"bosh"; -- Enable BOSH clients, aka "Jabber over HTTP"
 		--"httpserver"; -- Serve static files from a directory over HTTP
 		--"groups"; -- Shared roster support
TERMINE
fi
filtrer prosody.cfg.lua.install sed -E '/ = "prosody.(log|err)/s#= "#= "'"$dest"'/#'
sudo make install
creeCompte prosody 4110
sudo mkdir -p "$dest/var/run" "$dest/var/log"
sudo chown prosody:prosody "$dest/var/run" "$dest/var/log" "$dest/var/lib/prosody"
[ -e /usr/local/etc/rc.d/prosody ] || sudo ln -s "$INSTALLS/bin/prosodyctl" /usr/local/etc/rc.d/prosody

sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"

echo "# Pensez à faire vos sudo prosodyctl adduser gui@gclo.fr" >&2
echo "# Si vous êtes chez OVH, virer les CNAME _xmpp et _jabber (qui font croire à GTalk et d'autres serveurs exploitant les SRV que votre serveur se trouve sur le central OVH plutôt que sur votre machine)." >&2
