#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delictueux() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delictueux ; s="`dirname "$s"`" ; Delictueux ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

prerequis="python cmake \\"
v 2.6.0 && modifs="assert2 scalaireTest benchbench cmake3 memsetthis clang17Sympa isarithmetic picore" || true # Impossible à compiler en mars 2026 avec un clang 21.
v 2.7.1 && retirerModif cmake3 memsetthis clang17Sympa isarithmetic benchbench && modifs="$modifs sansNccl" || true # N'a pas encore le USE_NCCL.
v 2.8.0 && modifs="$modifs fmtMalloc funcClosure" || true # Compile, mais finit avec un Undefined symbol "dynamo_eval_custom_code" (qui est effectivement U dans notre .so, tandis qu'il est T dans celui d'une 2.9.1 compilée à côté): en reprenant des fichiers entiers de la 2.9.1, a-t-on chopé un .h qui en 2.9.1 ne fait que déclarer un symbole défini dans un .c que nous n'avons pas repris?
v 2.9.1 && retirerModif picore funcClosure || true
v 2.10.0 && remplacerPrerequis cmake && retirerModif fmtMalloc || true

# Modifications

fmtMalloc()
{
	# La 2.8 introduit du new sans les malloc et free qui vont avec: ça plante.
	# On repique la correction de la 2.10: précéder d'un <stdlib.h>
	filtrer third_party/fmt/include/fmt/format.h sed -e '/ifndef FMT_MODULE/a\
#include <stdlib.h>
'
}

funcClosure()
{
	filtrer torch/csrc/dynamo/framelocals_mapping.cpp sed \
		-e '/PyObject.*closure.*PyFunctionObject.*func_closure/c\
PyObject* closure = FUNC(frame)->func_closure;
' \
		-e '/pycore_code.h/{
i\
#define Py_BUILD_CORE
a\
#undef Py_BUILD_CORE
}' \
		-e '/IS_PYTHON_3_11_PLUS/{
a\
#if IS_PYTHON_3_14_PLUS
a\
#define stacktop stackpointer
a\
#endif
}' \
		-e '/update_framelocals.*localsplus/{
i\
#if IS_PYTHON_3_14_PLUS
i\
update_framelocals(i, PyStackRef_AsPyObjectBorrow(frame->localsplus[i]));
i\
#else
a\
#endif
}'
	filtrer torch/csrc/dynamo/cpython_includes.h sed \
		-e '/#if IS_PYTHON_3_13_PLUS/{
i\
#if IS_PYTHON_3_14_PLUS
i\
#define F_CODE(x) (PyCodeObject*)PyStackRef_AsPyObjectBorrow(x->f_executable)
i\
#define PREV_INSTR(x) (x)->instr_ptr
s/#/#el/
}' \
		-e '/#define FUNC/{
i\
#if IS_PYTHON_3_14_PLUS
i\
#define FUNC(x) ((PyFunctionObject*)PyStackRef_AsPyObjectBorrow((x)->f_funcobj))
i\
#else
a\
#endif
}'
	# Pour ceux-là il y a trop de modifs.
	for f in torch/csrc/dynamo/cpython_defs.c torch/csrc/dynamo/cpython_defs.h
	do
		bnf=`bn $f`
		cp `obtenir https://raw.githubusercontent.com/pytorch/pytorch/refs/tags/v2.9.1/$f $bnf.pytorch.2.9.1` $f
	done
}

picore()
{
	filtrer torch/csrc/dynamo/cpython_includes.h sed \
		-e '/pycore_frame.h/{
a\
#if IS_PYTHON_3_14_PLUS
a\
#include <internal/pycore_interpframe_structs.h>
a\
#include <internal/pycore_stackref.h>
a\
#include <internal/pycore_code.h>
a\
#endif
}'
}

clang17Sympa()
{
	# Les vieilles versions ne supportent pas un clang un peu moderne. On récupère les adaptations de la 2.10 ().
	true ||
	filtrer third_party/fbgemm/CMakeLists.txt sed -e '/CheckCXXCompilerFlag/{
i\
if(CMAKE_CXX_COMPILER_ID MATCHES Clang AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 17.0.0)
i\
target_compile_options(asmjit         PRIVATE "-Wno-vla-cxx-extension")
i\
target_compile_options(fbgemm_generic PRIVATE "-Wno-vla-cxx-extension")
i\
target_compile_options(fbgemm_avx2    PRIVATE "-Wno-vla-cxx-extension")
i\
target_compile_options(fbgemm_avx512  PRIVATE "-Wno-vla-cxx-extension")
i\
endif()
}
'
	cat >> third_party/fbgemm/CMakeLists.txt <<TERMINE
if(CMAKE_CXX_COMPILER_ID MATCHES Clang AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 17.0.0)
target_compile_options(asmjit         PRIVATE "-Wno-vla-cxx-extension")
target_compile_options(fbgemm_generic PRIVATE "-Wno-vla-cxx-extension")
target_compile_options(fbgemm_avx2    PRIVATE "-Wno-vla-cxx-extension")
target_compile_options(fbgemm_avx512  PRIVATE "-Wno-vla-cxx-extension")
endif()
TERMINE
}

benchbench()
{
	# third_party/benchmark/src/mutex.h:79:40: error: mutex 'mut_' is still held at the end of function
	# Normal, la fonction c'est le constructeur lock(): la libération se fera au destructeur.
	# Pourtant il y a bien un attribut compilo mentionnant que l'on enfreint sciemment.
	# Mais les macros de définition des attributs compilo sont conditionnées par HAVE_THREAD_SAFETY_ATTRIBUTES,
	# or dans build/CMakeFiles/CMakeConfigureLog.yaml on s'aperçoit que la compil' du test menant à la définition de cet HAVE_ a planté,
	# pour cause de third_party/benchmark/cmake/thread_safety_attributes.cpp qui inclut ../src/mutex.h qui inclut check.h puis internal_macros.h puis benchmark/benchmark.h qui n'existe pas (depuis le sous-dossier cmake).
	# Les versions suivantes de pytorch embarquent un internal_macros.h sans benchmark/benchmark.h (à chaque appelant de l'invoquer).
	# Bon au début j'ai essayé de faire le travail à la main en codant en dur le chemin vers benchmark.h
	# Sauf que finalement leur test CMake revient à compiler tout benchmark, pour valider qu'on peut le compiler. Ça devenait une merde pas possible.
	# Finalement on télécharge une version un peu plus récente (et on l'espère compatible) adaptée par Google aux clang un poil plus récents, et on n'en parle plus.
	( obtenirEtAllerDans https://github.com/google/benchmark/archive/refs/tags/v1.7.1.tar.gz ; tar cf - . ) | ( cd third_party/benchmark && tar xf - )
}

isarithmetic()
{
	# error: 'is_arithmetic' cannot be specialized: Users are not allowed to specialize this standard library entity
	# Et n'a pas l'air de servir.
	filtrer c10/util/strong_type.h awk '/^template/{t=(t?t"\n":"")$0;next}t&&/is_arithmetic/{t="";tari=1}tari&&/^};/{tari="";next}tari{next}t{print t;t=""}{print}'
}

memsetthis()
{
	# error: first argument in call to 'memset' is a pointer to non-trivially copyable type 'asmjit::ZoneAllocator'
	for f in \
		third_party/fbgemm/third_party/asmjit/src/asmjit/core/zone.cpp \
		third_party/fbgemm/third_party/asmjit/src/asmjit/core/zone.h \
		third_party/fbgemm/third_party/asmjit/src/asmjit/core/zonevector.h \
		third_party/fbgemm/third_party/asmjit/src/asmjit/core/func.h
	do
		filtrer "$f" sed \
			-e 's/memset.this/memset((void *)this/g' \
			-e 's/memcpy.this/memcpy((void *)this/g'
	done
	
	filtrer third_party/fbgemm/third_party/asmjit/src/asmjit/core/zonevector.h sed -E \
		-e 's/(memcpy\()([^,]*)/\1(void *)(\2)/g'
}

cmake3()
{
	# Certains des CMakeLists.txt mentionnent une compatibilité jusqu'à des cmake 2.8; sauf que les versions récentes (4.2) disent "je ne supporte plus les cmake < 3.5 (et bientôt 3.10)".
	# On aurait pu se rajouter cmake < 4 en prérequis (qui nous modifie le $PATH), sauf que setup.py utilise le module Python cmake, non pas le binaire du $PATH.
	grep -li 'cmake_minimum_required.VERSION.[0-3]' `find . -name CMakeLists.txt` | while read f
	do
		filtrer "$f" sed -e 's/VERSION [0-3][.0-9]*/VERSION 3.10/'
	done
}

assert2()
{
	# Le bidule utilise la fonction _assert(booléen, message) pour ne pas empiéter sur l'assert(booléen && message) système.
	# Problème: sous FreeBSD, assert est défini en fonction d'_assert(), lui-même macro.
	filtrer aten/src/ATen/native/sparse/ValidateCompressedIndicesCommon.h sed -e '/^namespace/i\
#undef _assert
'
}

scalaireTest()
{
	# conversion from 'long long' to 'Scalar' is ambiguous: il n'y a de constructeurs que pour les uint16, 32 et 64.
	filtrer c10/test/core/Scalar_test.cpp sed -e 's/1LL/(uint64_t)&/'
}

sansNccl()
{
	export USE_NCCL=0
}

# Variables

archive=https://github.com/pytorch/pytorch/releases/download/v$version/pytorch-v$version.tar.gz

for modif in true $predestiner ; do "$modif" ; done

destiner

prerequis

obtenirEtAllerDansVersion

echo Corrections… >&2
for modif in true $modifs ; do "$modif" ; done

echo Prérequis… >&2
pip install --prefix $INSTALLS/$PYEXT pyyaml typing_extensions

echo Compilation… >&2
while true
do
	touch $TMP/$$/h
	python ./setup.py build && break ||
	find . -newer $TMP/$$/h -type f -not -size 0 -not -name ".ninja*" -not -name CMakeConfigureLog.yaml -not -name version.py -not -name native_functions.yaml -not -name tags.yaml -not -name "*.check_cache" | tee $TMP/$$/z | grep -q . && magenta "Plantage, mais on progresse (`wc -l < $TMP/$$/z` fichiers générés entre-temps). On retente." && tail -10 < $TMP/$$/z | sed -e 's/^/  /' ||
	{ jaune "# Nous vous plaçons dans un shell interactif. Tentez de rattraper le coup." >&2 && sh ; }
done

echo Installation… >&2
dest0="`pwd`/dest"
rm -Rf "$dest0"
pyextinit "$dest0"
# Pas de sudokupy: on est sur un dossier local. Et sudokupy est une grosse machinerie qui rappelle ./pytorch (… même si je ne rappelle plus ce qui le justifie; peut-être y a-t-il un couac à corriger).
#sudokupy USE_NCCL=$USE_NCCL python ./setup.py install --prefix="$dest0"
# setup.py ne transmet pas le --prefix au pip sous-jacent. De plus il empaquette le projet en .wheel, puis l'installe… juste par nom, donc si on est en train d'installer une 2.9 alors qu'il a déjà téléchargé une 2.10, c'est la 2.10 qui finit en place.
#python ./setup.py install --prefix="$dest0"
pip install --prefix="$dest0" --no-build-isolation -v .

sudoku mkdir -p "$dest"
sudoku cp -Rp "$dest0/." "$dest/."
sutiliser - "$PYEXT"
