#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

prerequis="libjpeg libpng giflib dbus"

# Historique des versions gérées

v 3.3.8 || true
v 4.2.2 && modifs="qtcopy" && OPTIONS_CONF="$OPTIONS_CONF -qt-gif -thread -qdbus" || true
v 5.12.12 && prerequis="git cmake \\" && modifs="modules cflagsEnCmake" && OPTIONS_CONF="-qdbus" || true
v 5.15.16 && lts=1 || true
v 6.7.3 && lts= && modifs="$modifs fqtnConst" || true
v 6.8.2 && retirerModif fqtnConst || true

# Pour Qt 5, l'archive publiée ne contient que le lanceur, pas les .git… mais le lanceur chope des git submodules, donc échoue sans ses .git. On doit donc récupérer l'étiquette plutôt que le .tgz
pg 5 $version || versionComplete="$version.HEAD.silo.git" # Le HEAD de l'étiquette qui figure en @$version dans $archive_git. Avec un .silo pour préserver le .git/

# Modifications

modules()
{
	local OPTIONS_INIT="--module-subset=default"
	#OPTIONS_CONF="$OPTIONS_CONF -init-submodules -submodules all"
	#OPTIONS_CONF="$OPTIONS_CONF -submodules all"
	case `uname` in
		FreeBSD)
			# qtquick3dphysics a une #error explicite dans ses .h pour autre chose que Windows, Linux, Mac.
			OPTIONS_INIT="$OPTIONS_INIT,-qtquick3dphysics"
			;;
	esac
	OPTIONS_INIT="$OPTIONS_INIT,-qtcharts" # "Imposs de trouver la rév actuelle" en 6.8.
	[ ! -f guili.initsilos ] || return 0
	if [ -x init-repository.pl ]
	then
		./init-repository.pl $OPTIONS_INIT
	else
		./init-repository $OPTIONS_INIT
	fi
	touch guili.initsilos
}

cflagsEnCmake()
{
	case "$CFLAGS" in
		*-O3*) OPTIONS_CONF="$OPTIONS_CONF -Doptimize_full=true" ;;
	esac
}

# À FAIRE: éplucher le config.summary
# entre 6.7 et 6.8, QtMM GStreamer plugin passe de yes à no
# Fully optimize release builds (-O3) .... no
# Qt D-Bus directly linked to libdbus .... no
# Support enabled for:
# Using pkg-config ....................... no
# Qt directly linked to OpenSSL ........ no
# OpenSSL based cryptographic hash ....... no
# PostgreSQL ............................. no
# Using system provided SQLite ......... no
#   Optional system libraries:
#    re2 .................................. no
#    icu .................................. no
#    libwebp, libwebpmux and libwebpdemux . no
#    opus ................................. no
#    ffmpeg ............................... no
#    libvpx ............................... no
#    snappy ............................... no
#    glib ................................. no
#    zlib ................................. no
#    minizip .............................. no
#    libevent ............................. no
#    libxml2 and libxslt .................. no
#    lcms2 ................................ no
#    png .................................. no
#    tiff ................................. no
#    jpeg ................................. no
#    libopenjpeg2 ......................... no
#    harfbuzz ............................. no
#    freetype ............................. no
#    libpci ............................... no
# WARNING: QtPdf won't be built. Build can be done only on Linux, Windows, macO, iOS and Android.

for p in python pkgconf glib iconv icu pcre freetype harfbuzz libjpeg libpng postgresql sqlite mysql libtiff ninja gn fontconfig dbus nss re2 opus ffmpeg zlib libevent libxml libxslt lcms
do
	versions $p | grep -q . && prerequis="$prerequis $p" || true
done

fqtnConst()
{
	# Une 6.7 avec un clang 19 pète dans qdoc sur 3 erreurs, qui semblent être un durcissement de clang face aux tentatives d'extraction de type C++ sur des const tandis que lui attend des non const.
	# Confirmé en regardant le source d'une 6.8, qui inclut des blocs spécifiques #if LIBCLANG_VERSION_MAJOR >= 19
	
	case "$CC" in clang*) true ;; *) return 0 ;; esac
	local vclang="`versionCompiloChemin clang`"
	pge $vclang 19 || return 0
	modifsPostConf="$modifsPostConf _fqtnConst"
}

_fqtnConst()
{
	filtrer qttools/src/qdoc/qdoc/src/qdoc/clangcodeparser.cpp sed \
		-e '/get_fully_qualified_type_name/s/getDefaultArgument(),/getDefaultArgument().getArgument().getAsType(),/' \
		-e '/get_expression_as_string/s/getDefaultArgument(),/getDefaultArgument().getSourceExpression(),/' \
		-e 's/TemplateName::Qualified::Fully/TemplateName::Qualified::AsWritten/'
}

qtcopy()
{
	local version=r619081
	local archive_svn=svn://anonsvn.kde.org/home/kde/trunk/qt-copy/patches
	pushd . > /dev/null
	pushd /tmp > /dev/null
	obtenirEtAllerDansVersion
	ou="`pwd`"
	popd > /dev/null
	mv "$ou" patches
	for i in patches/*-*.diff
	do
		patch -p0 < "$i" || true # Certains sont vides.
	done
}

# Variables

archive=https://github.com/qt/qt5/archive/refs/tags/v$version`[ -z "$lts" ] || printf %s -lts-lgpl`.tar.gz
#archive_git=https://github.com/qt/qt5.git@$version # Surtout pas, car la structure à 2 étages fait que qt/playground/jenesaisplusquoi n'existe pas.
vgit=$version # La branche
pge $version 6 || vgit=v$version-lts-lgpl # L'étiquette
archive_git=https://code.qt.io/qt/qt5.git@$vgit
# Ce crétin de cmake utilise l'@ comme séparateur, dans qtshadertools/tools/qsb/Qt6ShaderToolsMacros.cmake
# résultat, son passage de paramètres truc:muche:$TMP/qt5@6.1.11.6.1.11.HEAD/etc. (format <option>:<option>:<chemin>) est découpé en deux blocs, le premier ayant un chemin incomplet, le second n'ayant pas de chemin (le 6.1.11.HEAD/etc. est vu comme l'<option> 1): list index: 2 out of range (-1, 0)
# On utilise donc un séparateur plus neutre (ni @, ni ;, ni :):
guili_etiquette_sep=_

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
# En l'absence de réseau sur une copie déjà extraite:
#filtrer cmake/QtIRGitHelpers.cmake sed -e 's/NOT should_clone AND arg_FETCH/FALSE AND &/'
if pge $version 5 && pg 6 $version ; then OPTIONS_CONF="$OPTIONS_CONF -opensource -confirm-license" ; fi # Sinon il emmerde avec demande de validation manuelle.
./configure --prefix="$dest" $OPTIONS_CONF
# Celui lancé par PhantomJS 2.1.1:
# /home/gui/tmp/phantomjs-2.1.1/src/qt/qtbase/configure -static -opensource -confirm-license -prefix /home/gui/tmp/phantomjs-2.1.1/src/qt/qtbase -qt-zlib -qt-libpng -qt-libjpeg -qt-pcre -nomake examples -nomake tools -nomake tests -no-qml-debug -no-dbus -no-opengl -no-audio-backend -D QT_NO_GRAPHICSVIEW -D QT_NO_GRAPHICSEFFECT -D QT_NO_STYLESHEET -D QT_NO_STYLE_CDE -D QT_NO_STYLE_CLEANLOOKS -D QT_NO_STYLE_MOTIF -D QT_NO_STYLE_PLASTIQUE -D QT_NO_PRINTPREVIEWDIALOG -no-qpa-platform-guard -qpa phantom -openssl -openssl-linked -no-openvg -no-eglfs -no-egl -no-glib -no-gtkstyle -no-cups -no-sm -no-xinerama -no-xkb -no-xcb -no-kms -no-linuxfb -no-directfb -no-mtdev -no-libudev -no-evdev -no-pulseaudio -no-alsa -no-feature-PRINTPREVIEWWIDGET -fontconfig -icu -system-libjpeg -system-libpng -system-zlib -release (et tous les CFLAGS et cie; on les retrouve dans le build.py de ladite branche.

for modif in true $modifsPostConf ; do $modif ; done

echo Compilation… >&2
export DYLD_LIBRARY_PATH="`pwd`/lib" # Car utilise dans la génération les biblios produites.
make -j4

echo Installation… >&2
sudo make install

sutiliser
