#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

prerequis="libjpeg libpng giflib dbus"

# Historique des versions gérées

v 3.3.8 || true
v 4.2.2 && modifs="qtcopy" && OPTIONS_CONF="$OPTIONS_CONF -qt-gif -thread -qdbus" || true

# Modifications

# À FAIRE: éplucher le config.summary
# entre 6.7 et 6.8, QtMM GStreamer plugin passe de yes à no
# Fully optimize release builds (-O3) .... no
# Qt D-Bus directly linked to libdbus .... no
# Support enabled for:
# Using pkg-config ....................... no
# Qt directly linked to OpenSSL ........ no
# OpenSSL based cryptographic hash ....... no
# PostgreSQL ............................. no
# Using system provided SQLite ......... no
#   Optional system libraries:
#    re2 .................................. no
#    icu .................................. no
#    libwebp, libwebpmux and libwebpdemux . no
#    opus ................................. no
#    ffmpeg ............................... no
#    libvpx ............................... no
#    snappy ............................... no
#    glib ................................. no
#    zlib ................................. no
#    minizip .............................. no
#    libevent ............................. no
#    libxml2 and libxslt .................. no
#    lcms2 ................................ no
#    png .................................. no
#    tiff ................................. no
#    jpeg ................................. no
#    libopenjpeg2 ......................... no
#    harfbuzz ............................. no
#    freetype ............................. no
#    libpci ............................... no
# WARNING: QtPdf won't be built. Build can be done only on Linux, Windows, macO, iOS and Android.

for p in python pkgconf glib iconv icu pcre freetype harfbuzz libjpeg libpng postgresql sqlite mysql libtiff ninja gn fontconfig dbus nss re2 opus ffmpeg zlib libevent libxml libxslt lcms
do
	versions $p | grep -q . && prerequis="$prerequis $p" || true
done

# Variables

truc=opensource-src
[[ $version = 3.* ]] && truc=free

archive="ftp://ftp.tu-chemnitz.de/pub/Qt/qt/source/$logiciel-mac-$truc-$version.tar.gz"

qtcopy()
{
	local version=r619081
	local archive_svn=svn://anonsvn.kde.org/home/kde/trunk/qt-copy/patches
	pushd . > /dev/null
	pushd /tmp > /dev/null
	obtenirEtAllerDansVersion
	ou="`pwd`"
	popd > /dev/null
	mv "$ou" patches
	for i in patches/*-*.diff
	do
		patch -p0 < "$i" || true # Certains sont vides.
	done
}

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Compilation… >&2
./configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
export DYLD_LIBRARY_PATH="`pwd`/lib" # Car utilise dans la génération les biblios produites.
make -j4

echo Installation… >&2
sudo make install

sutiliser
