#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 5.0 && modifs="darwin8aussi asdc" || true
v 5.2.14 || true
v 6.1.2 && modifs=asdc || true
v 6.2.1 || true
v 6.3.8 || true
v 7.0.5 || true
v 8.1.1 || true

# Modifications

# antislash dollar complétion
# Sur ls $t/truc<tab> lorsqu'il existe un "truc à espaces",
# readline complète en \$t/truc\ à\ espaces,
# avec des \ corrects devant les espaces, mais aussi un devant $.
asdc()
{
	local vr
	case "$version" in
		8.1.*) vr=8.1 ;;
		# Pour le moment on ne sait pas gérer les autres versions de readline.
		*) return ;;
	esac
	# Ne fait-on pas exactement ce que ferait un shopt -u complete_fullquote?
	patch -p0 < "$SCRIPTS/readline.non-intrusive-completion-quoting.$vr.patch"
	# Celui-ci est-il utile? Ne pourrait-on pas simplement activer rl_completion_suppress_quote?
	patch -p0 < "$SCRIPTS/readline.non-intrusive-completion-quoting.declose.$vr.patch"
}

darwin8aussi()
{
	filtrer support/shobj-conf sed -e 's/darwin7/darwin[78]/'
}

darwin89aussi()
{
	filtrer support/shobj-conf sed -e 's/darwin7/darwin[789]/' -e 's/darwin8/darwin[89]/'
}

rustine="`echo "$version" | cut -s -d . -f 3`"
mineure="`echo "$version" | cut -d . -f 1-2`"

archive="http://ftp.gnu.org/gnu/$logiciel/$logiciel-$mineure.tar.gz"

prerequis

destiner

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion
n=1
while [ $n -le $rustine ]
do
	v2="`echo $mineure | tr -d .`"
	url="`dirname "$archive"`/$logiciel-$mineure-patches/$logiciel$v2-`printf "%03.3d" $n`"
	patch -p0 < "`obtenir "$url"`"
	n=`expr $n + 1`
done

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
