#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 1.0.4 && prerequis="cmake \\ libevent glib gmime lua sqlite" && modifs="sansLuaJit sansRedis" || true # luajit trop instable.
v 1.3.5 && prerequis="$prerequis ragel" || true
v 1.5.3 && prerequis="$prerequis fann gd" || true
v 1.5.6 || true
v 1.6.2 && modifs="lpeginternevisible" || true

# Modifications

lpeginternevisible()
{
	# Je ne sais pourquoi lpeg, compilé dans rspamd, n'est pas exposée aux scripts lua. Du coup pétage immédiat au lancement:
	#   rspamd_config_read: rcl parse error:
	#   cannot init lua file /usr/local/rspamd-1.6.2/share/rspamd/rules/rspamd.lua:
	#   /usr/local/rspamd-1.6.2/share/rspamd/lib/lua_util.lua:2: module 'lpeg' not found
	filtrer src/lua/lua_common.c awk '/luaopen_lpeg *\(/{next}'\!'deja&&/rspamd_lua_add_preload/{print"rspamd_lua_add_preload (L, \"lpeg\", luaopen_lpeg);";deja=1}{print}'
}

sansRedis()
{
	OPTIONS="$OPTIONS -DENABLE_HIREDIS=OFF"
}

sansLuaJit()
{
	# Il plante chez moi.
	OPTIONS="$OPTIONS -DENABLE_LUAJIT=OFF"
	# Problème avec lua: la biblio est statique, et cmake génère un Makefile qui l'utilise via un (ou deux, d'ailleurs) /usr/local/lib/liblua.a, plutôt que conventionnellement par un -llua. Il faudra donc aller dans le dossier dans /tmp/, dans build, relancer make VERBOSE=1, repérer la commande pourrie, et la relancer à la main en ayant remplacé les occurrences. Et ce pour chaque exécutable lié. De plus à la fin il faudra renommer les deux exécutables de xxx-version en xxx, pour que l'install les trouve.
	echo -e '\033[0;31mAttention, vous devrez sans doute lier à la main (cf. fichier d'\''install)\033[0m'
}

# Variables

#archive="https://github.com/vstakhov/rspamd/archive/$version.tar.gz" # https://github.com/vstakhov/rspamd/issues/335
archive="https://rspamd.com/downloads/rspamd-$version.tar.xz"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX="$dest" $OPTIONS

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
