#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

logiciel=rsyncx

# Historique des versions gérées

version=2.5.5

version=2005-05-13
modifs=destSuivreLiens

# Modifications

destSuivreLiens()
{
	patch -p0 << TERMINE
--- ./generator.c	Sat Jan  3 12:21:39 2004
+++ ./generator.c	Sat May 14 23:52:55 2005
@@ -316,7 +316,7 @@
 		 * recursively create it. */
 
 		if (dry_run) return; /* XXXX -- might cause inaccuracies?? -- mbp */
-		if (statret == 0 && !S_ISDIR(st.st_mode)) {
+		if (statret == 0 && !S_ISDIR(st.st_mode) && !S_ISLNK(st.st_mode) /* À FAIRE: il faudrait vérifier que le lien est un lien sur dossier. */) {
 			if (robust_unlink(fname) != 0) {
 				rprintf(FERROR,
 					"recv_generator: unlink %s to make room for directory: %s\n",
TERMINE
}

# Variables

dest="/usr/local/$logiciel-$version"
archive=http://www.macosxlabs.org/rsyncx/rsync-$version.hfs.tgz
archive_cvs=cvs://anonymous@anoncvs.opendarwin.org:/Volumes/src/cvs/od:rsync_hfs

[ -d "$dest" ] && exit 0

if [[ $version = *-* ]] ; then
	obtenirEtAllerDansCvs -d $version $archive_cvs
else
	obtenirEtAllerDans "$archive"
fi

echo Correction… >&2
[ "x$modifs" = x ] || $modifs

echo Configuration… >&2
./configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sudo utiliser "$logiciel-$version"

rm -Rf /tmp/$$
