#!/bin/sh
# Copyright (c) 2007,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

archive="http://supportdownload.apple.com/download.info.apple.com/Apple_Support_Area/Apple_Software_Updates/Mac_OS_X/downloads/061-6195.20090429.Ti323/Safari3.2.3Ti.dmg"
archive="`obtenir "$archive"`"

montage="`hdid -plist "$archive" | awk '/<string>/{if(oui){sub(/^[ 	]*<string>/,"");sub(/<.string>.*$/,"");print;oui=0}}/mount-point/{oui=1}'`"

cd /tmp/
rm -Rf saf3temp
mkdir saf3temp
cd saf3temp
gunzip < "$montage/Safari3.2.3Ti.pkg/Contents/Archive.pax.gz" | pax -r

# Un joli paquet.

mkdir ./Applications/Safari.app/Contents/Resources/Frameworks
mv ./System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework ./System/Library/Frameworks/Contents/Resources/Frameworks/
mv ./System/Library/*Frameworks/*.framework ./Applications/Safari.app/Contents/Resources/Frameworks

# Remplacement de Safari par un lanceur.

mv ./Applications/Safari.app/Contents/MacOS/Safari ./Applications/Safari.app/Contents/MacOS/Safari.bin
cat > ./Applications/Safari.app/Contents/MacOS/Safari <<TERMINE
#!/bin/bash
SCRIPTS="\`command -v "\$0"\`" ; SCRIPTS="\`dirname "\$SCRIPTS"\`" ; [[ "\$SCRIPTS" = /* ]] || SCRIPTS="\`pwd\`/\$SCRIPTS"
export DYLD_FRAMEWORK_PATH="\$SCRIPTS/../Resources/Frameworks"
"\$SCRIPTS/Safari.bin"
TERMINE
chmod a+x ./Applications/Safari.app/Contents/MacOS/Safari

# Fini!

echo "L'application se trouve en `pwd`/Applications/Safari.app" >&2
