#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=cyrus-sasl

version=2.1.25
modifs=db5

# Modifications

db5()
{
	for f in utils/dbconverter-2.c sasldb/db_berkeley.c
	do
		filtrer "$f" sed -e 's/DB_VERSION_MAJOR == 4/DB_VERSION_MAJOR >= 4/g'
	done
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="ftp://ftp.cyrusimap.org/cyrus-sasl/$logiciel-$version.tar.gz"

[ -d "$dest" ] && exit 0

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" --with-saslauthd="$dest/var/state"

echo Compilation… >&2
make

echo Installation… >&2
sudo mkdir -p "$dest/var/state"
sudo make install
i="`cd "$dest/lib" && ls libsasl2.so.*`" ; sudo ln -s "$i" $dest/lib/libsasl2.so
[ ! -e /usr/lib/sasl2 -o -h /usr/lib/sasl2 ] && sudo rm -f /usr/lib/sasl2 && sudo ln -s "$dest/lib/sasl2" /usr/lib/sasl2

sutiliser $logiciel-$version

rm -Rf "$TMP/$$"

# Config:
#saslauthd -a pam
#[ -f /etc/pam.d/smtp ] || sudo sh -c 'cat > /etc/pam.d/smtp' <<TERMINE
#auth            required        pam_unix.so             no_warn try_first_pass
#account         required        pam_unix.so
#TERMINE
