#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 2.2 && prerequis="python meson ninja pkgconfig cmake gettext \\ glib libxml" && modifs="libpkgconfig" || true
v 2.3 && modifs="$modifs libcxxfs" || true
v 2.4 || true

# Modifications

libcxxfs()
{
	# Sur Raspbian avec un gcc 8.3, la 2.2 se lie bien, mais pas la 2.3 ni la 2.4:
	#   update-mime-database.cpp.o: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
	# nm -o /home/pi/tmp/shared-mime-info-2.4/build/src/update-mime-database.p/update-mime-database.cpp.o | grep filesystem.\*status
	#   /home/pi/tmp/shared-mime-info-2.4/build/src/update-mime-database.p/update-mime-database.cpp.o:         U _ZNSt10filesystem6statusERKNS_7__cxx114pathE
	# Après un grep -rl un peu long sur les dossiers système, on trouve la biblio correspondante:
	# nm -o /usr/lib/gcc/arm-linux-gnueabihf/8/libstdc++fs.a  | grep filesystem6status
	#   /usr/lib/gcc/arm-linux-gnueabihf/8/libstdc++fs.a:std-ops.o:00000000 T _ZNSt10filesystem6statusERKNS_7__cxx114pathE
	#   /usr/lib/gcc/arm-linux-gnueabihf/8/libstdc++fs.a:cow-std-ops.o:00000000 T _ZNSt10filesystem6statusERKNS_4pathE
	# Reste donc juste à lier la bête.
	# Ah tiens problème déjà rencontré par d'autres: https://stackoverflow.com/questions/53201991/how-to-use-stdfilesystem-on-gcc-8
	# Et attention pour le test, les biblios vont à la fin (https://stackoverflow.com/a/11894098/1346819)
	
	local cpf ldf
	
	cat > $TMP/$$/1.c++ <<TERMINE
#include <filesystem>

int main(int argc, char ** argv)
{
	std::filesystem::path c;
	std::filesystem::file_status e = std::filesystem::status(c);
	return 0;
}
TERMINE
	if compilo_test $CXX -o $TMP/$$/1 $TMP/$$/1.c++ ; then return 0 ; fi
	cpf="-std=c++17" ldf="-lstdc++fs"
	if compilo_test $CXX $cpf -o $TMP/$$/1 $TMP/$$/1.c++ $ldf ; then export CXXFLAGS="$CXXFLAGS $cpf" LDFLAGS="$LDFLAGS $ldf" ; return 0 ; fi
	echo "# Impossible de compiler / lier filesystem::status()." >&2
	return 1
}

libpkgconfig()
{
	filtrer meson.build sed -e "s#get_option('datadir') / 'pkgconfig'#get_option('prefix') / 'lib' / 'pkgconfig'#"
}

# Variables

archive="https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/$version/shared-mime-info-$version.tar.gz"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
mkdir -p build
meson setup build --buildtype=release --prefix="$dest"
cd build
make=ninja

echo Compilation… >&2
$make

echo Installation… >&2
sudokupy $make install

sutiliser
