#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

set -e

version="`grep '#define SOUDOIE_VERSION' < "$SCRIPTS/src/soudoie/version.h" | awk '{v=$3;gsub(/"/,"",v);print v}'`"

guili_localiser_soudoie()
{
	sudoku -f sh -c "chown -R 0:0 '$dest' && chmod 4755 '$dest/bin/soudoie'"
}

guili_localiser="$guili_localiser guili_localiser_soudoie"

archive=soudoie-$version.tar.gz

analyserParametres()
{
	vars=""
	config=
	while [ $# -gt 0 ] ; do
		case "$1" in
			--conf=*) config="`echo "$1" | cut -d = -f 2-`" ;;
			*) apAffecter "$1" $vars ;;
		esac
		shift
	done
	
	OPTIONS_CONF=
	if [ -n "$config" ]
	then
		local optconf="`echo "_$config" | sed -e 's/[^a-z0-9]/_/g' -e 's/___*/_/g' -e 's/_$//'`"
		argOptions="`options "$argOptions+conf$optconf"`"
		OPTIONS_CONF="$OPTIONS_CONF --conf=$config"
	fi
}

analyserParametres "$@"

option pcre || true # À FAIRE: gérer.
prerequis

destiner

( cd "$SCRIPTS/src/soudoie" && tar cf - . | gzip > "$INSTALL_MEM/$archive" ) # Inutile d'aller chercher l'archive, faisons comme si elle avait déjà été téléchargée.
obtenirEtAllerDansVersion || true # Récupère la version binaire si besoin.

./configure --prefix="$dest" $OPTIONS_CONF

./make

SANSSU=0 # À partir de là, on a tout plein de trucs à faire en vrai root, quel que soit le dossier d'install.

sudoku ./make install

sutiliser
