#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 14.5.1.1 || true
v 14.7.0.3 || true

archive=https://codeberg.org/sox_ng/sox_ng/releases/download/sox_ng-$version/sox_ng-$version.tar.gz

predestiner="optionnels"

optionnels()
{
	local o
	departager()
	{
		o="$1"
		case "$2" in ?*) OPTIONS_CONF="$OPTIONS_CONF$2 " ;; esac
	}
	for o in flac id3tag lame mad ogg ao:libao vorbis/vorbis-tools opus/opusfile iconv "curl --with-curl" "ffmpeg --with-ffmpeg" png/libpng
	do
		case "$o" in
			*" "*) departager $o ;;
		esac
		optionSi $o || true
	done
	if option opus ; then prerequis="$prerequis opus" ; modifs="$modifs plusopus" ; fi
}

plusopus()
{
	# opus/opusfile.h inclut opus_multistream.h sans préciser le opus/.
	CPPFLAGS="$CPPFLAGS -I$destopus/include/opus"
}

for modif in true $predestiner ; do "$modif" ; done

destiner

prerequis

obtenirEtAllerDansVersion

echo Corrections… >&2
for modif in true $modifs ; do "$modif" ; done

echo Configuration… >&2

./configure --prefix="$dest" --enable-replace $OPTIONS_CONF

echo Compilation… >&2
make

echo Installation… >&2
sudoku mkdir -p "$dest/include" "$dest/lib/pkgconfig"
sudoku make install

sutiliser
