#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e


DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

prerequis="zlib ncurses readline"
v 3.0.7 || true
v 3.6.4 || true
v 3.6.23.1 && modifs=foutuTclPourLePointH || true
v 3.7.17 && v_annee=2013 && modifs= || true
v 3.14.1 && v_annee=2016 || true
v 3.22.0 && v_annee=2018 || true
v 3.29.0 && v_annee=2019 || true

# Modifications

foutuTclPourLePointH()
{
	for i in main.mk Makefile.in
	do
		filtrer "$i" sed -e "s#tclsh .*/mksqlite3h.tcl#\"$SCRIPTS/sqlite_mksqlite3h.sh\"#"
	done
}

# Variables

archive="http://www.sqlite.org/$logiciel-$version.tar.gz"
version_="`echo "$version" | tr . _`"
pge "$version" 3.6.24 && archive="http://www.sqlite.org/sqlite-amalgamation-$version_.zip"
version0="`echo "$version.0" | tr . '\012' | sed -e '2,$s/^/00/' -e '2,$s/.*\(..\)$/\1/' -e '5,63d' | tr -d '\012'`"
pge $version 3.7 && archive="http://www.sqlite.org/$v_annee/sqlite-autoconf-$version0.tar.gz"

destiner

prerequis

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if pge $version 3.6.24 && ! pge $version 3.7
then
	true
else
	./configure --prefix="$dest" --enable-threadsafe $options
fi

echo Compilation… >&2
if pge $version 3.6.24 && ! pge $version 3.7
then
	if uname | grep -q Linux
	then
		cc -fPIC -c sqlite3.c -o sqlite3.o && ar rcs libsqlite3.a sqlite3.o && gcc -shared -o libsqlite3.so sqlite3.o
	else
	cc -c sqlite3.c -o sqlite3.o && ar rcs libsqlite3.a sqlite3.o && gcc -shared -o libsqlite3.so sqlite3.o
	fi
else
	make
fi

echo Installation… >&2
if pge $version 3.6.24 && ! pge $version 3.7
then
	sudo mkdir -p "$dest/lib" "$dest/include"
	sudo cp libsqlite3.a "$dest/lib/"
	sudo cp sqlite3.h "$dest/include"
else
	sudo make install
fi

sutiliser
