#!/bin/sh
# Copyright (c) 2004-2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"
. "$SCRIPTS/util.opt.pcre.sh"

# Historique des versions gérées

# Pour tester le module dont on dispose: sqlite3 /tmp/1.sqlite3 ".load …/sqlite-pcre" "select 'a' regexp '['":
#     intégré	Error: stepping, unclosed '['
#       PCRE1	Error: stepping, [a: missing terminating ] for character class (offset 2)
#       PCRE2	Error: stepping, [a: missing terminating ] for character class (offset 2)
#   hyperscan	Error: stepping, [a: Unterminated character class starting at index 0.
# Temps d'exéc (recherche d'un gros | de 400 items (= 4 Ko d'expression) sur une base de 70 Mo:
#     intégré	55 mn
#       PCRE1	1'20"
#       PCRE2	4'20"
#   hyperscan	23 mn

prerequis="sqlite pcre"
v 2007.01.20 && versionComplete="$version.4229ecc3.git" || true
v 2007.01.20.1 && versionComplete="$version.bc988508.git" || true
v 2021.10.06 && versionComplete="$version.ae8a1c03.git" || true

# À FAIRE: normaliser en une option +pcre1, +pcre2, ou +hyperscan.
if option hyperscan
then
	virerPrerequis pcre
	prerequis="$prerequis hyperscan"
fi

configurer()
{
	if option hyperscan
	then
		CPPFLAGS="$CPPFLAGS -DWITH_HYPERSCAN=1"
		CFLAGS="$CFLAGS -fPIC"
		biblios=-lhs
		echo "Biblio regex: [32mHyperscan[0m"
	elif pge $version_pcre 10
	then
		biblios=-lpcre2-8
		CPPFLAGS="$CPPFLAGS -DWITH_PCRE2=1"
		echo "Biblio regex: [32mPCRE[36m2[0m"
	else
		biblios=-lpcre
		CPPFLAGS="$CPPFLAGS -DWITH_PCRE1=1"
		echo "Biblio regex: [32mPCRE[36m1[0m"
	fi
}

# Variables

archive="http://git.altlinux.org/people/at/packages/?p=sqlite3-pcre.git;a=blob_plain;f=pcre.c;h=$rev"
archive_git="https://github.com/outtersg/sqlite3-pcre.git"
archive_git_locale="$HOME/src/projets/sqlite3-pcre"
[ -d "$archive_git_locale" ] && archive_git="$archive_git_locale" || true

prerequisPcre pcre2 pcre1

prerequis

destiner

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
configurer

echo Compilation… >&2
$CC -fPIC -shared -o sqlite-pcre.so $CPPFLAGS $CFLAGS pcre.c $LDFLAGS $biblios -lsqlite3

echo Installation… >&2
sudoku mkdir -p "$dest/lib"
sudoku cp sqlite-pcre.so "$dest/lib/"

sutiliser

echo "[33m# Pensez à activer l'extension en ajoutant dans votre \$HOME/.sqliterc un:[0m" >&2
echo ".load $INSTALLS/lib/sqlite-pcre.so"
