#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delibere() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delibere ; s="`dirname "$s"`" ; Delibere ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

logiciel=sslh

# Historique des versions gérées

# À FAIRE: pcre est peut-être optionnel.
v 1.18 && prerequis="make \\ pcre" && modifs="sansLibConfig" || true
v 1.22.2 || true
v 1.23.0 || true
v 2.0.0 && prerequis="$prerequis libevent" && modifs="$modifs sansLibevCrade" || true
v 2.0.1 || true

# Modifications

sansLibevCrade()
{
	local f
	for f in Makefile Makefile.in
	do
		[ -f "$f" ] || continue
		filtrer $f sed -e '/^sslh:.*sslh-ev/s/ sslh-ev//'
	done
}

sansLibConfig()
{
	filtrer Makefile sed -e '/^USELIBCONFIG=/c\
USELIBCONFIG=
'
}

# Variables

varch=$version
pge $version 1.23 || { varcher() { local vmin=$3 ; case vmin in ?*) vmin=`{ echo obase=16 ; echo $vmin+10 ; } | bc | tr A-Z a-z` ;; esac ; varch=$1.$2$vmin ; } ; IFS=. ; tifs varcher $version ; }
case $version in *[b-z]) varch="`printf %s $version | tr -d a-z`.`printf %s ${version}-A | tr a-z0-9. A-Z | bc`" ;; esac
archive="https://github.com/yrutschle/sslh/archive/refs/tags/v$varch.tar.gz"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2

echo Compilation… >&2
make

echo Installation… >&2
sudo mkdir -p "$dest/bin"
sudo cp sslh-fork "$dest/bin/"
sudo ln -s sslh-fork "$dest/bin/sslh"

sutiliser
