#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=ssmtp

# Historique des versions gérées

v 2.65 && modifs="configIci laisseFrom" || true

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi <serveur smtp> [<domaine émission>] [<adrél émetteur>]
TERMINE
	exit 1
}

analyserParametres()
{
	vars="smtp domaine emetteur"
	for i in $vars
	do
		eval $i=
	done
	while [ $# -gt 0 ]
	do
		case "$1" in
			*)
				[ -z "$vars" ] && auSecours
				for i in $vars
				do
					eval $i="$1"
					break
				done
				vars="`echo "$vars" | sed -e 's/[^ ]* //'`"
				;;
		esac
		shift
	done

	[ ! -z "$smtp" ] || auSecours
}

analyserParametres "$@"

prerequis

# Modifications

configIci()
{
	[ -z "$domaine" ] || confDomaine="hostname=$domaine"
	[ -z "$emetteur" ] || confEmetteur="root=$emetteur"
	cat > generate_config <<TERMINE
#!/bin/sh
cat > "\$1" <<FINI
mailhub=$smtp
$confDomaine
$confEmetteur
FINI
TERMINE
}

laisseFrom()
{
	patch -p0 <<TERMINE
--- ssmtp.c	2013-12-18 12:20:23.000000000 +0100
+++ ssmtp.c	2016-09-21 16:41:46.257322000 +0200
@@ -712,7 +712,7 @@
 			uad = from_strip(ht->string);
 		}
 		else {
-			return;
+			//return;
 		}
 #endif
 		have_from = True;
TERMINE
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="https://github.com/ajwans/sSMTP/archive/master.zip#/$logiciel-$version.zip"

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
