#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=strider

v 1.6.5 && modifs="" && prerequis="nodejs >= 0.10 mongodb" || true

archive="https://github.com/Strider-CD/strider/archive/v$version.tar.gz"

auSecours()
{
	moi="`basename "$0"`"
	cat >&2 <<TERMINE
# Utilisation: $moi <répertoire destination>
TERMINE
	exit 1
}

analyserParametres()
{
	vars="dest"
	while [ $# -gt 0 ]
	do
		case "$1" in
			*) apAffecter "$1" $vars ;;
		esac
		shift
	done
}

analyserParametres "$@"

[ -z "$dest" ] && auSecours
echo "$dest" | grep -q ^/ || dest="`pwd`/$dest"

prerequis

echo Obtention et décompression… >&2
( obtenirEtAllerDansVersion > /dev/null && tar cf - . ) | ( mkdir -p "$dest" && cd "$dest" && tar xf - )

cd "$dest"

echo Correction… >&2
for modif in true $modifs ; do $modif "$@" ; done

echo Installation… >&2
if [ ! -z "$ALL_PROXY" ]
then
	cat > .bowerrc <<TERMINE
{
	"https-proxy": "$ALL_PROXY",
	"proxy": "$ALL_PROXY",
	"directory": "bower_components",
	"analytics": false,
	"interactive": false
}
TERMINE
fi
npm install

echo Création d\'un compte admin… >&2
node bin/strider addUser

rm -Rf "$TMP/$$"
