#!/bin/sh
# Copyright (c) 2004,2008 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

v 1.2.3 && prerequis="apr apr-util gettext neon db" || true
v 1.4.6 && modifs="lssl" || true
v 1.7.2 && modifs= || true
v 1.7.6 && modifs=destdir || true
v 1.7.10 && modifs=destdir || true
v 1.8.0 && modifs="exclusivementPrerequis" && prerequis="pkgconfig \\ apr apr-util gettext expat zlib serf >= 1.2.1 sqlite" || true # La détection de serf est faite via pkgconfig.
v 1.8.3 || true # La détection de serf est faite via pkgconfig.
v 1.8.11 || true
v 1.8.15 || true
v 1.9.1 && modifs="moiDAbord" || true
v 1.9.4 || true
v 1.9.5 || true
v 1.9.7 || true
v 1.9.9 || true
v 1.9.10 || true
# La 1.10.2 est super chiante, dans la résolution de conflits d'arbo (nouvelle fonctionnalité) elle mouline des dizaines de secondes avant de se planter complètement de diagnostic.
#v 1.10.2 && modifs="moiDAbord lz4interne" && prerequis="$prerequis utf8proc" || true

prerequis

# Modifications

lz4interne()
{
	OPTIONS_CONF="$OPTIONS_CONF --with-lz4=internal"
}

moiDAbord()
{
    # Lors de l'install, ce crétin, sous Linux, essaie de se relier à lui-même. Manque de bol, il utilise les chemins qu'on lui a fournis en priorité sur les siens. Du coup il essaie de lier ses bibliothèques avec celles d'une vieille version qui a le malheur d'être installée dans le PATH.

	pwd="`pwd`"
	LDFLAGS="`ls -d "$pwd/subversion/"libsvn_* | sed -e 's/^/-L/' -e 's#$#/.libs#' | tr '\012' ' '` $LDFLAGS"
    export LD_FLAGS
}

lssl()
{
	filtrer configure sed -e '/if.*with_ssl/a\
  LIBS="-lssl $LIBS"
'
}

destdir()
{
	# Un APACHELIBEXECDIR = DESTDIR dans le Makefile, qui fait assez moche, et fait planter un libtool.
	export DESTDIR="$dest/lib"
}

# Variables

archive="http://subversion.tigris.org/tarballs/subversion-$version.tar.bz2"
pge $version 1.6.9 && archive="http://mirrors.ircam.fr/pub/apache/subversion/subversion-$version.tar.bz2"

destiner

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
OPTIONS_CONF=
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" --with-ssl $OPTIONS_CONF

echo Compilation… >&2
make -j 3

echo Installation… >&2
sudo make install

sutiliser
