#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=tesseract

# Historique des versions gérées

v 3.02.02 && modifs="libpthread" && prerequis="leptonica" || true

prerequis

# Modifications

libpthread()
{
	if [ `uname` = FreeBSD ]
	then
		LDFLAGS="$LDFLAGS -lpthread"
	fi
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="https://tesseract-ocr.googlecode.com/files/tesseract-ocr-$version.tar.gz"
v_min="`echo "$version" | sed -e 's/\([0-9]*\.[0-9]*\).*/\1/'`"
archive_fr="https://tesseract-ocr.googlecode.com/files/tesseract-ocr-$v_min.fra.tar.gz"

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
obtenirEtAllerDans "$archive_fr"
sudo cp tessdata/fra.traineddata "$dest/share/tessdata/eng.traineddata" # En tant qu'eng pour l'avoir par défaut.
sutiliser "$logiciel-$version"

rm -Rf "$TMP/$$"
