#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 3.02.02 && modifs="libpthread" && prerequis="leptonica" || true
v 3.05.02 && prerequis="autoconf automake m4 libtool pkgconfig \\ $prerequis" && remplacerPrerequis "leptonica >= 1.74" || true
v 4.1.3 && remplacerPrerequis "leptonica >= 1.74.2" || true
v 5.5.1 || true

# À FAIRE: pour l'entraînement, demande ICU 52.1, pango 1.38, cairo

prerequis

# Modifications

libpthread()
{
	if [ `uname` = FreeBSD ]
	then
		LDFLAGS="$LDFLAGS -lpthread"
	fi
}

# Variables

archive="https://tesseract-ocr.googlecode.com/files/tesseract-ocr-$version.tar.gz"
archive="https://github.com/tesseract-ocr/tesseract/archive/$version.tar.gz"
v_min="`echo "$version" | sed -e 's/\([0-9]*\.[0-9]*\).*/\1/'`"
archive_fr="https://tesseract-ocr.googlecode.com/files/tesseract-ocr-$v_min.fra.tar.gz"
archive_fr="https://github.com/tesseract-ocr/tessdata/raw/master/fra.traineddata"
archive_fr="https://github.com/tesseract-ocr/tessdata/raw/refs/heads/main/fra.traineddata"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if [ ! -e configure ] # La 3.04.01 est la dernière livrée avec son configure (https://github.com/tesseract-ocr/tesseract/issues/1219#issuecomment-346791112).
then
	export LIBTOOL="`command -v libtool`"
	./autogen.sh || ./autogen.sh # La première fois il nous pète à la gueule disant qu'il lui manque LIBTOOL.
fi
./configure --prefix="$dest"

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
case "$archive_fr" in
	*.tar.gz)
obtenirEtAllerDans "$archive_fr"
sudo cp tessdata/fra.traineddata "$dest/share/tessdata/eng.traineddata" # En tant qu'eng pour l'avoir par défaut.
		;;
	*.traineddata)
		curl -O -L "$archive_fr"
		sudoku cp "`basename "$archive_fr"`" "$dest/share/tessdata/eng.traineddata"
		;;
esac

sutiliser
