#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Historique des versions gérées

v 1.8.4 && modifs="sansdoc" || true
# J'ai la même chose que https://github.com/tinyproxy/tinyproxy/issues/274
v 1.10.0 || true
v 1.10.2020.01.15 && versionComplete="$version.2e02dce0c3de4a231f74b44c34647406de507768.git" || true
v 1.10.2020.10.19 && versionComplete="$version.adad565c03f3ffde6520646bc5d119ce1eadbadb.git" && modifs="$modifs linemax" || true

# Modifications

linemax()
{
	[ `uname` = FreeBSD ] || return 0
	filtrer src/conf.c awk '/#include/&&!oui{print "#include <limits.h>";oui=1}{print}'
}

sansdoc()
{
	if pge $version 1.10.2020.10
	then
		optionsConf="$optionsConf --disable-manpage-support"
	fi
	
	# asciidoc est vraiment trop vieux, et requiert un vraiment trop vieux Python.
	rm -Rf docs
	if [ -e configure ]
	then
	filtrer configure sed -e '/^ac_config_files=/s# docs/[^ "]*##g'
	else
		filtrer configure.ac grep -v '^docs/'
	fi
	if [ -e Makefile.in ]
	then
	filtrer Makefile.in grep -v docs
	else
		filtrer Makefile.am grep -v docs
	fi
}

# Variables

archive="https://github.com/tinyproxy/tinyproxy/releases/download/$version/tinyproxy-$version.tar.bz2"
archive_git="https://github.com/tinyproxy/tinyproxy.git"

case "$versionComplete" in
	*.git) prerequis="git autoconf automake m4 \\ $prerequis" ;;
esac

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
if [ -e configure ]
then
	./configure --prefix="$dest" $optionsConf
else
	./autogen.sh --prefix="$dest" $optionsConf
fi

echo Compilation… >&2
make

echo Installation… >&2
sudo make install

sutiliser
