#!/bin/sh
# Copyright (c) 2004,2009 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=unison

v 2.40.63 && prerequis="ocaml < 4" && modifs="espaces" || true
v 2.40.128 || true
v 2.48.4 && prerequis="ocaml >= 4 < 4.04" && modifs="espaces sansVersionMac" || true
v 2.51.2 && prerequis="ocaml >= 4" || true

# Modifications

sansVersionMac()
{
	filtrer Makefile.OCaml sed -e 's/-ccopt -mmacosx-version-min=[^ ]*/ /g'
}

espaces()
{
	CPPFLAGS="`echo " $CPPFLAGS" | sed -e 's/ -I/ -I /g'`"
	CFLAGS="`echo " $CFLAGS" | sed -e 's/ -I/ -I /g'`"
	export CPPFLAGS CFLAGS
}

# Variables

dest="$INSTALLS/$logiciel-$version"
archive="http://www.seas.upenn.edu/~bcpierce/unison//download/releases/unison-$version/unison-$version.tar.gz"

[ -d "$dest" ] && exit 0

prerequis

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2

echo Compilation… >&2
make UISTYLE=text

echo Installation… >&2
sudo mkdir -p "$dest/bin"
sudo cp unison "$dest/bin/"

sutiliser $logiciel-$version

rm -Rf "$TMP/$$"
