#!/bin/sh
# Copyright (c) 2018 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delibere() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delibere ; s="`dirname "$s"`" ; Delibere ; SCRIPTS="$s" ; } ; SCRIPTS
ICI="$PWD" # util.sh nous place dans un dossier temporaire, pour le cas (classique) où nous sommes un installeur. Sauf que nous sommes un outil autonome, et nos règles de fonctionnement sont différentes.
. "$SCRIPTS/util.sh"
cd "$ICI"

util_var()
{
	varsPrerequis "$@"
}

# Combine une recherche de déjà installé, et son installation si besoin.
# Utilisation: guili <logiciel> <option>* <contrainte version>* <param install>*
guili()
{
	local err_deja=0
	local err_installee=0
	local err_err=-1
	
	while [ $# -gt 0 ]
	do
		case "$1" in
			--si-deja) shift ; err_deja="$1" ;;
			--si-installee) shift ; err_installee="$1" ;;
			*)
				if ! _guiliChercher "$@"
				then
					_guiliInstaller "$@" || return "$?"
					return $err_installee
				fi
				return $err_deja
				;;
		esac
		shift
	done
}

_guiliChercher()
{
	(
		local l="$1"
		analyserParametresInstall "$@"
		versions "$l+$argOptions" "`argVersion "$@"`" | grep -q .
	)
}

_guiliInstaller()
{
	local l="$1" ; shift
	local o=
	case "$l" in
		*+*)
			o="+`echo "$l" | cut -d + -f 2-`"
			l="`echo "$l" | cut -d + -f 1`"
			;;
	esac
	"$SCRIPTS/$l" $o "$@"
}

# Environne, Prérequiert, et Opère (Enveloppe)
# Utilisation:
#   epo var="val" var="val" commande args*
# La forme simplifiée:
#   epo "<prérequis>"
# est équivalente à:
#   epo prerequis="<prérequis>" prerequis \; sh
# À FAIRE?: créer des alias e ou sh? Afin de ne pas polluer avec une fonction shell on pourrait le faire dans le case général.
epo()
{
	local prerequis _epo_bouffes _epo_qqc
	
	case " $* " in
		*" prerequis "*) true ;; # Déjà un appel à prerequis explicite.
		*) # prerequis implicite, on doit déterminer où le caler (après la définition des prerequis).
			while [ $# -gt 0 ]
			do
				# Pour distinguer un = affectation d'un = dans "truc >= 1.2", pas vraiment d'autre moyen que grep.
				if printf %s "$1" | grep -q '^[a-zA-Z_][a-zA-Z0-9_]*='
				then
					IFS="="
					_epo_setvar "$1"
					shift
				else
					break
				fi
			done
			# Si prerequis n'a pas été explicitement définie, le premier paramètre s'y colle.
			case "$prerequis" in
				"") prerequis="$1" ; shift ;;
			esac
			_epo_exec prerequis
			;;
	esac
	
	# Exécution!
	
	while [ $# -gt 0 ]
	do
		_epo_exec "$@"
		shift $_epo_bouffes
		case "$1" in \;) shift ;; esac
	done
	
	# Si rien n'a été lancé, on veut entrer dans un shell.
	case "$_epo_qqc" in "")
		local _epo_id="`id -u`"
		local _epo_sh="`getent passwd $_epo_id | sed -e 's/.*://'`"
		[ -n "$_epo_sh" -a -f "$_epo_sh" -a -x "$_epo_sh" ] || _epo_sh=sh
		PS1="epo> " "$_epo_sh"
	;; esac
}

_epo_setvar()
{
	local var="$1"
	shift
	#eval $var='"$*"'
	setvar $var "$*"
	unset IFS
}

# Exécute jusqu'au point-virgule.
_epo_exec()
{
	local _epo_p _epo_init=1 _epo_modif
	for _epo_p in "$@"
	do
		case "$_epo_init" in 1) set -- ; _epo_init= ;; esac # Si on est à l'initialisation, on repart d'une liste de paramètres vides.
		case "$_epo_p" in \;) break ;; esac
		set -- "$@" "$_epo_p"
	done
	"$@"
	_epo_bouffes=$#
	
	case "$1" in
		prerequis)
			# Cas particulier: prerequis prépare l'environnement mais ne l'exécute pas.
			for _epo_modif in $modifs
			do
				$_epo_modif
			done
			;;
		*)
			# Pour tout le reste: on signale qu'on a lancé une charge utile.
			_epo_qqc=1
			;;
	esac
}

util_commande="$1" ; shift
case "$util_commande" in
	var) util_commande=util_var ;;
esac
"$util_commande" "$@"
