#!/bin/sh
# Copyright (c) 2018 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; [ -x "$SCRIPTS" -o ! -x "$0" ] || SCRIPTS="$0" ; case "`basename "$SCRIPTS"`" in *.*) true ;; *sh) SCRIPTS="$1" ;; esac ; case "$SCRIPTS" in /*) ;; *) SCRIPTS="`pwd`/$SCRIPTS" ;; esac ; delie() { while [ -h "$SCRIPTS" ] ; do SCRIPTS2="`readlink "$SCRIPTS"`" ; case "$SCRIPTS2" in /*) SCRIPTS="$SCRIPTS2" ;; *) SCRIPTS="`dirname "$SCRIPTS"`/$SCRIPTS2" ;; esac ; done ; } ; delie ; SCRIPTS="`dirname "$SCRIPTS"`" ; delie
. "$SCRIPTS/util.sh"

util_var()
{
	varsPrerequis "$@"
}

# Combine une recherche de déjà installé, et son installation si besoin.
# Utilisation: guili <logiciel> <option>* <contrainte version>* <param install>*
guili()
{
	local err_deja=0
	local err_installee=0
	local err_err=-1
	
	while [ $# -gt 0 ]
	do
		case "$1" in
			--si-deja) shift ; err_deja="$1" ;;
			--si-installee) shift ; err_installee="$1" ;;
			*)
				if ! _guiliChercher "$@"
				then
					_guiliInstaller "$@" || return "$?"
					return $err_installee
				fi
				return $err_deja
				;;
		esac
		shift
	done
}

_guiliChercher()
{
	(
		local l="$1"
		analyserParametresInstall "$@"
		versions "$l$argOptions" "`argVersion "$@"`" | grep -q .
	)
}

_guiliInstaller()
{
	local l="$1" ; shift
	local o=
	case "$l" in
		*+*)
			o="+`echo "$l" | cut -d + -f 2-`"
			l="`echo "$l" | cut -d + -f 1`"
			;;
	esac
	"$SCRIPTS/$l" $o "$@"
}

util_commande="$1" ; shift
case "$util_commande" in
	guili) guili "$@" ;;
	versions) versions "$@" ;;
	var) util_var "$@" ;;
	*) "$util_commande" "$@" ;;
esac
