#!/bin/sh

prefixe=/usr/local

[ -z "$PREFIXE_UTILISER" ] || prefixe="$PREFIXE_UTILISER"
[ "x$1" = "x-r" ] && shift && prefixe="$1" && shift

if [ \( "x$1" = x \) -o ! -d "$prefixe/$1" ]
then
	echo '# Utiliser'
	echo '# Crée des liens de /usr/local/<x> vers /usr/local/<biblio>/<x>'
	echo '# © Guillaume Outters 2003-2004,2007'
	echo
	echo 'Utilisation: '"$0"' <biblio>'
	exit 1
fi

allerUtiliser()
{
	local i
	local j
	local k
	# Juste le nom de l'app.
	i="`echo "$1" | sed -e 's#/.*##'`"
	cd "$prefixe/$i"
	# Le nom de tout ce qui est après l'app (avec le / reporté à la fin).
	k="`echo "$1" | sed -e 's#^[^/]*##' -e 's#$#/#' -e 's#^/##'`"
	# Les .. correspondant à tout ce qui est après l'app.
	j="`echo "$1" | sed -e 's#^[^/]*##' -e 's#/[^/]*#..@#g' -e 's#@#/#g'`"
	utiliserEtoile "$j$i" "$k"
}

racine()
{
	echo "$1" | sed -e 's#-[^-]*[0-9.][0-9.]*.*$##'
}

statn()
{
	case `uname` in
		FreeBSD) stat "$@" ;;
		*) stat -f "%N" "$@" ;;
	esac
}

utiliserEtoile()
{
	if statn "$2"* 2> /dev/null > /dev/null
	then
		utiliser "$1" "$2"*
	else
		utiliser "$1"
	fi
}

utiliser()
{
	local ou="$1"
	local a
	shift
	until [ $# = 0 ]
	do
		# On commence par virer les liens qu'une de nos précédentes versions
		# auraient placés, et pour les liens déjà utilisés par un autre
		# logiciel, on les remplace si possible par un dossier qu'on va se
		# partager.
		if [ -L "$prefixe/$1" ]
		then
			a="`readlink "$prefixe/$1"`" # Vers où ça pointe pour l'heure?
			if [ "`racine "$a"`" = "`racine "$ou"`" ] # Même racine, mettons version plus ancienne, on écrase.
			then
				rm "$prefixe/$1"
			elif [ -d "$prefixe/`dirname "$1"`/$a" ] # La destination est un répertoire, on peut l'utiliser.
			then
				rm "$prefixe/$1"
				mkdir "$prefixe/$1"
				a="`echo "$a" | sed -e 's#\.\./##g'`"
				echo "On ménage $a…" >&2
				( allerUtiliser "$a" )
			else
				echo "$1 déjà occupé par $a" >&2
			fi
		fi
		if [ -d "$1" -a -d "$prefixe/$1" -a ! -L "$prefixe/$1" ]
		then
			utiliserEtoile "../$ou" "$1/"
		elif [ \( ! -e "$prefixe/$1" \) ]
		then
			ln -s "$ou/$1" "$prefixe/$1"
		else
			echo Impossible d\'écraser $1
		fi
		shift
	done
}

allerUtiliser "$1"
