#!/bin/sh
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# git: pour récupérer les extensions
# openssl: pour httpfs
prerequis="meson ninja pkgconfig \\ wayland-protocols libxml"
v 0.10.0 && modifs="usrLocalInclude linuxInput" || true

archive=https://github.com/WayfireWM/wayfire/releases/download/v$version/wayfire-$version.tar.xz

linuxInput()
{
	# Sous FreeBSD, input.h et input-event-codes.h sont dans …/include/dev/evdev/ et non …/include/linux/ (ou alors uniquement si on a installé la couche de compat Linux).
	# Le problème est que la coquille n'est pas dans notre source, mais dans le paquet installé par les ports: on ne peut donc pas corriger, juste poser un fichier équivalent.
	echo "#include <linux/input.h>" > $TMP/$$/1.c
	echo "#include <dev/evdev/input.h>" > $TMP/$$/2.c
	if ! compilo_test $CC -E $TMP/$$/1.c > /dev/null 2>&1 && compilo_test $CC -E $TMP/$$/2.c > /dev/null 2>&1
	then
		mkdir -p $TMP/$$/linux
		echo "#include <dev/evdev/input.h>" > $TMP/$$/linux/input.h
		echo "#include <dev/evdev/input-event-codes.h>" > $TMP/$$/linux/input-event-codes.h
		export CPPFLAGS="-I$TMP/$$ $CPPFLAGS"
	fi
}

usrLocalInclude()
{
	# Notre GuiLI vire /usr/local/include, à une époque fourre-tout équivalent à $INSTALLS, pour éviter d'embarquer involontairement des logiciels GuiLI non cités dans les $prerequis.
	# Mais sous FreeBSD, c'est aussi un dossier système (au même titre qu'/usr/include), et notamment on veut pouvoir utiliser certaines couches système non installées par GuiLI (ex.: /usr/local/include/GLES2/gl2.h)
	export CPPFLAGS="$CPPFLAGS -I/usr/local/include"
}

predestiner=
for modif in true $predestiner ; do "$modif" ; done
destiner

prerequis

obtenirEtAllerDansVersion

echo Corrections… >&2
for modif in true $modifs ; do "$modif" ; done

echo Configuration… >&2
meson setup build --prefix="$dest"

echo Compilation… >&2
cd build
ninja
for modif in true $modifspostcompil ; do $modif "$@" ; done

echo Installation… >&2
sudoku ninja install

sutiliser
