#!/bin/sh
# Copyright (c) 2004 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.bash"

logiciel=wx

version=2.8.11
modifs=dyld105

version=2.8.12
modifs=dyld105

version=2.9.2
modifs="cocoa dyld105"

inclure libpng # Avant la 1.5, sinon on a des appels qui sautent.

dest="$INSTALLS/$logiciel-$version"
suffixe=gz
pge $version 2.9 && suffixe=bz2
archive="http://heanet.dl.sourceforge.net/project/wxwindows/$version/wxWidgets-$version.tar.$suffixe"

# Modifications

cocoa()
{
	supplementConf="-with-osx_cocoa"
}

[ -d "$dest" ] && exit 0

echo Obtention et décompression… >&2
obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure CFLAGS="-arch i386" CXXFLAGS="-arch i386" CPPFLAGS="-arch i386 $CPPFLAGS" LDFLAGS="-arch i386 $LDFLAGS" OBJCFLAGS="-arch i386" OBJCXXFLAGS="-arch i386" --prefix="$dest" --enable-unicode $supplementConf

echo Compilation… >&2
make

echo Installation… >&2
sudo make install
sudo ln -s libwx_macu_qa-2.8.dylib "$dest/lib/libwx_macud_qa-2.8.dylib" # spring-lobby voudrait qu'on compile en debug.

sutiliser "$logiciel-$version"

rm -Rf $TMP/$$
