#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"

# Travail préalable: notre PHP donne des contraintes de version.

analyserParametresPour --pour php "$@"

# https://xdebug.org/docs/compat
# /!\ Parfois en contradiction avec https://github.com/xdebug/xdebug.org/blob/master/src/XdebugVersion.php; on met en commentaire la version max proposée par ce dernier.
case `php-config --version | cut -d . -f 1-2` in
	5.3) argVersion="$argVersion < 2.3" ;;
	5.4) argVersion="$argVersion < 2.5" ;;
	5.[56]) argVersion="$argVersion < 2.6" ;;
	7.0) argVersion="$argVersion >= 2.4 < 2.7" ;; # < 2.9
	7.1) argVersion="$argVersion >= 2.5 < 3.0" ;;
	7.2) argVersion="$argVersion >= 2.6" ;;
	7.[34]) argVersion="$argVersion >= 2.7" ;;
	7.*) argVersion="$argVersion >= 2.7" ;;
	8.0) argVersion="$argVersion >= 3.0" ;;
	8.*) argVersion="$argVersion >= 3.1" ;;
esac

# Historique des versions gérées

# make: mon FreeBSD make n'arrive pas à renseigner $^ sur une règle pourtant ultra simple (debugclient: main.o usefulstuff.o), et fait générer une "clang: error: no input files".
v 2.1.0 && prerequis="make autoconf \\ $prerequis" || true
v 2.2.1 || true
v 2.2.5 || true
v 2.2.7 || true
v 2.4.1 || true
v 2.5.5 || true
v 2.6.0 || true
v 2.6.1 || true
v 2.7.1 || true
v 2.8.1 || true
v 2.9.2 || true
v 2.9.8 || true
v 3.0.2 || true
v 3.0.4 || true
v 3.1.2 || true

# Modifications

# Variables

archive="http://www.xdebug.org/files/xdebug-$version.tgz"

# Le debugclient autonome était fourni avant la version 3.
# Désormais seuls sont proposés:
# - d'utiliser le client intégré à l'IDE
# - ou de télécharger dbgpClient, un binaire sans source, réécrit vraisemblablement en Go, et dont le contenu fait référence à l'inexistante URL https://github.com/derickr/dbgp-tools
pge $version 3 || opSiPasPas debugclient

# Rien À Installer: si on n'a rien à caler dans $INSTALLS/xdebug-x.y.z, on peut se contenter de se greffer à $INSTALLS/php-m.n.o
# En ce cas un : préfixant la destination indique que l'on renonce à notre dossier d'install.
rai=
option debugclient || rai=:

destiner "$rai$destphp"

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

monPhp="`php-config --prefix`"

cd xdebug-$version
phpize
./configure --enable-xdebug
make
for f in xdebug.so libxdebug.so.0.0
do
	[ -e "modules/$f" ] && break || true
done
sudo cp "modules/$f" "$monPhp/lib/"
ini="`php --ini | grep Loaded | cut -d : -f 2 | sed -e 's/^ *//' -e 's/ *$//'`"
sufiltrer "$ini" grep -v 'zend_extension=.*xdebug'
sufiltrer "$ini" sed -e '$a\
zend_extension="'"$monPhp"'/lib/'"$f"'"
'

if option debugclient
then
cd debugclient
./configure --prefix="$dest"
[ -e install.sh ] && chmod a+x install.sh
[ -e install-sh ] && chmod a+x install-sh
# La 2.7.1, étrangement, n'inclut plus l'install du debugclient.
if pge "$version" 2.7
then
	make
	sudo mkdir -p "$dest/bin"
	sudo cp debugclient "$dest/bin/"
else
sudo make install
fi
cd ..
fi

sutiliser -
