#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

absolutiseScripts() { SCRIPTS="$1" ; echo "$SCRIPTS" | grep -q ^/ || SCRIPTS="`dirname "$2"`/$SCRIPTS" ; } ; absolutiseScripts "`command -v "$0"`" "`pwd`/." ; while [ -h "$SCRIPTS" ] ; do absolutiseScripts "`readlink "$SCRIPTS"`" "$SCRIPTS" ; done ; SCRIPTS="`dirname "$SCRIPTS"`"
. "$SCRIPTS/util.sh"

logiciel=xdebug

# Travail préalable: notre PHP donne des contraintes de version.

analyserParametresPour --pour php "$@"

case `php-config --version | cut -d . -f 1-2` in
	5.3) argVersion="$argVersion < 2.3" ;;
	5.4) argVersion="$argVersion < 2.5" ;;
	5.5) argVersion="$argVersion < 2.6" ;;
	7.0) argVersion="$argVersion >= 2.4" ;;
	7.1) argVersion="$argVersion >= 2.5" ;;
	7.2) argVersion="$argVersion >= 2.6" ;;
	7.*) argVersion="$argVersion >= 2.7" ;;
esac

# Historique des versions gérées

v 2.1.0 && prerequis="$prerequis autoconf" || true
v 2.2.1 || true
v 2.2.5 || true
v 2.2.7 || true
v 2.4.1 || true
v 2.5.5 || true
v 2.6.0 || true
v 2.6.1 || true
v 2.7.1 || true

# Modifications

# Variables

archive="http://www.xdebug.org/files/xdebug-$version.tgz"

destiner

prerequis

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

monPhp="`php-config --prefix`"

cd xdebug-$version
phpize
./configure --enable-xdebug
make
for f in xdebug.so libxdebug.so.0.0
do
	[ -e "modules/$f" ] && break || true
done
sudo cp "modules/$f" "$monPhp/lib/"
ini="`php --ini | grep Loaded | cut -d : -f 2 | sed -e 's/^ *//' -e 's/ *$//'`"
sufiltrer "$ini" grep -v 'zend_extension=.*xdebug'
sufiltrer "$ini" sed -e '$a\
zend_extension="'"$monPhp"'/lib/'"$f"'"
'

cd debugclient
./configure --prefix="$dest"
[ -e install.sh ] && chmod a+x install.sh
[ -e install-sh ] && chmod a+x install-sh
# La 2.7.1, étrangement, n'inclut plus l'install du debugclient.
if pge "$version" 2.7
then
	make
	sudo mkdir -p "$dest/bin"
	sudo cp debugclient "$dest/bin/"
else
sudo make install
fi
cd ..

sutiliser -

rm -Rf "$TMP/$$"
