#!/bin/bash
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

logiciel=xdu

# Historique des versions gérées

version=3.0
modifs=tutimura

# Modifications

tutimura()
{
	for i in dirname i18n
	do
		patch -p1 < "`obtenir http://www.nn.iij4u.or.jp/~tutimura/$logiciel/$logiciel-$version.$i.patch`"
	done
}

# Variables

archive="http://sd.wareonearth.com/~phil/$logiciel/$logiciel-$version.tar.Z"
dest=/usr/local/$logiciel-$version

[ -d "$dest" ] && exit 0

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Compilation… >&2
cc -o xdu xdu.c xwin.c -L/usr/X11R6/lib -lXaw -lXt -lXext -lX11

echo Installation… >&2
sudo mkdir -p "$dest/bin" "$dest/man/man1"
sudo cp "$logiciel" "$dest/bin/"
sudo cp "$logiciel.man" "$dest/man/man1/"
sutiliser $logiciel-$version

rm -Rf /tmp/$$
