#!/bin/sh
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

DelieS() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) s="`pwd`/$s" ;; esac ; DelieS ; s="`dirname "$s"`" ; DelieS ; SCRIPTS="$s" ; } ; SCRIPTS
. "$SCRIPTS/util.sh"
. "$SCRIPTS/util.guili.nss.sh"

# Historique des versions gérées

OPTIONS_CONF=

v 1.2.27 && prerequis="libtool libxml libxslt openssl nss" && modifs="inclusions inclusionsNss nssPasMozilla" || true

option nss && virerPrerequis openssl || virerPrerequis nss
option nss && OPTIONS_CONF="$OPTIONS_CONF --with-nss --without-openssl --with-default-crypto=nss" || true

# Modifications

nssPasMozilla()
{
	# Pour retrouver le nom du paquet (pkg-config) nss et nspr, et l'inscrire dans les prérequis, le configure a toute une stratégie pour essayer les divers noms. Mais si aucune ne fonctionne (ex.: on lui a forcé un --with-nss=xxx, lui disant où trouver son nss sans pkg-config), il inscrit un nom de paquet nss par défaut: mozilla-nss. Or on sait bien, nous, que celui qu'on lui a demandé de prendre est le nss standard.
	filtrer configure sed -e '/^[A-Z_]*_PACKAGE=mozilla-/s/mozilla-//'
}

inclusions()
{
	filtrer configure sed \
		-e '/^COMMON_INCLUDE_DIR=/{
s#=.*#="'"$CMAKE_INCLUDE_PATH"'"#
s/:/ /g
}' \
		-e '/^COMMON_LIB_DIR=/{
s#=.*#="'"$CMAKE_LIBRARY_PATH"'"#
s/:/ /g
}'
}

# Variables

archive="http://www.aleksey.com/xmlsec/download/xmlsec1-$version.tar.gz"

prerequis

destiner

obtenirEtAllerDansVersion

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./configure --prefix="$dest" $OPTIONS_CONF

echo Compilation… >&2
make

echo Installation… >&2
sudoku make install

sutiliser
