#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

inclure scons
inclure glib
inclure mad
inclure ogg

logiciel=xmms2

# Historique des versions gérées

version=0.1DR2.2
modifs=sqlite3_tiger

# Modifications

sqlite3_tiger()
{
	sudo tee /usr/local/lib/pkgconfig/sqlite3.pc > /dev/null <<- TERMINE
	prefix=/usr
	exec_prefix=\${prefix}
	libdir=\${exec_prefix}/lib
	includedir=\${prefix}/include
	Name: sqlite3 
	Description: SQLite
	Requires:
	Version: 3.2.1
	Libs: -L\${libdir} -lsqlite3
	Cflags: -I\${includedir}
	TERMINE
}

# Variables

dest="/usr/local/$logiciel-$version"
archive=http://ovh.dl.sourceforge.net/sourceforge/$logiciel/$logiciel-$version.tar.gz

[ -d "$dest" ] && exit 0

if [[ $version = *-* ]] ; then
	obtenirEtAllerDansCvs -d $version $archive_cvs
else
	obtenirEtAllerDans "$archive"
fi

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration et compilation… >&2
scons PREFIX="$dest" LINKFLAGS="-lgthread-2.0"

echo Installation… >&2
sudo scons PREFIX="$dest" install
sudo utiliser "$logiciel-$version"

rm -Rf /tmp/$$
