#!/bin/bash
# Copyright (c) 2006 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

SCRIPTS="`command -v "$0"`" ; SCRIPTS="`dirname "$SCRIPTS"`" ; echo "$SCRIPTS" | grep -q "^/" || SCRIPTS=`pwd`/"$SCRIPTS"
. "$SCRIPTS/util.bash"

logiciel=yi

# Historique des versions gérées

version="2006-11-21@highlight bug when cursor is on end"
modifs=ghc66
OPTIONS_CONF=()

# Modifications

ghc66()
{
	# Paquets déjà inclus dans GHC 6.6
	filtrer yi.cabal sed -e '/^build-depends:/{
s/, *mtl//
s/, *fps//
}'
}

# Variables

archive_darcs=http://www.cse.unsw.edu.au/~dons/yi

[ -d "$dest" ] && exit 0

if [[ $version = *@* ]] ; then
	obtenirEtAllerDansDarcs -n "${version%%@*}" -p "${version#*@}" "$archive_darcs"
	autoreconf
	chmod +x Setup.hs configure
	version="${version%%@*}"
elif [[ $version = r* ]] ; then
	obtenirEtAllerDansSvn -r ${version#r} $archive_svn
elif [[ $version = *-* ]] ; then
	obtenirEtAllerDansCvs -d $version $archive_cvs
else
	obtenirEtAllerDans "$archive"
fi

dest="/usr/local/$logiciel-$version"

echo Correction… >&2
for modif in true $modifs ; do $modif ; done

echo Configuration… >&2
./Setup.hs configure --prefix="$dest"

echo Compilation… >&2
./Setup.hs build

echo Installation… >&2
./Setup.hs install
sudo utiliser $logiciel-$version

rm -Rf /tmp/$$
