#!/bin/sh

set -e

#- Utilitaires -----------------------------------------------------------------

diag()
{
	echo "[90m+ $*[0m" >&2
	"$@"
	status=$?
	return $status
}

diago()
{
	local output="`while [ $# -gt 0 ] ; do [ "x$1" = x-o ] && echo "$2" && exit 0 || shift ; done`"
	[ "x$1" = x-o ] && shift && shift || true
	if ! diag "$@"
	then
		[ -n "$output" ] && rm -f "$output" || true
		return $status
	fi
	return 0
}

#- Construction ----------------------------------------------------------------

all()
{
	soudoie
}

soudoie()
{
	local f
	for f in *.c
	do
		diago cc $CFLAGS -c -o "$f.o" "$f"
	done
	diago cc -o soudoie *.c.o
}

install()
{
	./make
	( [ `id -u` -eq 0 ] && chmod 4755 soudoie || sudo sh -c 'chown 0:0 soudoie && chmod 4755 soudoie' )
}

_listeTests()
{
	local tests="`grep TEST_ < soudoie.c | sed -e 's#TEST_[_A-Z0-9=]*#@&@#g' | tr @ '\012' | grep '^TEST_.' | sort -u`"
	# Pour les tests figurant sous deux forme (une prenant une valeur, une sans) on ne garde que celui avec valeur.
	local filtre="`echo "$tests" | tr ' ' '\012' | grep = | sed -e 's/=.*//' | tr '\012' '|'`"
	echo "$tests" | tr ' ' '\012' | egrep -v "^($filtre)$"
}

_test()
{
	local cflags="-DTEST $CFLAGS"
	_listeTests | while read test egal
	do
		echo "[90m=== $test ===[0m" >&2
		CFLAGS="$cflags -D$test" ./make && ./soudoie || echo "[31m# Sorti en erreur $?[0m" >&2
	done
}

quoi="$1"
case "$quoi" in
	"") quoi=all ;;
	test) quoi=_test ;;
esac
$quoi
