#!/bin/sh
# Copyright (c) 2019 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Sudo Ou Soudoie
# Se rabat sur un soudoie si sudo ne veut pas alors que soudoie est présent et autorisé.

jouer()
{
	local vraisudo="`IFS=: ; vraisudo $PATH`" # Des fois que sudo ait été remplacé par un lien vers nous.
	
	if ! $vraisudo -n -l "$@"
	then
		if command -v soudoie > /dev/null 2>&1 && soudoie -n -l "$@" 
		then
			soudoie "$@"
			return $?
		fi
	fi
	
	$vraisudo "$@"
}

# Ramène le chemin du vrai sudo, des fois que sudo ait été surchargé par un lien symbolique vers nous.
vraisudo()
{
	unset IFS
	local d
	for d in "$@" ""
	do
		[ ! -x "$d/sudo" ] || grep -q soudoie < "$d/sudo" 2> /dev/null || break
	done
	case "$d" in
		""|*/) true ;;
		*) d="$d/" ;;
	esac
	echo "${d}sudo"
}

jouer "$@"
